### ISSUE TITLE
Notifications still showing after cancelling

### ISSUE THREAD

**Issue by roelsprimont** [ionic-team/capacitor-plugins#158] opened 2020-12-22 16:46 UTC
### Plugin(s)
Local Notifications

### Capacitor Version

```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/electron not installed

[success] Android looking great! �
```

### Platform(s)

Android

### Current Behavior

Schedule a notification.
Then cancel it.
It still shows the notification at scheduled date after cancelling.

### Expected Behavior

Schedule a notification.
Then cancel it.
Don't show the cancelled notification anymore.

**Comment by jcesarmobile** [comment] 2021-02-24 18:25
can you provide a sample app reproducing the issue?

**Comment by jcesarmobile** [comment] 2021-06-01 13:48
closing since I can't reproduce and the user didn't provide a sample app where it could be reproduced.

**Closed by jcesarmobile** 2021-06-01 13:48 UTC
Labels: platform: android, question, triage
