### ISSUE TITLE
Google map generate a lot of error in CapacitorGoogleMapsPlugin.dispatchMapEvent

### ISSUE THREAD

**Issue by francolondra** [ionic-team/capacitor-plugins#1395] opened 2023-01-29 04:54 UTC
### Plugin(s)

@capacitor/google-maps

### Capacitor Version
    "@capacitor/google-maps": "4.3.1",

In Android Studio
E/Capacitor/Plugin: Unhandled Error: null.
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.capacitorjs.plugins.googlemaps.CapacitorGoogleMapsPlugin.dispatchMapEvent(CapacitorGoogleMapsPlugin.kt:541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:125)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:721)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)

D/Capacitor: Sending plugin error: {"save":false,"callbackId":"99599765","pluginId":"CapacitorGoogleMaps","methodName":"dispatchMapEvent","success":false,"error":{"message":"Unhandled Error: null.","code":"0"}}
V/Capacitor/CapacitorGoogleMapsPlugin: Notifying listeners for event isMapInFocus
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 99599768, pluginId: CapacitorGoogleMaps, methodName: dispatchMapEvent
V/Capacitor: callback: 99599768, pluginId: CapacitorGoogleMaps, methodName: dispatchMapEvent, methodData: {"id":"map","focus":false}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 99599769, pluginId: CapacitorGoogleMaps, methodName: dispatchMapEvent
V/Capacitor: callback: 99599769, pluginId: CapacitorGoogleMaps, methodName: dispatchMapEvent, methodData: {"id":"map","focus":false}

In Angular
polyfills.8a98a597f426b6b1.js:1 Unhandled Promise rejection: Unhandled Error: null. ; Zone: <root> ; Task: Promise.then ; Value: Error: Unhandled Error: null.
    at returnResult (VM3:741:32)
    at win.androidBridge.onmessage (VM3:716:21) Error: Unhandled Error: null.
    at returnResult (http://localhost/:741:32)
    at win.androidBridge.onmessage (http://localhost/:716:21)

### Platform(s)
android

### Current Behavior
I started to move in the map and other page and I showed a lot of console log with this
![WhatsApp Image 2023-01-29 at 1 47 33 AM](https://user-images.githubusercontent.com/40376158/215305585-5993c792-0941-4223-ba7c-fb6baa768ca1.jpeg)

and suddenly appear this error and the other page started to frozen and the modal of marker open multiple times

### Expected Behavior
for the first time , the map doesn't work when I open other page and I would have to be able to move for other place and the map should work fine.

### Code Reproduction
explain in before items

**Comment by francolondra** [comment] 2023-02-02 02:12
I already sent everything I can send, because sending a demo compromises the project.

**Comment by jcesarmobile** [comment] 2023-02-20 18:05
closing since the reporter didn't provide a sample app that reproduces the issue

**Closed by jcesarmobile** 2023-02-20 18:05 UTC
Labels: platform: android, needs reproduction
