### ISSUE TITLE
Camera (capacitor 3 @capacitor/camera) getPhoto() doesn't work the first time

### ISSUE THREAD

**Issue by Synthx** [ionic-team/capacitor-plugins#653] opened 2021-10-11 08:47 UTC
### Plugin(s)

@capacitor/camera 1.1.0

### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

### Platform(s)

iOS - 14.X - Safari & Native

### Current Behavior

When calling Camera.getPhoto(...), the first promise never ended (in the same time the node_modules_capacitor_camera_dist_esm_web_js.js is lazy loaded), and I need to call Camera.getPhoto(...) a second time to display the prompt menu

### Expected Behavior

Camera.getPhoto(...) should work every time the method is called

### Code Reproduction

```
async openCamera() async {
    const file = await Camera.getPhoto({
                        quality: 50,
                        allowEditing: false,
                        webUseInput: true,
                        resultType: CameraResultType.Uri,
                        source: CameraSource.Prompt,
                    });
   console.log(file);
}
```

### Other Technical Details

Reproductible on both emulators & real devices

**Comment by Ionitron** [comment] 2021-10-11 11:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-11-05 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-11-05 00:01 UTC
Labels: platform: ios, needs reproduction, needs reply
