### ISSUE TITLE
Android capacitor/preferences plugin returns null when getting an item stored with capacitor/storage plugin

### ISSUE THREAD

**Issue by richardkshergold** [ionic-team/capacitor-plugins#1263] opened 2022-11-08 12:01 UTC
We've migrated an app from Capacitor 3 to Capacitor 4 (part of which was handling the renaming of the **capacitor/storage** plugin to **capacitor/preferences**).  All is working fine with the new storage plugin until I try an upgrade test on a couple of Android devices which have the old Capacitor 3 app installed.  When the devices are upgraded to the new app, a value of null is returned when the app tries to retrieve anything from storage.  iOS works fine.

The two android devices are:

Pixel 4 running Android 13
Samsung Galaxy A10 running Android 11

Here is our package.json dependencies:

"dependencies": {
    "@angular/common": "~13.2.7",
    "@angular/core": "~13.2.7",
    "@angular/forms": "~13.2.7",
    "@angular/platform-browser": "~13.2.7",
    "@angular/platform-browser-dynamic": "~13.2.7",
    "@angular/router": "~13.2.7",
    "@angular/service-worker": "~13.2.7",
    "@capacitor-community/file-opener": "^1.0.2",
    "@capacitor-community/http": "^1.4.1",
    "@capacitor/android": "^4.2.0",
    "@capacitor/app": "^4.0.0",
    "@capacitor/browser": "^4.0.1",
    "@capacitor/core": "^4.2.0",
    "@capacitor/device": "^4.0.0",
    "@capacitor/haptics": "^4.0.0",
    "@capacitor/ios": "^4.2.0",
    "@capacitor/keyboard": "^4.0.0",
    "@capacitor/network": "^4.0.0",
    "@capacitor/preferences": "^4.0.1",
    "@capacitor/push-notifications": "^4.1.0",
    "@capacitor/splash-screen": "^4.0.0",
    "@capacitor/status-bar": "^4.0.0",
    "@capawesome/capacitor-badge": "^2.0.0",
    "@ionic-native/app-rate": "^5.33.6",
    "@ionic-native/app-version": "^5.33.6",
    "@ionic-native/badge": "^5.33.6",
    "@ionic-native/calendar": "^5.33.6",
    "@ionic-native/core": "^5.33.6",
    "@ionic-native/deeplinks": "^5.33.6",
    "@ionic-native/file": "^5.33.6",
    "@ionic-native/file-transfer": "^5.33.6",
    "@ionic-native/fingerprint-aio": "^5.33.6",
    "@ionic-native/http": "^5.33.6",
    "@ionic-native/in-app-browser": "^5.33.6",
    "@ionic-native/market": "^5.33.6",
    "@ionic-native/safari-view-controller": "^5.36.0",
    "@ionic-native/secure-storage": "^5.36.0",
    "@ionic-native/splash-screen": "^5.33.6",
    "@ionic-native/status-bar": "^5.33.6",
    "@ionic/angular": "^6.2.7",
    "@ionic/storage": "^3.0.6",
    "@ng-idle/core": "^11.1.0",
    "@ng-idle/keepalive": "^11.0.3",
    "@ngrx/effects": "^13.2.0",
    "@ngrx/store": "^13.2.0",
    "@ngrx/store-devtools": "^13.2.0",
    "@okta/okta-angular": "^5.2.0",
    "@okta/okta-auth-js": "^6.7.3",
    "@sentry/browser": "^7.13.0",
    "@sentry/cli": "^2.5.2",
    "@sentry/wizard": "^2.2.0",
    "angular-linky": "^1.2.2",
    "capacitor-secure-storage-plugin": "^0.6.4",
    "cordova-plugin-advanced-http": "3.2.2",
    "cordova-plugin-calendar": "^5.1.6",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "https://github.com/sitewaerts/cordova-plugin-file-transfer.git",
    "cordova-plugin-fingerprint-aio": "^5.0.1",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-safariviewcontroller": "2.0.0",
    "cordova-plugin-secure-storage-echo": "5.1.1",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.3",
    "faye": "^1.4.0",
    "ionic-appauth": "github:wi3land/ionic-appauth",
    "jetifier": "^1.6.8",
    "moment": "^2.29.4",
    "rxjs": "~6.6.0",
    "tinycolor2": "^1.4.2",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },

**Comment by Ionitron** [comment] 2022-11-08 13:11
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-24 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-24 00:02 UTC
Labels: needs reproduction, needs reply
