### ISSUE TITLE
Camera.getPhoto() not return error message in Android

### ISSUE THREAD

**Issue by Brullworfel** [ionic-team/capacitor-plugins#488] opened 2021-06-18 14:10 UTC
## Bug Report

When error occurs in `Camera.getPhoto()`, I get `error.errorMessage` on iOS, but on Android `error` is an empty object.

Here is my code:

`Camera.getPhoto({
      resultType: CameraResultType.Uri,
      source: CameraSource.Prompt,
      webUseInput: true
    }).then(
      photo => {
        return this.accountService.uploadAvatar(photo.webPath);
      },
      error => {
        console.error(error);
     }
   );`

### Plugin(s)
Camera 1.0.1

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
Android 10

**Comment by Ionitron** [comment] 2021-06-18 14:24
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-07-04 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-07-04 00:01 UTC
Labels: needs reply, needs reproduction, platform: android
