### ISSUE TITLE
Change the spinner position on the Splash Screen

### ISSUE THREAD

**Issue by GosuMania** [ionic-team/capacitor-plugins#821] opened 2022-02-14 22:31 UTC
Plugin
Capacitor 3 Splash Screen

Description
Splash screen typically have a logo or other feature in the center of the screen. Currently the spinner on the Splash Screen plugin is fixed to the center horizontally and vertically. Being able to configure the spinner to appear elsewhere on the screen would be useful.

Platform(s)
iOS
Android

Preferred Solution
Add an option to capacitor.config.json to determine the position of the spinner

Is it possible?

**Comment by jcesarmobile** [comment] 2022-02-15 08:13
Closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/37

**Closed by jcesarmobile** 2022-02-15 08:13 UTC
