### ISSUE TITLE
getDeliveredNotifications does not work on iOS when hitting the notification banner

### ISSUE THREAD

**Issue by bstrasburg** [ionic-team/capacitor-plugins#881] opened 2022-03-18 19:46 UTC
## Bug Report

getDeliveredNotifications does not work on iOS when hitting the notification banner but works when clicking on the app icon. Android works fine.

### Plugin(s)
	"dependencies": {
		"@capacitor/android": "3.3.3",
		"@capacitor/cli": "^3.4.0",
		"@capacitor/core": "3.3.3",
		"@capacitor/ios": "3.3.3",
		"@capacitor/keyboard": "1.2.0",
		"@capacitor/status-bar": "1.0.6",
		"@ionic/cli": "^6.18.1",
		"@ionic/vue": "^6.0.4",
		"@ionic/vue-router": "^6.0.0",
		"axios": "^0.24.0",
		"axios-case-converter": "^0.9.0",
		"core-js": "^3.6.5",
		"dayjs": "^1.10.7",
		"install": "^0.13.0",
		"npm-check-updates": "^12.2.1",
		"sass": "^1.45.1",
		"sass-loader": "^12.4.0",
		"vue": "^3.2.26",
		"vue-loader": "^17.0.0",
		"vue-router": "^4.0.12",
		"vue-tabler-icons": "^2.1.0",
		"vuex": "^4.0.2",
		"ws": "^8.4.2"
	},

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.0
  @capacitor/android: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS
iPhone 11
Software version 15.3.1

### Current Behavior
- getDeliveredNotifications() returns and empty notifications array when clicking on iOS notification banner
- however clicking on the app icon returns all notifications

### Expected Behavior
- getDeliveredNotifications() should return notifications when clicking the notification banner

### Code Reproduction
```
await PushNotifications.addListener('registration', async(token) => {
               const notificationList =
                await PushNotifications.getDeliveredNotifications().then((resp: any) => {
                     console.log('notifications', resp);
                });
                console.log('notificationList', notificationList);
       
 });
```

**Comment by Ionitron** [comment] 2022-03-21 09:41
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by bstrasburg** [comment] 2022-03-21 12:16
This is a base Vue 3 app, just put the code in setup(). Not sure how I can give you more code....

**Comment by bstrasburg** [comment] 2022-03-21 12:21
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

This is a base Vue 3 app, just put the code in setup(). Not sure how I can give you more code....

**Comment by jcesarmobile** [comment] 2022-03-22 15:31
A full app that can be run by us to verify the issue

**Comment by Ionitron** [comment] 2022-04-07 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-07 00:02 UTC
Labels: platform: ios, needs reproduction, needs reply
