### ISSUE TITLE
@capacitor/inappbrowser is closed automatically when switching App from background to foreground (by clicking App Icon in Home device)

### ISSUE THREAD

**Issue by kientrant1** [ionic-team/capacitor-plugins#2211] opened 2024-10-17 14:44 UTC
### Plugin(s)
@capacitor/inappbrowser

### Capacitor Version
v6

### Platform(s)
Android

### Current Behavior
- Open URL with InApp Browser plugin
- Minimize App into background (foreground -> background)
- Click App Icon to open App again (background -> foreground)
- InApp Browser is closed automatically

### Expected Behavior
- Open URL with InApp Browser plugin
- Minimize App into background (foreground -> background)
- Click App Icon to open App again (background -> foreground)
- InApp Browser still remain with the opend URL as before that

**Comment by intobrackets** [comment] 2024-10-19 19:20
I'm experiencing the same issue described here. After running the application, it automatically closes with a message:
"App Closed because this app has a bug".

**Comment by Ionitron** [comment] 2024-10-30 13:49
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-11-15 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-11-15 00:04 UTC
Labels: platform: android, needs reproduction
