### ISSUE TITLE
Catching if neither buttons in Dialog was clicked

### ISSUE THREAD

**Issue by mrtnrs** [ionic-team/capacitor-plugins#1982] opened 2024-01-05 12:12 UTC
### Plugin
Dialog

### Description
Could we have a different value for when user clicks outside the Dialog, not false similar to the cancellation button. So basically you could catch when user clicked neither of the buttons and you could prevent the Dialog from closing?

### Platform(s)
Android

### Preferred Solution
Set value boolean to undefined when neither buttons are clicked, not false.

**Comment by Ionitron** [comment] 2024-01-08 13:50
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-01-24 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-24 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
