### ISSUE TITLE
Unable to Add Custom Sound for Push Notifications in Ionic 6 (iOS)

### ISSUE THREAD

**Issue by bassamIHabash** [ionic-team/capacitor-plugins#1621] opened 2023-05-28 17:41 UTC
I am currently using Ionic 6 with the latest version and have encountered an issue with push notifications on iOS. It appears that the push notification functionality in Ionic 6 does not support adding a custom sound for iOS devices. This limitation prevents me from providing a unique audio experience for users when receiving push notifications.

I would like to inquire whether there is a workaround available to enable the support for custom sounds in iOS push notifications within Ionic 6. Alternatively, if there is a custom plugin that can be utilized to achieve this functionality, please provide guidance on how to integrate it into an Ionic 6 project.

This feature is crucial for enhancing the user experience and personalization of notifications within our application. It would greatly benefit our development team and our users if this limitation could be addressed or if there are alternative solutions available.

Thank you for your attention to this matter, and I look forward to your guidance and assistance in resolving this issue.

Steps to Reproduce:
1. Create an Ionic 6 project with the latest version.
2. Implement push notification functionality for iOS.
3. Attempt to add a custom sound for iOS push notifications.
4. Observe that custom sound support is not available or functional.

Expected Result:
The Ionic 6 push notification system should provide the ability to add custom sounds for iOS push notifications, allowing developers to provide a unique audio experience for users.

Actual Result:
The push notification functionality in Ionic 6 does not support adding custom sounds for iOS push notifications, limiting the customization options available for audio notifications.

Environment:
- Ionic version: 6.x.x
- iOS version: [Specify the iOS version you are testing on, e.g., iOS 14.5]
- Device: [Specify the device model you are testing on, e.g., iPhone 11]

**Comment by Ionitron** [comment] 2023-05-30 08:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-15 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-15 00:03 UTC
Labels: needs reproduction, needs reply
