### ISSUE TITLE
@capacitor/geolocation does NOT throw an error even though GPS is unavailable

### ISSUE THREAD

**Issue by ZweiEuro** [ionic-team/capacitor-plugins#1696] opened 2023-07-23 06:01 UTC
Hi!
Given this issue: https://github.com/ionic-team/capacitor-plugins/issues/822

I'd assume that devices where the google play service is not available, and thereby GPS is not available. `checkPermissions` should throw an error, it doesn't though.

This took me forever to debug since e.g. on /e/os operating system (one without playstore, and with which i am developing) it just doesn't return anything upon requesting a location but returns just fine when checking permissions.

Please consider printing at least a warning or something so other people don't waste 3h searching for something that's not even a bug. Or consider adding "This requires playstore location service to work properly" to the docs.

**Comment by Ionitron** [comment] 2023-07-24 09:03
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by ZweiEuro** [comment] 2023-07-24 09:38
run your own example on any non playstore device: https://github.com/ionic-team/capacitor/issues/6763

There is nothing more to it.

**Comment by Ionitron** [comment] 2023-11-11 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-11 00:03 UTC
Labels: needs reproduction, needs reply
