### ISSUE TITLE
Cannot fetch images after camera pickImages (CORS Error)

### ISSUE THREAD

**Issue by michiherbst** [ionic-team/capacitor-plugins#705] opened 2021-11-26 12:36 UTC
### Plugin(s)
@capacitor/camera: 1.2.1

### Capacitor Version
@capacitor/android: 3.3.2
@capacitor/cli: 3.3.2
@capacitor/core: 3.3.2
@capacitor/ios: 3.3.2

### Platform(s)
iOS

### Current Behavior
After picking the images i can't fetch the file contents to process the images due to a CORS Error. If i set the url as image src the image loads without any problem.

### Expected Behavior
Image blob should be accessible in the GalleryPhotos response, or fetch from capacitor:// should be possible. 

### Code Reproduction

```
const images = await Camera.pickImages({
      quality: 90,
      limit: 20,
});

for (const photo of images.photos) {
      const imageResponse = await fetch(photo.webPath);
      // Origin http://localhost:4000 is not allowed by Access-Control-Allow-Origin.
      console.log(imageResponse);
}
```
![image](https://user-images.githubusercontent.com/15610195/143581597-81422849-7446-4829-a5b8-3885c4d5ed6a.png)

### Other Technical Details
I use a dev server with the following capacitor config:
```
const config: CapacitorConfig = {
    appId: "com.myapp.app",
    appName: "MyApp",
    webDir: "out",
    bundledWebRuntime: false,
    server: {
        url: `http://localhost:4000`,
    },
};
```

**Comment by jcesarmobile** [comment] 2021-11-30 15:47
thanks for reporting the issue
it's already reported in Capacitor repository since the issue is caused there, so closing this one as duplicate
https://github.com/ionic-team/capacitor/issues/4089

**Closed by jcesarmobile** 2021-11-30 15:47 UTC
Labels: platform: ios
