### ISSUE TITLE
Capacitor status bar not changing status bar color

### ISSUE THREAD

**Issue by LuizTokuhara** [ionic-team/capacitor-plugins#465] opened 2021-06-08 23:41 UTC
## Bug Report
The status bar plugin is not changing the the status bar color (background and text).

### Plugin(s)
@capacitor/status-bar

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
```

### Platform(s)

Android 11 (Xiaomi Mi 10 Lite)

### Current Behavior

After setting the status bar style and background, when running the app on device, nothing changed.

### Expected Behavior

Change the status bar color.

### Code Reproduction

```
async setStatusBar(): Promise<void> {
    await StatusBar.setStyle({ style: Style.Dark });
    await StatusBar.setBackgroundColor({ color: "#ffffff" });
}
```

![image](https://user-images.githubusercontent.com/26283844/121271309-cd9b7180-c899-11eb-9ed9-caa77c20e8fc.png)

**Comment by Ionitron** [comment] 2021-06-09 12:41
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by LuizTokuhara** [comment] 2021-06-09 13:59
Code reproduction at https://github.com/LuizTokuhara/capacitor-statusbar

**Comment by jcesarmobile** [comment] 2021-06-09 15:09
What do you expect to happen?

I've tested on Android 9 and 11 devices and it's turning the status bar white and the text also white.

`undefined` is just what the plugin return value, in this case it doesn't return anything, so it's `undefined`, not that the function is `undefined`

**Comment by LuizTokuhara** [comment] 2021-06-09 16:40
Strange, I have tested here and it is not turning the status bar to white.
Maybe because the android is set to dark mode?

**Comment by jcesarmobile** [comment] 2021-06-09 16:45
I have dark mode enabled and it's still setting the status bar to white without problems, so might be some Xiaomi specific problem.

**Comment by LuizTokuhara** [comment] 2021-06-09 16:47
> I have dark mode enabled and it's still setting the status bar to white without problems, so might be some Xiaomi specific problem.

Ok, got it, thanks

**Comment by jcesarmobile** [comment] 2021-06-09 16:48
do you have miui or some other launcher?
looks like miui has some problems with status bar colors
https://www.reddit.com/r/Xiaomi/comments/hyqqmf/miui_12_status_bar_color_constantly_changing_when/

**Comment by LuizTokuhara** [comment] 2021-06-19 21:13
> do you have miui or some other launcher?
> looks like miui has some problems with status bar colors
> https://www.reddit.com/r/Xiaomi/comments/hyqqmf/miui_12_status_bar_color_constantly_changing_when/

I am using Miui, but I haver another app (ionic 4 with cordova) and the status bar is changing the background color... Using the same phone.

**Comment by jcesarmobile** [comment] 2021-12-08 11:54
Sorry, I'm closing the issue as won't fix because I can't reproduce.

I've tested in a wide variety of devices and Android versions including a few Xiaomi devices, with and without dark mode enabled and the background color is set on all of them.

Also compared our status-bar plugin code with Cordova's one and they do exactly the same, the only difference is the Cordova plugin uses reflection instead of calling the native API directly, but I don't think that would make a difference.

**Closed by jcesarmobile** 2021-12-08 11:54 UTC
Labels: wontfix, platform: android, plugin: status-bar
