### ISSUE TITLE
@capacitor/filesystem error reasons

### ISSUE THREAD

**Issue by ecc521** [ionic-team/capacitor-plugins#2136] opened 2024-06-17 00:49 UTC
## Feature Request

A way to determine the reason why a filesystem operation failed. 

### Plugin
@capacitor/filesystem

### Description
It should be possible to determine why a filesystem operation failed for known failure reasons (like file not found). As is, different platforms have different error messages, and those can change over time, so string checking is far from optimal and results in apps breaking with updates. 

### Platform(s)
This should be available on all platforms. 

### Preferred Solution
Provide enums for Error.cause (or a custom property) allowing for determining if an error was triggered for a specific reason. 

### Additional Context
This was previously requested for Android specifically in 2021 in #326.

**Comment by jcesarmobile** [comment] 2024-06-17 09:46
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/326

**Closed by jcesarmobile** 2024-06-17 09:46 UTC
Labels: triage
