### ISSUE TITLE
Browser 5.1.0: "No Activity found to handle Intent"

### ISSUE THREAD

**Issue by TonyGiorgio** [ionic-team/capacitor-plugins#1881] opened 2023-11-04 17:25 UTC
### Plugin(s)
Browser 5.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
"No Activity found to handle Intent" when calling `Browser.Open` on an installed app from my capacitor android app.

### Expected Behavior
It should open, like it still correctly does on 5.0.6

### Code Reproduction

```
export function openLinkProgrammatically(href?: string) {
    if (!href) return;
    if (Capacitor.isNativePlatform()) {
        Browser.open({ url: href || "", windowName: "_blank" });
    } else {
        window.open(href || "", "_blank");
    }
}
```

### Additional Context
I suspect something was wrong with this: https://github.com/ionic-team/capacitor-plugins/pull/1758

**Comment by Ionitron** [comment] 2023-11-06 09:31
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-11-22 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-22 00:03 UTC
Labels: platform: android, needs reproduction, needs reply

**Comment by TonyGiorgio** [comment] 2023-11-22 00:09
Not completed
