### ISSUE TITLE
Android Oreo (API 2) doesn't show proper Splash Screen

### ISSUE THREAD

**Issue by vincentsartoko** [ionic-team/capacitor-plugins#1825] opened 2023-10-03 17:19 UTC
### Plugin(s)

`"@capacitor/splash-screen": "^5.0.6"`

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

I already did `npx @capacitor/assets generate --android --assetPath /public/media/generate` and some assets were generated, however when using Android Oreo (API 26), the splash screen didn't show properly
![image](https://github.com/ionic-team/capacitor-plugins/assets/56718724/7f3a4b95-2149-4f06-9023-9d25daa24436)

### Expected Behavior

Show my custom splash screen and not default Android logo

**Comment by Ionitron** [comment] 2023-10-04 09:49
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-10-20 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-10-20 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
