### ISSUE TITLE
FileSystem readFile throwing not implemented error on iOS

### ISSUE THREAD

**Issue by Ferkonet** [ionic-team/capacitor-plugins#348] opened 2021-04-15 17:56 UTC
### Plugin(s)

@capacitor/filesystem

### Capacitor Version
@capacitor/cli: 3.0.0-beta.6
@capacitor/core: 3.0.0-beta.6
@capacitor/android: 3.0.0-rc.0
@capacitor/ios: 3.0.0-beta.6

### Platform(s)

iOS

### Current Behavior
I want to read an image from file system (location data directory). Access is available and file exists. I get the following error:

Error: "Filesystem" plugin is not implemented on ios

### Expected Behavior

Should return a ReadFileResult with containing the data.

### Code Reproduction

```
async readFile(fullpath: string) {
    let result = await Filesystem.readFile({
      path: fullpath
    });
    console.log(result);
  }
```

**Comment by jcesarmobile** [comment] 2021-04-15 21:15
Try updating core and ios to rc 0, you are on beta 6, then do a new npm run build and npx cap sync

**Comment by jcesarmobile** [comment] 2021-04-29 17:36
closing as I can't reproduce and there wasn't any response

**Closed by jcesarmobile** 2021-04-29 17:36 UTC
Labels: platform: ios, triage

**Comment by alcalyn** [comment] 2022-05-17 22:25
I'm getting the same error for Android: `Error: "Filesystem" plugin is not implemented on android`

```
    "@capacitor/android": "3.4.3",
    "@capacitor/app": "1.1.1",
    "@capacitor/core": "3.4.3",
    "@capacitor/filesystem": "^1.1.0",

    "@capacitor/cli": "3.4.3",
```

Just installed it and tried:

``` js
import { Filesystem, Directory, Encoding } from '@capacitor/filesystem';

Filesystem.readFile({path: 'file:///data/user/0/io.ionic.starter/files/...jpg'})
    .then((content) => {
        console.log('content', {content});
    })
    .catch((err) => console.error(err))
;
```
