### ISSUE TITLE
Keyboard calculates height wrong when using setDecorFitsSystemWindows and resizeOnFullScreen

### ISSUE THREAD

**Issue by digaus** [ionic-team/capacitor-plugins#1335] opened 2022-12-16 14:56 UTC
### Plugin(s)

KeyboardPlugin

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

When using `setDecorFitsSystemWindows` in `MainActivity.java` and the flag `resizeOnFullScreen` the `computeUsableHeight` function returns the wrong size because it does not add the bottom offset.

### Expected Behavior

Add a new flag to which adds the bottom offset when possible:

```
                private void possiblyResizeChildOfContent() {
                    int usableHeightNow = computeUsableHeight();
                    if (usableHeightPrevious != usableHeightNow) {
                        frameLayoutParams.height = usableHeightNow + getBottomOffset();
                        mChildOfContent.requestLayout();
                        usableHeightPrevious = usableHeightNow;
                    }
                }


                private int getBottomOffset() {
                    if (resizeOnFullScreenOffset && Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                                return activity.getWindow().getDecorView().getRootWindowInsets().getInsetsIgnoringVisibility(WindowInsets.Type.systemBars()).bottom;
                            }
                            return activity.getWindow().getDecorView().getRootWindowInsets().getStableInsetBottom();
                        }
                    }
                    return 0;
                }

```

### Code Reproduction

Demo project: https://github.com/digaus/keyboard-demo/tree/main

**Comment by Ionitron** [comment] 2022-12-16 15:11
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by digaus** [comment] 2022-12-16 15:46
Demo project: https://github.com/digaus/keyboard-demo/tree/main

Change `resizeOnFullScreen` to true and navigation bar will not overlay the content anymore

**Comment by NePheus** [comment] 2022-12-26 12:36
https://www.npmjs.com/package/capacitor-adjust-resize does this plugin solves your issue? I initially created it because I set android:windowTranslucentNavigation in our app and also had the problem with the missing bottom spacing.

**Comment by digaus** [comment] 2023-01-02 08:25
> https://www.npmjs.com/package/capacitor-adjust-resize does this plugin solves your issue? I initially created it because I set android:windowTranslucentNavigation in our app and also had the problem with the missing bottom spacing.

This seems to be working fine :)

**Comment by NePheus** [comment] 2023-01-02 08:29
FYI: https://github.com/ionic-team/capacitor/discussions/5525

**Comment by digaus** [comment] 2023-01-22 19:25
> FYI: [ionic-team/capacitor#5525](https://github.com/ionic-team/capacitor/discussions/5525)

Just got time to do some more testing and it appears, that when Keyboard is open, the bottom safe area gets removed and the Keyboard overlays the content

**Comment by jcesarmobile** [comment] 2023-01-24 12:38
Thanks for the sample app, but I don't see the bug you describe on it.
When I change `resizeOnFullScreen` to true the WebView resizes and the sample app doesn't show any indication that the height is calculated wrong.

Can you change the sample app to maybe make the input fixed to the bottom or any other change that would make clear that the size is not correct?

**Comment by digaus** [comment] 2023-01-24 13:07
> Thanks for the sample app, but I don't see the bug you describe on it. When I change `resizeOnFullScreen` to true the WebView resizes and the sample app doesn't show any indication that the height is calculated wrong.
> 
> Can you change the sample app to maybe make the input fixed to the bottom or any other change that would make clear that the size is not correct?

Update the repo. Now added a red footer. In screenshot you can see that when using `"resizeOnFullScreen": true` that the color is not red behind the button bar.

**Comment by NePheus** [comment] 2023-01-24 17:16
> > FYI: [ionic-team/capacitor#5525](https://github.com/ionic-team/capacitor/discussions/5525)
> 
> Just got time to do some more testing and it appears, that when Keyboard is open, the bottom safe area gets removed and the Keyboard overlays the content :/

Same problems that I had. Therefore I also created this plugin https://www.npmjs.com/package/capacitor-areas

```
Areas.getNavigationBarHeight().then((result) => {
    document.documentElement.style.setProperty('--ion-safe-area-bottom', `${result.value}px`);
});
```
And check that this bottom padding is really set somewhere below the button, because you have to set it by yourself if you dont use the ion-footer of ionic. Hope this helps.

**Comment by digaus** [comment] 2023-01-24 17:34
> > > FYI: [ionic-team/capacitor#5525](https://github.com/ionic-team/capacitor/discussions/5525)
> > 
> > 
> > Just got time to do some more testing and it appears, that when Keyboard is open, the bottom safe area gets removed and the Keyboard overlays the content :/
> 
> Same problems that I had. Therefore I also created this plugin https://www.npmjs.com/package/capacitor-areas
> 
> ```
> Areas.getNavigationBarHeight().then((result) => {
>     document.documentElement.style.setProperty('--ion-safe-area-bottom', `${result.value}px`);
> });
> ```
> 
> And check that this bottom padding is really set somewhere below the button, because you have to set it by yourself if you dont use the ion-footer of ionic. Hope this helps.

No, `--ion-safe-area-bottom` is already set via another plugin. See the height of the red area, both are the same and include the offset. The problem is that the webview itself has the wrong height on the second screenshot.

**Comment by vilic** [comment] 2023-03-31 23:48
This can be fixed by setting the initial value `-1` instead of the calculated height if the keyboard is not shown.

Here the patch:

```diff
diff --git a/node_modules/@capacitor/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java b/node_modules/@capacitor/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java
index 983fdb9..452e9f2 100644
--- a/node_modules/@capacitor/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java
+++ b/node_modules/@capacitor/keyboard/android/src/main/java/com/capacitorjs/plugins/keyboard/Keyboard.java
@@ -13,9 +13,9 @@ import android.view.Window;
 import android.view.WindowInsets;
 import android.view.inputmethod.InputMethodManager;
 import android.widget.FrameLayout;
+
 import androidx.annotation.Nullable;
 import androidx.appcompat.app.AppCompatActivity;
-import com.getcapacitor.Logger;
 
 public class Keyboard {
 
@@ -63,9 +63,6 @@ public class Keyboard {
 
                 @Override
                 public void onGlobalLayout() {
-                    if (resizeOnFullScreen) {
-                        possiblyResizeChildOfContent();
-                    }
                     Rect r = new Rect();
                     //r will be populated with the coordinates of your view that area still visible.
                     rootView.getWindowVisibleDisplayFrame(r);
@@ -92,22 +89,32 @@ public class Keyboard {
                     int heightDiff = screenHeight - resultBottom;
 
                     int pixelHeightDiff = (int) (heightDiff / density);
-                    if (keyboardEventListener != null) {
-                        if (pixelHeightDiff > 100 && pixelHeightDiff != previousHeightDiff) { // if more than 100 pixels, its probably a keyboard...
+
+                    if (pixelHeightDiff > 100 && pixelHeightDiff != previousHeightDiff) { // if more than 100 pixels, its probably a keyboard...
+                        if (resizeOnFullScreen) {
+                            possiblyResizeChildOfContent(true);
+                        }
+
+                        if (keyboardEventListener != null) {
                             keyboardEventListener.onKeyboardEvent(EVENT_KB_WILL_SHOW, pixelHeightDiff);
                             keyboardEventListener.onKeyboardEvent(EVENT_KB_DID_SHOW, pixelHeightDiff);
-                        } else if (pixelHeightDiff != previousHeightDiff && (previousHeightDiff - pixelHeightDiff) > 100) {
+                        }
+                    } else if (pixelHeightDiff != previousHeightDiff && (previousHeightDiff - pixelHeightDiff) > 100) {
+                        if (resizeOnFullScreen) {
+                            possiblyResizeChildOfContent(false);
+                        }
+
+                        if (keyboardEventListener != null) {
                             keyboardEventListener.onKeyboardEvent(EVENT_KB_WILL_HIDE, 0);
                             keyboardEventListener.onKeyboardEvent(EVENT_KB_DID_HIDE, 0);
                         }
-                    } else {
-                        Logger.warn("Native Keyboard Event Listener not found");
                     }
+
                     previousHeightDiff = pixelHeightDiff;
                 }
 
-                private void possiblyResizeChildOfContent() {
-                    int usableHeightNow = computeUsableHeight();
+                private void possiblyResizeChildOfContent(boolean keyboardShown) {
+                    int usableHeightNow = keyboardShown ? computeUsableHeight() : -1;
                     if (usableHeightPrevious != usableHeightNow) {
                         frameLayoutParams.height = usableHeightNow;
                         mChildOfContent.requestLayout();
```

**Closed** 2023-04-18 17:30 UTC
Labels: platform: android, plugin: keyboard, type: bug
