### ISSUE TITLE
Can not get photos from selected photos in iOS (photo library)

### ISSUE THREAD

**Issue by marioshtika** [ionic-team/capacitor-plugins#920] opened 2022-04-11 09:04 UTC
### Plugin(s)
@capacitor/camera: 1.3.1

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
When I am trying to add a new photo from the library in iOS, it first gives me the option to select from all my photos in my library, and then it asks me to "Select More Photos..." or "Keep Current Selection"
Below are the screenshots of the workflows described above.
![1](https://user-images.githubusercontent.com/3079663/162701568-6cfc1a1a-7ca8-48ac-979d-44d0f6d11852.png)
![2](https://user-images.githubusercontent.com/3079663/162701624-61e6a9fc-2676-43be-85b5-06454aab9515.png)
![3](https://user-images.githubusercontent.com/3079663/162701658-fdbf73e2-3e94-4547-98b6-4385d8ef04be.png)
![4](https://user-images.githubusercontent.com/3079663/162701680-1330bfda-24e6-4717-8f24-3ba4e76bbaad.png)

### Expected Behavior
When trying to add a new photo from the library in iOS, at first it should ask you to "Select More Photos..." or "Keep Current Selection" then you should choose from one of the selected photos.

### Code Reproduction
```
Camera.getPhoto({
    source: CameraSource.Prompt,
    resultType: CameraResultType.Uri
});
```

**Comment by Ionitron** [comment] 2022-04-18 09:39
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-04 00:03 UTC
Labels: platform: ios, needs reproduction, needs reply
