### ISSUE TITLE
[google-maps] Unexpectedly found nil

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/capacitor-plugins#1710] opened 2023-07-28 00:19 UTC
### Plugin(s)
`"@capacitor/google-maps": "^5.1.2",`

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
IOS

### Current Behavior

```
CapacitorGoogleMaps/Map.swift:129: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2023-07-27 20:14:05.769063-0400 ampido[47665:3118612] CapacitorGoogleMaps/Map.swift:129: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

Sometimes I get this crash of the google maps. I am not sure what is the issue, but maybe I will identify it. I just wanted to post this still, since it causes an app crash and maybe should be considered to be fixed. I run my ionic app inside a physical device via xCode. 

<img width="1079" alt="Screenshot 2023-07-27 at 20 16 28" src="https://github.com/ionic-team/capacitor-plugins/assets/22853830/41b1ac02-291f-4ca5-bc2e-0e9d0733706b">

**Comment by Ionitron** [comment] 2023-07-28 15:56
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by NoMoreTickets** [comment] 2023-08-01 18:44
Does it happen when you're on page maps page and then you do something like do a navcontroller push onto the navigation stack and then go back?

I find I've had to recreate and reinitialize the map every time I come back to the page as a workaround.

**Comment by ngmiduc** [comment] 2023-08-03 11:54
> 

Hi, 

yes, it sometimes happened on navigation push and pop. And sometimes it also happened after the app start when I rebuilt the application in Xcode to test inside the emulator. I couldn't explain why it happened. I need to pay more attention to it next time when I am back working on this.

**Comment by Ionitron** [comment] 2023-08-19 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-08-19 00:02 UTC
Labels: platform: ios, needs reproduction
