### ISSUE TITLE
Map not displayed on iOS

### ISSUE THREAD

**Issue by MatteoOstermeier** [ionic-team/capacitor-plugins#1387] opened 2023-01-23 20:23 UTC
## Bug Report
Hello all! Unfortunately, I need your help. I've tried following some tipps in other threads, but none of them worked. Thanks a lot in advance!

### Plugin(s)
@capacitor/google-maps

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platform(s)
iOS

### Current Behavior
I have set up this plugin on my ionic capacitor application. it is displayed inside a modal. The implementation for Android and Web is working like a charm.

On iOS, i cannot get it to run properly. The map is not displayed. I tried inspecting the code on safari and the maps element just seems to be empty. The map view is in the foreground, as I could manually set a style:background-color:red and see it. Strange thing is that if i close the modal (and the map.destroy() function is called), the map is shown for a tiny fraction. 

I'm getting the following error when the map is created:
⚡️  [log] - center is 50.3142482
⚡️  [log] - {"lat":50.3142482,"lng":10.8559456}
⚡️  To Native ->  CapacitorGoogleMaps create 88537378
⚡️  TO JS undefined
2023-01-21 22:05:18.936369+0100 App[510:19026] Metal GPU Frame Capture Enabled
2023-01-21 22:05:18.954945+0100 App[510:19026] Metal API Validation Enabled
⚡️  To Native ->  CapacitorGoogleMaps addListener 88537379

On Web:
![image](https://user-images.githubusercontent.com/50016431/213887370-75fb065b-c850-44e6-a37f-98b6dbbfd7f8.png)
On Android:
![Screenshot_20230121-222050](https://user-images.githubusercontent.com/50016431/213887590-37f197ef-78be-4e71-954d-b62c91f100b7.png)
On iOS:
![7F1CB20D-32FF-4F5C-8255-0C580369D530](https://user-images.githubusercontent.com/50016431/213887561-b6ef54d5-d1cb-4d78-abf3-d00ee5586797.png)

I've tried a couple of workarounds (like removing fullscreen=true) or creating the map after a timeout. I also tried setting all backgrounds to transparent like on android, but that only makes the background turn grey. I also tried creating the map on a button click just in case it is rendered too early, but that also did not change anything.

### Expected Behavior
The map shall be displayed like on the other platforms

### Code Reproduction
I'm using a tabs layout. A page is opening up a modal for creating content. This page is opening the modal with the map. Both modal components are declared in a shared components module:
![image](https://user-images.githubusercontent.com/50016431/213887817-4921d15b-f88f-4bf9-8cc3-1269a2f08c2e.png)

Here is the code opening the Map Modal. (layout.setScanner() was a method I used for setting all backgrounds to transparent. I initially used it for a qr-code scanner, which is also rendered in the background. so sorry for the name).
![image](https://user-images.githubusercontent.com/50016431/213887838-23bb8e9c-3736-4efe-bd00-87c166539523.png)

This is the code of the map component:
![image](https://user-images.githubusercontent.com/50016431/213887878-66e14847-684c-4737-a6c3-c01c0235176b.png)
![image](https://user-images.githubusercontent.com/50016431/213887904-2ba983ab-38b5-4a02-a210-ae66843948cb.png)

HTML:
![image](https://user-images.githubusercontent.com/50016431/213888044-12dd6df0-05fd-4feb-8448-74ea750cc070.png)

### Other Technical Details
   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.0
   @angular-devkit/build-angular : 15.1.2
   @angular-devkit/schematics    : 15.1.2
   @angular/cli                  : 15.1.2
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 9.3.1
   OS     : macOS Monterey

**Comment by Ionitron** [comment] 2023-01-24 09:29
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by DwieDima** [comment] 2023-01-25 12:04
can you try to remove the `div` where the map is wrapped and apply this styling to your map?

```scss
capacitor-google-map {
  display: inline-block;
  width: 100%;
  height: 100%;
  position: absolute;
  z-index: -1;
}

```

**Comment by DwieDima** [comment] 2023-01-26 09:38
Hi @MatteoOstermeier, now i see you're using the map inside `ion-modal`.
In this case you have to make sure on your side, that all elements behind `ion-modal` are transparent.
In your case the `ion-content` element of the page where the modal is presented, need also to be transparent.

This is not a bug of the plugin. You can read more about this here:

https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios
https://capacitor-community.github.io/google-maps/#/guide/setup-webview

**Comment by bahyusanciko** [comment] 2023-01-27 09:32
> In this case you have to make sure on your side, that all elements behind `ion-modal` are transparent.

not working , its blank on native apps, browser its working 

![image](https://user-images.githubusercontent.com/41245088/215053741-4eb6aee4-4292-4c3a-979d-192357539e58.png)

**Comment by MatteoOstermeier** [comment] 2023-01-30 08:01
Hey all! Thanks a lot for your support. I'm getting to the root of the problem (I think).

Setting background to transparent also helps on iOS. I first thought this was only necessary for Android. Still, that is not the only solution required, as this shows only a grey background. 
![tmp1](https://user-images.githubusercontent.com/50016431/215418793-c0b11ab0-0fdf-4897-8c8a-b9630ab62727.png)

The map is displayed if i use a setTimeOut of 0 (!) seconds before triggering the createMap() in ionViewDidEnter(). Sounds pretty weird to me. I can personally work with this workaround, but let me know if you have an idea where the bug might be rooted. The only error i get in the js console is "failed to load resource core.css.map" in both the working and not working case.
![tmp2](https://user-images.githubusercontent.com/50016431/215418817-a2879dc7-ae23-440b-8512-a153f5984598.png)

**Comment by DwieDima** [comment] 2023-01-30 08:41
Hi @MatteoOstermeier 
to find the missing layer which is not transparent i recommend you to inspect your device on safari by changing background transparency.
For me it looks like this might be the `<body>` background.

**Comment by MatteoOstermeier** [comment] 2023-01-30 09:29
Hi DwieDima,

thanks for your reply! In the post above, I managed to create a working version on iOS. Still, it's weird that I need to place the map creation in a setTimeout function, especially as it works also with a "timeout" of 0 seconds. If I remove that part, the map is not displayed (see the two screenshots in my last post).

BR
Matteo

**Comment by jcesarmobile** [comment] 2023-02-20 18:02
closing since no sample app was provided
it sounds like a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1366

**Closed by jcesarmobile** 2023-02-20 18:02 UTC
Labels: platform: ios, needs reproduction
