### ISSUE TITLE
When called Geolocation.getCurrentPosition() resolves with empty object

### ISSUE THREAD

**Issue by naresh33** [ionic-team/capacitor-plugins#2106] opened 2024-05-15 11:08 UTC
### Plugin(s)
<img width="586" alt="Screenshot 2024-05-15 at 3 39 04 PM" src="https://github.com/ionic-team/capacitor-plugins/assets/15869305/11204367-8466-480d-b352-4ce90f818317">

@awesome-cordova-plugins/geolocation: ^6.4.0
@capacitor/geolocation: ^6.0.0
@awesome-cordova-plugins/native-geocoder: ^6.4.0
cordova-plugin-nativegeocoder: ^3.5.1

<img width="386" alt="Screenshot 2024-05-15 at 3 40 32 PM" src="https://github.com/ionic-team/capacitor-plugins/assets/15869305/4fa5c56e-9ff8-4948-9390-473d94a0b0d8">

### Platform(s)
Android

Version: 
To be specific Android 14 - UpsideDownCakePrivacySandbox

await Geolocation.getCurrentPosition() is returning empty options object.

**Comment by Gollm** [comment] 2024-06-07 11:16
I can confirm the behavior, but have not yet been able to determine the exact cause.

The fact is that since the update to version 6, the geolocation is often null on Android devices and this leads to errors in my system.

Of the packages mentioned above, I only have
@capacitor/geolocation: 6.0.0
implemented

**Comment by Ionitron** [comment] 2024-06-07 15:20
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-06-23 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-06-23 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
