### ISSUE TITLE
Filesystem (Web): Current directory does already exist.

### ISSUE THREAD

**Issue by kristojorg** [ionic-team/capacitor-plugins#1358] opened 2023-01-04 17:53 UTC
## Bug Report

When trying to write multiple files to the same (new) directory, I am seeing the following error:

```
web.ts:306 Uncaught (in promise) Error: Current directory does already exist.
    at FilesystemWeb.mkdir (web.ts:306:13)
    at async FilesystemWeb.mkdir (web.ts:312:7)
    at async FilesystemWeb.writeFile (web.ts:189:9)
    at async writeFile (axisnow.ts:199:10)
    at async downloadFile (axisnow.ts:117:21)
    at async axisnow.ts:160:17
    at async Promise.all (index 116)
    at async downloadAxisnow (axisnow.ts:173:3)
    at async download (useDownload.tsx:63:5)
```

It appears to come from this line: https://github.com/ionic-team/capacitor-plugins/blob/f4ba421b211e78bd205fa737955780a12e86e24f/filesystem/src/web.ts#L306

### Plugin(s)

- capacitor/filesystem ^4.1.4

### Capacitor Version

```
❯ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
- Web

Doesn't appear on iOS

### Current Behavior

I write multiple files in parallel to a new directory with recursive set to `true`. This appears to call `mkdir` internally which in some cases errors because the directory was just created.

### Expected Behavior

Writing with `recursive` should call `mkdir` with a try/catch or else allow mkdir to fail gracefully when the directory already exists.

**Comment by Ionitron** [comment] 2023-01-09 10:00
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-25 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-25 00:03 UTC
Labels: platform: ios, platform: web, needs reproduction, needs reply
