### ISSUE TITLE
LocalNotifications - Notification not showing up in status bar (Android)

### ISSUE THREAD

**Issue by aanders77** [ionic-team/capacitor-plugins#1196] opened 2022-09-26 09:58 UTC
## Bug Report
I do not get a local notification on my Android 12 phone. I've set up a channel, and scheduled the notification to show 10 seconds after the command is sent. I've tried both having the app in foreground and in background, but neither works. What am I missing?

PS! The documentation only describes how to setup global vars, there's no description of how to actually trigger a notification...

Here's my log from Chrome Dev Tools
![image](https://user-images.githubusercontent.com/9765529/192247722-10a49b1e-f7e3-42a0-8f2f-23603d059795.png)

### Plugin(s)
local-notifications 4.1.0

### Capacitor Version

```
Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 4.3.0    
  @capacitor/core: 4.3.0   
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0    

Installed Dependencies:    

  @capacitor/cli: 4.3.0    
  @capacitor/ios: 4.3.0    
  @capacitor/core: 4.3.0   
  @capacitor/android: 4.3.0
```

### Platform(s)
Only tested on Android so far

**Comment by Ionitron** [comment] 2022-09-26 10:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-10-12 00:06
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-12 00:06 UTC
Labels: platform: android, needs reproduction, needs reply
