### ISSUE TITLE
Notification time ago using on

### ISSUE THREAD

**Issue by mkrumboeck** [ionic-team/capacitor-plugins#620] opened 2021-09-17 22:10 UTC
`    
LocalNotifications.schedule({
      notifications: [
        {
          title: 'Title',
          body: 'Body',
          id: 99,
          schedule: {
            on: {
              hour: date.getHours(),
              month: date.getMonth()
            },
            repeats: true,
          },
          sound: null,
          attachments: null,
          actionTypeId: '',
          extra: null,
        },
      ],
    });
  }
`

When i create a notification on the 01.01.2021 and it will be executed on 01.02.2021 then you will see in the notification that the notification is 30 day old but it should be now or 1 minute because the notifcation was executed now.

![2021-09-18 00_09_22-❓-capacitor-questions - Discord](https://user-images.githubusercontent.com/25662080/133858878-0b5c5261-e634-4c10-b72f-4940c883b271.png)

**Comment by jcesarmobile** [comment] 2021-09-20 08:38
Duplicate of
https://github.com/ionic-team/capacitor-plugins/issues/433

**Closed by jcesarmobile** 2021-09-20 08:38 UTC
Labels: triage
