### ISSUE TITLE
Camera Plugin crashes app on restoreState (NullPointerException)

### ISSUE THREAD

**Issue by dnarvaez27** [ionic-team/capacitor-plugins#658] opened 2021-10-15 14:39 UTC
### Plugin(s)
* Camera

### Capacitor Version
```
Installed Dependencies:

@capacitor/ios: not installed
@capacitor/core: 3.2.4 
@capacitor/cli: 3.2.4 
@capacitor/android: 3.2.4

[success] Android looking great! 👌
```

### Platform(s)
* Android

### Current Behavior
We have seen crashes in production related to a NullPointerException on the restoreState of the CameraPlugin. The setup for the Camera is the following:
```
photo = await Camera.getPhoto({
          quality: 75,
          resultType: CameraResultType.Base64,
          promptLabelHeader: '...',
          promptLabelPicture: '...',
          promptLabelPhoto: '...',
          promptLabelCancel: '...',
          source: CameraSource.Prompt,
});
```

### Expected Behavior
Able to take a photo with the camera or pick a photo with no problem.

### Code Reproduction
N/A

### Other Technical Details
N/A

### Additional Context
Works perfect when testing on our phones, but there has been more than 200 crashes in production in the last three days with the following stack trace:
```
java.lang.NullPointerException: 
  at com.capacitorjs.plugins.camera.CameraPlugin.restoreState (CameraPlugin.java:618)
  at com.getcapacitor.Bridge.restoreInstanceState (Bridge.java:811)
  at com.getcapacitor.Bridge$Builder.create (Bridge.java:1279)
  at com.getcapacitor.BridgeActivity.load (BridgeActivity.java:72)
  at com.getcapacitor.BridgeActivity.onStart (BridgeActivity.java:110)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1435)
  at android.app.Activity.performStart (Activity.java:8222)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3818)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

This is happening for android versions 7.0 7.1, 8.0, 8.1, 9, 10, 11.

**Comment by Ionitron** [comment] 2021-10-15 16:13
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-31 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-10-31 00:01 UTC
Labels: platform: android, needs reproduction, needs reply

**Comment by hermitdemschoenenleben** [comment] 2021-11-20 18:39
I see the same error in production with > 100 occurences, but I'm also unable to reproduce the issue. @dnarvaez27 did you find any workaround?
