### ISSUE TITLE
Splash Screen - Several options not working, example guide possibly outdated

### ISSUE THREAD

**Issue by ultimate-tester** [ionic-team/capacitor-plugins#446] opened 2021-05-29 22:05 UTC
### Plugin(s)
Splash Screen - latest (shows 1.0?)

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

### Platform(s)
Android

### Current Behavior
**The following options have zero effect:**

_**launchAutoHide**_, when set to false, splash screen hides anyway after a fixed duration
_**launchShowDuration**_, splash screen always shows the same fixed amount of time (3 seconds it seems)
_**androidScaleType**_, I have several devices with scaling issues, changing the scale type does not have any effect
**_splashFullScreen_**, regardless of this setting, the splash screen remains the same
**_splashImmersive_**, regardless of this setting, the splash screen remains the same

**The listed example guide seem to be outdated (or I am doing something wrong).**
https://www.joshmorony.com/creating-a-dynamic-universal-splash-screen-for-capacitor-android/
I tried making a nine-patch, it has a weird effect on the overall app where the browser is only filling 1/4th of the screen and the splash screen remains visible as a background. It also refers to the "launch_splash.xml" file, which I don't have at all.

### Expected Behavior
All of the above functions to be working, README to be relevant and example guides to be accurate.

### Code Reproduction
This happens running a new Android project right after npx cap add android

### Other technical details

I confirm the capacitor.config.js file is correctly copied into the src/main/assets folder of the Android project. This is a snippet of the content:
```

"plugins": {
		"SplashScreen": {
			"launchAutoHide": false,
			"androidScaleType": "CENTER_CROP",
			"splashFullScreen": false,
			"splashImmersive": false
		}
	}
```

### Additional Context
I'm new to Capacitor, love it, but I really cannot get this one to work. There's no specific installation instructions, I expect it to be a matter of configuration and go. Perhaps there was a big change between v2 and v3, or I'm simply doing something wrong.

**Comment by mariusbolik** [comment] 2021-05-30 15:39
I have the same problem using `launchAutoHide` :(

I was trying to hide the splash screen in my home.page.ts, after it has been initialized. Because `launchAutoHide` did not work, I got some error like "Splash Screen wasn't hidden in 500ms" and the Platform API wasn't working anymore.

**Comment by Ionitron** [comment] 2021-06-01 08:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by erenyavuz** [comment] 2021-06-01 11:20
> I have the same problem using `launchAutoHide` :(
> 
> I was trying to hide the splash screen in my home.page.ts, after it has been initialized. Because `launchAutoHide` did not work, I got some error like "Splash Screen wasn't hidden in 500ms" and the Platform API wasn't working anymore.

How did you solve this problem?

**Comment by Ionitron** [comment] 2021-06-01 17:07
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mariusbolik** [comment] 2021-06-06 14:20
### Problem 1: Splash Screen settings are not working
I not tested all settings, but for example changing the background color of the splash screen still shows a black screen a short period of time. I also changed the background color of the webview to be sure. Please see the GIF:

<img src="https://user-images.githubusercontent.com/39862171/120926930-3e4a5e80-c6df-11eb-9624-eec2d54eefb8.gif" width="200px">

If the app is more complex, the black screen lasts longer.

### Problem 2: JavaScript exception is thrown if splash screen is hidden after 500ms
It seems to work using livereload. But if you build the app normally and run it with Xcode, the app isn't working:

<img width="652" alt="Bildschirmfoto 2021-06-06 um 15 55 14" src="https://user-images.githubusercontent.com/39862171/120927010-997c5100-c6df-11eb-8e8d-2ad55a510864.png">

### Problem 3: Setting to disable link preview also isn't working
I don't know if there's a general problem with the cpacitor config, so I think it's helpful to also mention this problem. Maybe I misunderstood the setting, but there's still a haptic feedback if you press anywhere on the app. This makes the app feels less native. For example: If you hold your finger pressed in the middle of the app, you'll notice a haptic feedback.

---

**This is my `capacitor.config.ts`:**
```ts
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'my.app.id',
  appName: 'SplashScreen Test',
  webDir: 'www',
  bundledWebRuntime: false,
  backgroundColor: "#0080ff",
  plugins: {
    SplashScreen: {
      launchAutoHide: false,
      backgroundColor: "#0080ff", // Background is still black (tested on iOS)
    }
  },
  ios: {
    allowsLinkPreview: false // Long press still gives haptic feedback
  }
};

export default config;
```

**Here is my sample project:**
To reproduce you can simply run the app on your iOS Device:
https://github.com/mariusbolik/capacitor-splashscreen-settings

You'll find problem 1 & 3 in `capacitor.config.ts` and problem 2 in `home.page.ts`.

It seems like these problems only appear on iOS.

Thank you for your awesome work @jcesarmobile!

**Comment by jcesarmobile** [comment] 2021-06-07 16:04
Problem 1: iOS apps first show the launch storyboard, then the splash plugin kicks in, so if you change the background color for the plugin you should also change it in the launch storyboard background or you'll notice the transition between them.

Problem 2: that's unrelated to this topic, the problem is we are firing the cordova resume event while the webView has not fully loaded the content and prints that error.

Problem 3: `allowsLinkPreview` disables the preview of the link, but not the haptic feedback, I asked Apple engineers and looks like it can't be disabled. There are ways of disabling it with some workarounds such as adding a long press gesture recognizer to the webview, but it's a hacky solution, so we won't be adding that into capacitor, there are plugins that can do it.

**Comment by jcesarmobile** [comment] 2021-06-21 17:13
Closing as no sample app was provided and I can't reproduce on [our test app ](https://github.com/ionic-team/capacitor-testapp)

It uses `launchAutoHide: false` and if I remove the code for hiding the splash programmatically the splash doesn't disappear, if I change the value to true then it disappears, if I add `splashFullScreen` set to true then the status bar disappears, and if I add `splashImmersive` set to true then the navigation bar disappears (on devices that have software navigation bar)

**Closed by jcesarmobile** 2021-06-21 17:13 UTC
Labels: needs reproduction, platform: android

**Comment by richardmward** [comment] 2021-07-15 08:09
For anyone else that comes across this, I have found that you need to set a non-zero value in `launchShowDuration`, even if using `launchAutoHide: true` because in `com.capacitorjs.plugins.splashscreen.SplashScreen.showOnLaunch` there is the following piece of logic, which means it doesn't actually launch the splash image view.

```java
        if (config.getLaunchShowDuration() == 0) {
            return;
        }
```

**Comment by aless673** [comment] 2021-12-17 15:42
> For anyone else that comes across this, I have found that you need to set a non-zero value in `launchShowDuration` (e.g. i use `1`), even if using `launchAutoHide: false` because in `com.capacitorjs.plugins.splashscreen.SplashScreen.showOnLaunch` there is the following piece of logic, which means it doesn't actually launch the splash image view.
> 
> ```java
>         if (config.getLaunchShowDuration() == 0) {
>             return;
>         }
> ```

thanks, took hours before finding your answer

the only remaining problem seems to be the androidScaleType that works onyl after few seconds. The splash is stretched, nothing to do ...
