### ISSUE TITLE
@capacitor/app-launcher canOpenUrl crashed app (android)

### ISSUE THREAD

**Issue by xaru123** [ionic-team/capacitor-plugins#2170] opened 2024-08-13 08:56 UTC
### Plugin(s)
@capacitor/app-launcher

### Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/ios: 6.1.1

### Platform(s)
only on android

### Current Behavior
Try to open 'tel:+79001234567' or another phone crashed app. App is closed and nothing work.
"tel://" is not working too.
canOpenUrl return false. Everytime.
If delete a check canOpenUrl and call only openUrl method , everything is fine
If delete only "if (value)" app crashed.
The problem is in canOpenUrl method.

### Expected Behavior
Open phone number page, where you can call a number.

### Code Reproduction
```
const { value } = await AppLauncher.canOpenUrl({ url: `${telephone}`  });

if (value) {
  await AppLauncher.openUrl({ url: `${telephone}` });
}
```

**Comment by Ionitron** [comment] 2024-08-19 16:22
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-09-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-09-04 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
