### ISSUE TITLE
google maps marker icon when clustering

### ISSUE THREAD

**Issue by xdelvalle** [ionic-team/capacitor-plugins#1308] opened 2022-11-29 10:09 UTC
### Plugin(s)

@capacitor/google-maps

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0

```

### Platform(s)

Android

### Current Behavior

If enableClustering() is not called, the map shows the markers with my customized icon (iconUrl) without problems, but when I call "await this.map.enableClustering();", when zoom in, the markers aren't my customer markers, are the default markers. 

### Expected Behavior

When zoom in and the individual markers are displayed, this markers have to be my customized markers.

### Code Reproduction

await this.addCustomMarkers();
await this.map.enableClustering();

```
  async addCustomMarkers() {
    for (const element of this.elements) {
      const marker: Marker = {
        coordinate: {
          lat: element.latitude,
          lng: element.longitude
        },
        title: element.name,
        snippet: element.name,
        iconUrl: 'assets/icon/markers/marker.png',
      };
      this.markers.push(marker);
    }
    await this.map.addMarkers(this.markers);
  }
```

### Other Technical Details

"@capacitor/android": "^4.5.0",
"@capacitor/app": "^4.1.1",
"@capacitor/core": "^4.5.0",
"@capacitor/geolocation": "^4.1.0",
**"@capacitor/google-maps": "4.2.1",**
"@capacitor/haptics": "4.1.0",
"@capacitor/ios": "^4.5.0",
"@capacitor/keyboard": "^4.1.0",
"@capacitor/status-bar": "^4.1.0",

**Comment by Ionitron** [comment] 2022-11-29 10:15
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-15 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-15 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
