### ISSUE TITLE
Camera getPhoto in webUseInput after cancel still trigger

### ISSUE THREAD

**Issue by HackJack-101** [ionic-team/capacitor-plugins#996] opened 2022-05-20 16:04 UTC
### Plugin(s)

@capacitor/camera v1.3.1

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/cli: 3.5.0
  @capacitor/ios: 3.5.0

```

### Platform(s)

PWA

### Current Behavior

Two components trigger Camera.getPhoto() in webUseInput mode are in the same view.

If we cancel the first input, and we chose a photo for the second one, the first resolve function will trigger.

### Expected Behavior

The first resolve function will not be triggered.

### Additional Context

https://github.com/ionic-team/capacitor-plugins/blob/656f9169ccd8d7fa880143b13ca5f62bb546edb0/camera/src/web.ts#L91

```
if (input) {
    cleanup();
}
```

And remove the condition `if(!input)`

**Comment by Ionitron** [comment] 2022-05-20 16:12
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-05 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-05 00:02 UTC
Labels: needs reproduction, needs reply
