### ISSUE TITLE
Google Maps: Map disappearing after losing focus

### ISSUE THREAD

**Issue by bojernico** [ionic-team/capacitor-plugins#1568] opened 2023-05-02 14:54 UTC
### Plugin(s)

Google Maps

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.0.0-rc.0
  @capacitor/core: 5.0.0-rc.0
  @capacitor/ios: 5.0.0-rc.0

[success] iOS looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

The first loading of the map works without any problems.
A click on the slider or the button (and "go back"-Button to be on the same page) makes the map disappear ( see screenshots below).
( Same behavior with latest versions )

### Expected Behavior

Map should still be shown

### Code Reproduction

```
git clone https://github.com/bojernico/capacitor-googlemaps.git
npm install
```

Add API-Key to 'src/app/pages/map/map.page.ts'

```
ionic cap add ios
ionic cap sync ios
ionic cap run ios
```

( pick a random emulator )

### Other Technical Details

iOS-Version: 16.2
XCode-Version: 14.2

### Additional Context

Initial load:
<img src="https://user-images.githubusercontent.com/43436805/235691826-c6af5032-f4cd-4c0a-95a7-1f261b4d1264.png" width="200" height="400">

After clicking on slider / change site and go back:
<img src="https://user-images.githubusercontent.com/43436805/235693276-a60e40fd-dec1-4e4b-ae3b-a457a2ad9cff.png" width="200" height="400">

**Comment by RobSchilderr** [comment] 2023-05-15 11:40
I will run most likely into this issue this week, because i am also actively working on something! Upvoting for visability.

**Comment by planbsim** [comment] 2023-05-17 13:23
Further investigations shows, that the size could be a problem. 

```
capacitor-google-map {
  display: inline-block;
  width: 100%;
  height: 100%;
}
```

We set the capacitor-google-map width and height to 100% and no specific pixel size. When we set it to a pixel size then the slider does not affect the map but the routing to another page and back does. After Routing the map disappears.

**Comment by jcesarmobile** [comment] 2023-05-24 17:46
Yeah, when you navigate to a different page, the WKWebView is probably destroying the map, so when you go back it's no longer there. For their own views it restores them, but since this is a native view that it's being added to the WKWebView, the WKWebView doesn't restore it.

The issue is a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1402.

**Closed by jcesarmobile** 2023-05-24 17:46 UTC
Labels: platform: ios
