### ISSUE TITLE
Issue with receiving push notifications on iOS using Capacitor and Firebase

### ISSUE THREAD

**Issue by ghonche** [ionic-team/capacitor-plugins#1662] opened 2023-06-20 08:35 UTC
## Bug Report

I am facing a problem with receiving push notifications on iOS using Capacitor and Firebase Cloud Messaging. Here are the details:

- I'm using @capacitor/push-notifications, and followed the setup steps provided in the [plugin documentation for iOS](https://capacitorjs.com/docs/apis/push-notifications#ios).

- Android devices receive notifications successfully, but iOS devices do not.

- PushNotifications.register() runs successfully and the FCM token is obtained from iOS device.

- Notification permission is asked at first startup. I also checked the app settings. Notifications are enabled.

- I have downloaded GoogleService-Info.plist from FCM and pasted it into the root of my IOS project.

- I have uploaded the APNs Certificates for both Development and Production modes in FCM dashboard.

- Im using "@capacitor/core": "^5.0.0", "@capacitor/push-notifications": "^5.0.4" and "@capacitor/ios": "^5.0.5".

- I have tried sending a test notification directly to that device from FCM dashboard (using device FCM token), but no notification is received.

- I have tried this scenario on a real device and an emulator. still no luck.

Despite these steps, notifications are not received on iOS devices/emulators. I would appreciate any guidance. Thank you in advance.

### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.0
  @capacitor/ios: 5.0.5
  @capacitor/core: 5.0.0


```

### Platform(s)
IOS

**Comment by Ionitron** [comment] 2023-06-20 08:38
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by khalsa-school-app** [comment] 2023-07-03 17:02
did you get it working?

**Comment by ghonche** [comment] 2023-07-04 12:28
> did you get it working?

no luck with @capacitor/push-notifications :(
I used [@capacitor-firebase/messaging](https://github.com/capawesome-team/capacitor-firebase) plugin instead  and that worked for me. [ This guide](https://capawesome.io/blog/the-push-notifications-guide-for-capacitor) can help.

**Comment by khalsa-school-app** [comment] 2023-07-04 23:58
@ghonche 

I keep getting the below error. Any help would be appreciated. I have added the aps-enviroment entitlement in both the app and in the provisioning profile.

```
Jul  4 23:54:50 App(GoogleUtilities)[5564] <Notice>: 10.8.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '860157479095'.Be sure to re-retrieve the FCM token once the APNS device token is set.
Jul  4 23:54:50 callservicesd(TelephonyUtilities)[116] <Notice>: Pickable Routes Changed: <private>
Jul  4 23:54:50 App(GoogleUtilities)[5564] <Notice>: 10.8.0 - [FirebaseMessaging][I-FCM002022] Declining request for FCM Token since no APNS Token specified
```

'''
Jul  4 23:54:39 App(GoogleUtilities)[5564] <Notice>: 10.8.0 - [FirebaseMessaging][I-FCM012002] Error in application:didFailToRegisterForRemoteNotificationsWithError: no valid \M-b\M^@\M^\aps-environment\M-b\M^@\M^] entitlement string found for application

'''

**Comment by wsamoht** [comment] 2023-07-12 19:20
Are you sure you are getting the FCM token and not the Apple APN token?

When using Firebase for push notifications, you need to change `AppDelegate.swift` to swap the APN token with the FCM token as shown [here](https://capacitorjs.com/docs/guides/push-notifications-firebase#add-initialization-code).

```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  Messaging.messaging().apnsToken = deviceToken
  Messaging.messaging().token(completion: { (token, error) in
    if let error = error {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    } else if let token = token {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: token)
    }
  })
}
```

**Comment by jcesarmobile** [comment] 2023-07-14 13:17
Closing since no sample app was provided.

`@capacitor/push-notifications` doesn't support FCM out of the box, you have to do some additional steps as explained on the link wsamoht shared.
The code mentioned in wsamoht message was not on the steps provided by the reporter, so they are probably missing that step.
Also this step is incorrect
> I have downloaded GoogleService-Info.plist from FCM and pasted it into the root of my IOS project.
You don't have to copy the file to the root of the project, you have to drag the file to the Xcode project as Xcode projects track the app files, just copying files to a folder is not enough. That's also explained in the link.

If somebody is still having configuring push notifications, they can ask on the [forums](https://forum.ionicframework.com/c/capacitor/26) or in [github discussions](https://github.com/ionic-team/capacitor/discussions)

**Closed by jcesarmobile** 2023-07-14 13:17 UTC
Labels: platform: ios, needs reproduction
