### ISSUE TITLE
bug: preferences must be without prefix

### ISSUE THREAD

**Issue by bazuka5801** [ionic-team/capacitor-plugins#1310] opened 2022-11-29 12:29 UTC
prefixes is bad when develop iOS app extension.
https://github.com/ionic-team/capacitor-plugins/blob/df7e2f5a35879e618f0c3d50fe1a4b3ef4380b0e/preferences/ios/Plugin/Preferences.swift#L43-L45
Example:
I have `foo: 1` preference in my web app through `Preferences.set({ key: 'foo', value: '1' })`

But in my extension, if I use `UserDefaults(suiteName: "group.app.mygroup").getString('foo')` I get nothing, because the preference plugin can't:
1. Specify suiteName for iOS UserDefaults (right now only `UserDefaults.standart` is used)
2. Write value without key prefix

I need to write a simple method until this plugin is improved
```swift
let prefs = UserDefaults(suiteName: "group.com.app")
    
@objc func setPreference(_ call: CAPPluginCall) {
    
    guard let key = call.getString("key") else {
        call.reject("'key' not provided")
        return
    }
    
    guard let val = call.getString("value") else {
        call.reject("'value' not provided")
        return
    }
    
    prefs!.set(val, forKey: key)
    
    call.resolve(["success": true])
}
```

**Comment by Ionitron** [comment] 2022-11-29 12:35
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-12-15 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-12-15 00:02 UTC
Labels: needs reproduction, needs reply

**Comment by bazuka5801** [comment] 2022-12-23 09:41
@jcesarmobile please reopen

**Comment by bazuka5801** [comment] 2022-12-25 17:51
@jcesarmobile why my comment marked as disruptive?
