### ISSUE TITLE
App-launcher canOpenUrl does not work with url scheme on Android

### ISSUE THREAD

**Issue by maxfloden** [ionic-team/capacitor-plugins#614] opened 2021-09-16 14:28 UTC
### Plugin(s)
@capacitor/app-launcher@1.0.4 

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3
  @capacitor/core: 3.2.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
AppLauncher.canOpenUrl fails on Android when providing url scheme as url parameter even though the url can be opened with AppLauncher.openUrl. Using package name works.

E/Capacitor/AppLauncherPlugin: Package name 'bankid:///?autostarttoken=xxxx-xxxx-xxxx-xxxx-xxxx&redirect=null' not found!

### Expected Behavior
If a url can be opened with openUrl, then canOpenUrl should return true.
Or if this is by design, at least this discrepancy should be clearly documented.

### Additional Context
I am using app-launcher plugin to open another app using a url like this:
'bankid:///?autostarttoken=xxxx-xxxx-xxxx-xxxx-xxxx&redirect=null' 
Opening it using AppLauncher.openUrl works fine on both Android and iOS.

However when I try to check AppLauncher.canOpenUrl it works as expected on iOS (ie returns value: true) but on Android it returns value: false (even though it can in fact be opened using AppLauncher.openUrl)

My guess is that the plugin is checking against AndroidManifest.xml <queries> and it only accept package names, not url schemes (at least what I have found)
```
   <queries>
        <package android:name="com.bankid.bus" />
    </queries>
```

Workaround is to hardcode to instead check for package name ('com.bankid.bus') instead of url scheme on Android platform.

**Comment by Ionitron** [comment] 2021-09-16 15:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-02 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-10-02 00:01 UTC
Labels: platform: android, needs reproduction, needs reply

**Comment by jackdaniel9** [comment] 2022-04-20 21:12
Same problem. App open only with package name. With params, app not open.

**Comment by jesusabaditsoft** [comment] 2022-06-20 11:49
Same problem. Anyone can help me?
