### ISSUE TITLE
@capacitor/screen-orientation not changing directly landscape-primary to landscape-secondary

### ISSUE THREAD

**Issue by andreidmour** [ionic-team/capacitor-plugins#1813] opened 2023-09-26 08:42 UTC
### Plugin(s)
@capacitor/screen-orientation 5.0.6

### Capacitor Version
@capacitor/core 5.4.0

### Platform(s)
React 18 / Next 13 (client build)

### Current Behavior

Flipping the device directly from landscape-primary to landscape-secondary does not change the value unless it first goes through portrait-primary.

### Expected Behavior
It should work like window.screen.orientation

### Code Reproduction

```
"use client";

import { useEffect, useState } from "react";
import { ScreenOrientation } from "@capacitor/screen-orientation";

export default function Page() {
  const [screenOrientation, setScreenOrientation] =
    useState<OrientationType | null>(null);

  useEffect(() => {
    const handleOrientationChange = async () => {
      const { type } = await ScreenOrientation.orientation();
      setScreenOrientation(type);
    };

    const orientationChangeListener = ScreenOrientation.addListener(
      "screenOrientationChange",
      handleOrientationChange
    );

    handleOrientationChange();

    return () => {
      orientationChangeListener.remove;
    };
  }, []);

  return (
    <main className="relative flex min-h-screen flex-col items-center justify-between w-full">
      <div>
        <h1>Screen Orientation</h1>
        <p>Current Orientation: {screenOrientation}</p>
      </div>
    </main>
  );
}
```

###Working code with window.screen.orientation

```
"use client";

import { useEffect, useState } from 'react';

function ScreenOrientationComponent() {
  const [orientation, setOrientation] = useState("");

  useEffect(() => {
    const handleOrientationChange = () => {
      const { type } = window.screen.orientation;
      setOrientation(type);
    };

    window.addEventListener('orientationchange', handleOrientationChange);

    handleOrientationChange();

    return () => {
      window.removeEventListener('orientationchange', handleOrientationChange);
    };
  }, []);

  return (
    <div>
      <h1>Screen Orientation</h1>
      <p>Current Orientation: {orientation}</p>
    </div>
  );
}

export default ScreenOrientationComponent;
```

**Comment by andreidmour** [comment] 2023-09-26 08:59
It seems to be caused by the ScreenOrientation.addListener

**Comment by Ionitron** [comment] 2023-09-26 17:37
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-10-12 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-10-12 00:02 UTC
Labels: needs reproduction, needs reply
