### ISSUE TITLE
Camera.pickImages gallery is not appearing over app on Motorola devices

### ISSUE THREAD

**Issue by matheus-foscarinid** [ionic-team/capacitor-plugins#2184] opened 2024-08-30 13:25 UTC
### Plugin(s)

```
@capacitor/camera@6.0.2
```

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/core: 6.1.2
```

### Platform(s)
It appears to only happens on Android Motorola Devices, and on Android 13. 
I've tested mainly in Android 13, 11, 10 and 9. From Android 11 to 9 works like a charm.

### Current Behavior
When calling `Camera.pickImages` the gallery overlay is not appearing, but the backdrop is. Looks like the gallery is there but not visible, because you can click and it works, but you're not seeing what's happening. Event screenshots work, the gallery overlay appears.

### Expected Behavior
The gallery overlay appear as in any other device

### Code Reproduction

I'll add ASAP, but for now I'll just show the method:
```js
const { photos } = await Camera.pickImages({
  quality: 90,
  width: 2048,
  height: 2048,
  correctOrientation: false
});
```

**Comment by Ionitron** [comment] 2024-09-16 10:22
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-10-02 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-10-02 00:03 UTC
Labels: platform: android, needs reproduction
