### ISSUE TITLE
PushNotifications and LocalNotifications always return granted on Android 13

### ISSUE THREAD

**Issue by joshuavillano** [ionic-team/capacitor-plugins#1274] opened 2022-11-11 01:54 UTC
### Plugin(s)
"@capacitor/local-notifications": "^4.1.1",
"@capacitor/push-notifications": "^4.1.0",

### Platform(s)
Android 13 Only

### Current Behavior
requestPermissions always return "granted" even if the user clicked Don't Allow
checkPermissions always return "granted" even if the notification setting is disabled

### Expected Behavior
requestPermissions will return "denied" if the user clicked Don't Allow
checkPermissions always return "denied" if the notification setting is disabled

**Comment by ndabAP** [comment] 2022-11-26 11:36
I have the opposite problem: I always receive `denied` in both cases.

**Comment by nip3o** [comment] 2023-01-09 12:47
I believe this is a duplicate of #1116 / #1135 and should be fixed when #1190 is merged

**Comment by GabrieleGruppoInformatico** [comment] 2023-03-10 16:26
@nip3o Any info on the status of #1190? It seems to be unreviewed since october 2022...
I don't know if there is a workaround for Android 13, but at the moment we can't request permissions. On Android 13 notification are "blocked" by default but  from all method they result as "granted" (not working obv), while on Android 11 they are granted by default.

**Comment by nip3o** [comment] 2023-03-16 08:24
#1463 was merged the other day, which I believe should fix this. I think it will be released at the same time as Capacitor 5.

**Comment by jcesarmobile** [comment] 2023-05-23 13:41
This is fixed in Capacitor 5 and version 5 of capacitor push/local notification plugins

**Closed by jcesarmobile** 2023-05-23 13:41 UTC
Labels: platform: android

**Comment by ximex** [comment] 2023-05-23 13:42
could confirm this is fixed
