### ISSUE TITLE
Android Pixel 7, API 33 keyboardHeight incorrect

### ISSUE THREAD

**Issue by albertreed** [ionic-team/capacitor-plugins#1858] opened 2023-10-24 22:26 UTC
### Plugin(s)

keyboard

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/ios: 5.3.0
  @capacitor/android: 5.3.0

### Platform(s)

Android

### Current Behavior

`keyboardHeight` returned by `keyboardWillShow` event does not reflect the full height of the keyboard widget.

### Expected Behavior

`keyboardHeight` reflects the full height of the widget.

### Code Reproduction

`Keyboard.addListener("keyboardWillShow", (info) => {console.log(info);})`

### Other Technical Details

Running on the simulator, API 33, Pixel 7.

From the inspector, if I put a `fixed` box with `bottom: keyboardHeight` you can see it renders the box.
<img width="447" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/4851499/030f8c90-bbbc-44af-bd44-62369654ddc6">

When viewing the simulator the little portion of the keyboard that provides additional functionality is obscuring the input box:
<img width="1102" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/4851499/728d36ee-c2a0-4a32-96d4-94998011a0ec">

on iOS the box renders in the correct spot.
<img width="844" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/4851499/6a7ce3f4-c3e8-4126-838b-d1b151a5a60c">

**Comment by Ionitron** [comment] 2023-10-25 08:40
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-11-10 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-10 00:03 UTC
Labels: platform: android, needs reproduction
