### ISSUE TITLE
WriteFile not working for Android SDK 33

### ISSUE THREAD

**Issue by EllendeBoer** [ionic-team/capacitor-plugins#1659] opened 2023-06-16 11:04 UTC
### Plugin(s)

@capacitor/filesystem 5.0.4

### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/core: 5.0.5

```

### Platform(s)

Android

### Current Behavior

Write file to Android is not working with Capacitor 5, with @capacitor/filesystem and Android SDK 33.

SDK 33 does not need the WRITE_EXTERNAL_STORAGE permission anymore. This permission will always return 'denied'. The filesystem plugin still uses this permission.

Response **without** using permission **WRITE_EXTERNAL_STORAGE**: 
'Missing the following permissions in AndroidManife…TORAGE\nandroid.permission.WRITE_EXTERNAL_STORAGE'

Response **with** use of permission **WRITE_EXTERNAL_STORAGE**: 
'Unable to do file operation, user denied permission request'
permissionCheck: ('publicStorage":"denied"}

With SDK 32 it works fine.

After locally removing all permission code within the filesystem plugin, writing file succeeded.

### Expected Behavior

It should write the file to the Android device after clicking on button.

### Code Reproduction

https://github.com/PimBurgt/capacitor-save-file

`      await Filesystem.writeFile({
        path: 'Download/test.txt',
        data: 'abc',
        directory: Directory.ExternalStorage,
        encoding: Encoding.UTF8,
        recursive: false
      })`

### Other Technical Details

WebStorm 2022.1.1
Android Studio Flamingo | 2022.2.1 Patch 2
Capacitor 5
@capacitor/filesystem 5.0.4
@capacitor/android 5.0.5

target Samsung_Galaxy_A40_API_33 (does not work)
target Samsung_Galaxy_A40_API_32 (works fine)

### Additional Context

https://www.linkedin.com/pulse/android-storage-permissionless-13-ashutosh-sharma

**Comment by jcesarmobile** [comment] 2023-06-16 12:42
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1512

**Closed by jcesarmobile** 2023-06-16 12:42 UTC
Labels: platform: android
