### ISSUE TITLE
google-maps Web Component Fails to Compile in Next.js

### ISSUE THREAD

**Issue by kavdev** [ionic-team/capacitor-plugins#1244] opened 2022-10-23 20:42 UTC
### Plugin(s)

@capacitor/google-maps v4.3.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0
```

### Platform(s)

**web**
"next": "12.2.5"
"react": "18.2.0"
"typescript": "4.8.2"

### Current Behavior

ReferenceError when attempting to load GoogleMap plugin:
```
error - ReferenceError: HTMLElement is not defined
    at Object.<anonymous> (/.../node_modules/@capacitor/google-maps/dist/plugin.cjs.js:63:32)
```

### Expected Behavior

Ability to import GoogleMap without a ReferenceError 

### Code Reproduction

`import { GoogleMap } from '@capacitor/google-maps';`

### Other Technical Details

This seems to be due to the web component added in the library. Next.js doesn't play nicely with web components at the moment. If I remove the `MapCustomElement` class and the `customElements.define` call below it, this error goes away.

I realize my only option might be to fork this library, remove that code (or maybe move it into my app), and add the styles for ios manually, but I'd love to know if there's another option out there. I tried dynamically loading the library, but I ran into a bunch of type issues.

**Comment by Ionitron** [comment] 2022-10-24 08:04
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by kavdev** [comment] 2022-10-24 16:58
This is more of a discussion on possibilities, or an opportunity for documentation on a workaround for next.js users.

**Comment by fryiee** [comment] 2022-11-01 05:17
This is also an issue for Nuxt users.

**Comment by jcesarmobile** [comment] 2023-02-27 12:33
closing since no sample app was provided

**Closed by jcesarmobile** 2023-02-27 12:33 UTC
Labels: needs reproduction
