### ISSUE TITLE
White screen after install the library an call it in a Ionic-React with capacitor in IOS

### ISSUE THREAD

**Issue by aayestashn** [ionic-team/capacitor-plugins#1061] opened 2022-06-24 20:30 UTC
# Bug report

## What steps will reproduce the problem?

- Install the dependencies in a React Ionic with Capacitor project.
```bash
$ npm install cordova-plugin-lottie-splashscreen 
$ npm install @awesome-cordova-plugins/lottie-splash-screen 
$ ionic cap sync
```
- Open in Xcode and run the build.

In the index file of the React application, I put the following code.

```jsx
const splash = async () => {
  await LottieSplashScreen.show(
    "https://assets10.lottiefiles.com/packages/lf20_pjaextie.json",
    true,
    1024,
    768
  );
};

splash();
```
## Expected output

The splash screen with the animation from the Lottie file.

## What do you see instead?

The splash screen opened without the animation from the Lottie file. As you can see here: [image](https://drive.google.com/file/d/1IDW40OzYcOUeqLBuY90EEocNZqW4fTum/view?usp=sharing)

## Log file of the issue/error

```
To Native Cordova ->  LottieSplashScreen show LottieSplashScreen155446136 ["options": [https://assets10.lottiefiles.com/packages/lf20_pjaextie.json, 1, 1024, 768]]
⚡️  To Native ->  App addListener 47150257
⚡️  To Native ->  App addListener 47150258
To Native Cordova ->  LottieSplashScreen initialAnimationEnded LottieSplashScreen155446137 ["options": []]
⚡️  To Native ->  App addListener 47150259
⚡️  WebView loaded
```

## Version information

```bash
npx cordova info 
npx: installed 495 in 39.984s
? May Cordova anonymously report usage statistics to improve the tool over time? (Y/n) 
You have been opted out of telemetry. To change this, run: cordova telemetry on.
Current working directory is not a Cordova-based project.
```

```bash
npx ionic info   

Ionic:

   Ionic CLI       : 6.17.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.2

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v14.17.3 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Monterey
```
package.json
```json
  "@awesome-cordova-plugins/core": "^5.43.0",
  "@awesome-cordova-plugins/lottie-splash-screen": "^5.43.0",
  "cordova-plugin-lottie-splashscreen": "^0.9.6",
```

## Please provide any additional information below.
This plugin is fully compatible with Capacitor in an ionic-react application? 
I am following this information [ionic docs](https://ionicframework.com/docs/native/lottie-splash-screen)

**Comment by Ionitron** [comment] 2022-06-27 08:19
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-07-13 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-13 00:03 UTC
Labels: needs reproduction, needs reply
