### ISSUE TITLE
LocalNotification set autoCancel false is not working

### ISSUE THREAD

**Issue by ysneo** [ionic-team/capacitor-plugins#1384] opened 2023-01-22 09:35 UTC
### Plugin(s)

 "@capacitor/local-notifications": "^4.1.4",

### Capacitor Version

```
v4
```

### Current Behavior

LocalNotification set autoCancel false is not working
      autoCancel: false,

### Expected Behavior

**autoCancel set to false**

### Code Reproduction

  autoCancel: false,  this property is not woring; when click notification, still disappear

### Other Technical Details

no

### Additional Context

no

**Comment by Ionitron** [comment] 2023-01-23 09:20
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-08 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-08 00:03 UTC
Labels: needs reproduction, needs reply
