### ISSUE TITLE
Android layout name not loading layout file

### ISSUE THREAD

**Issue by sgarchavada** [ionic-team/capacitor-plugins#604] opened 2021-09-14 09:20 UTC
### Plugin(s)

`@capacitor/splash-screen": "^1.1.2`

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/android: 3.2.2
  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/ios: 3.2.2

```

### Platform(s)

`Android`

### Current Behavior

```
capacitor.config.ts file

SplashScreen: {
      launchShowDuration: 5000,
      launchAutoHide: true,
      splashFullScreen: true,
      splashImmersive: true,
      useDialog: true,
      layoutName: "launch_screen",
    },

This is not loading launch_screen.xml layout, instead I am getting blank white screen. 
also launchShowDuration is also not applying, blank screen disappear after 1 sec.
```

### Expected Behavior

```
This should load layout file named launch_screen
Launch screen should stay on screen for 5 second.

```
Let me know if I am missing something

**Comment by Ionitron** [comment] 2021-09-14 14:32
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-09-30 00:20
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-09-30 00:20 UTC
Labels: triage, platform: android, plugin: splash screen, needs reproduction, needs reply
