### ISSUE TITLE
[@capacitor/google-maps] Add method fitBounds

### ISSUE THREAD

**Issue by heykanna** [ionic-team/capacitor-plugins#1625] opened 2023-05-30 12:58 UTC
### Plugin
@capacitor/google-maps

### Description
Add method fitBounds which would move and zoom map so it would display all supplied points.

### Platform(s)
Android
iOS

### Preferred Solution
`map.fitBounds({
  points: [],
  animation: true,
  animationDuration: 1000
})`

**Comment by jcesarmobile** [comment] 2023-05-30 13:34
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1346

**Closed by jcesarmobile** 2023-05-30 13:34 UTC
Labels: platform: android, platform: ios
