### ISSUE TITLE
Focus between inputs resize screen

### ISSUE THREAD

**Issue by vladislavgolubev** [ionic-team/capacitor-plugins#1513] opened 2023-03-30 13:09 UTC
### Plugin(s)

    "@awesome-cordova-plugins/media-capture": "^6.2.0",
    "@awesome-cordova-plugins/nfc": "^6.2.0",
    "@awesome-cordova-plugins/power-optimization": "^6.2.0",
    "@awesome-cordova-plugins/speech-recognition": "^6.2.0",
    "@capacitor-community/barcode-scanner": "^3.0.1",
    "@capacitor-community/file-opener": "^1.0.3",
    "@capacitor/android": "^4.5.0",
    "@capacitor/app": "^4.1.1",
    "@capacitor/assets": "^2.0.4",
    "@capacitor/camera": "latest",
    "@capacitor/core": "latest",
    "@capacitor/filesystem": "^4.1.4",
    "@capacitor/ios": "^4.6.3",
    "@capacitor/keyboard": "^4.1.1",
    "@capacitor/local-notifications": "^4.1.3",
    "@capacitor/preferences": "^4.0.2",
    "@capacitor/push-notifications": "^4.1.2",
    "@capacitor/splash-screen": "latest",
    "@capacitor/status-bar": "^4.1.0",
    "@capgo/capacitor-updater": "^4.13.5",
    "@hugotomazi/capacitor-navigation-bar": "^2.0.0",
    "capacitor-plugin-safe-area": "^1.0.1",
    "capacitor-voice-recorder": "^4.0.0",
    "cordova-plugin-file": "^7.0.0",
    "cordova-plugin-media-capture": "github:aaronksaunders/cordova-plugin-media-capture",
    "cordova-plugin-power-optimization": "^0.0.4",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "jetifier": "^2.0.0",
    "phonegap-nfc": "github:vladislavgolubev/phonegap-nfc",
    "pinpon-capacitor-video-recorder": "github:pinpon-dev/capacitor-video-recorder"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0
  @capacitor/android: 4.5.0
```

### Platform(s)

ios

### Current Behavior

Keyboard.setScroll({isDisabled: true});
KeyboardResize is default - native

when the focus is switched between two inputs, the screen size changes.
1) click to first input - screen size changed successfull (screen height decreases)
2) click to second input - screen size back (screen height  increase, as if the keyboard was closed, but keybord still show for second fiocused input)
3) click to first input - screen size changed successfull (screen height decreases)
4) click to second input - screen size back (screen height  increase)
5) and so on ...

### Expected Behavior

chnage focus betwen inputs not change screen size.

**Comment by jcesarmobile** [comment] 2023-04-10 16:38
The issue is a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1413

**Closed by jcesarmobile** 2023-04-10 16:38 UTC
Labels: platform: ios
