### ISSUE TITLE
[PushNotification] java.lang.NullPointerException for "removeDeliveredNotifications"

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor-plugins#855] opened 2022-03-09 14:45 UTC
### Plugin(s)

* PushNotification

### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli 2.4.6
  @capacitor/core 2.4.6
  @capacitor/android 2.4.6
  @capacitor/ios 2.4.6
```

### Platform(s)

* Android

### Current Behavior

_I know I'm currently using a 2.x Capacitor version but from what I see it does not change the issue (I looked at past commits until the version I have)._

I was trying to remove a notification that does not exist any longer:
```
                  PushNotifications.removeDeliveredNotifications({
                    notifications: [notification],
                  });
```

And it appears it crashes my application:
```
java.lang.RuntimeException: 
  at com.getcapacitor.Bridge$1.run (Bridge.java:551)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.os.HandlerThread.run (HandlerThread.java:67)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.getcapacitor.PluginHandle.invoke (PluginHandle.java:99)
  at com.getcapacitor.Bridge$1.run (Bridge.java:542)
Caused by: java.lang.NullPointerException: 
  at com.getcapacitor.plugin.PushNotifications.removeDeliveredNotifications (PushNotifications.java:159)
```

According to the logs it points to:https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java#L145-L168

... and indeed the exception of a null pointer is not caught. I don't have details which line uses the wrong pointer but I wanted to provide the feedback on this. Crashing the app is hard, even if the "developer" made an error of trying to remove after the notification is gone 😄 

### Expected Behavior

To not crash.

### Code Reproduction

-

### Other Technical Details

It works perfectly on iOS even if the notification was gone.

### Additional Context

-

Thank you,

**Comment by Ionitron** [comment] 2022-03-09 15:20
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sneko** [comment] 2022-03-09 15:20
Ok I tried to reproduce directly with Android Studio to give you more hints:

```
I/Capacitor/Console: File: http://localhost/js/chunk-vendors.1c1668f3.js - Line 1621 - Msg: info: Push Notification action performed
I/Capacitor/Console: File: http://localhost/js/chunk-vendors.1c1668f3.js - Line 1621 - Msg: debug: Push Notification action content: {"actionId":"tap","notification":{"id":"0:1646839078401306%0257ad8b0257ad8b","data":{"google.delivered_priority":"normal","google.sent_time":"1646839078397","google.ttl":"2419200","google.original_priority":"normal","from":"645040165901","collapse_key":"aaaaaaaaaaaaa","redirectUrl":"bbbbbbbbbbb"}}}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 56527741, pluginId: PushNotifications, methodName: removeDeliveredNotifications
V/Capacitor: callback: 56527741, pluginId: PushNotifications, methodName: removeDeliveredNotifications, methodData: {"notifications":[{"id":"0:1646839078401306%0257ad8b0257ad8b","data":{"google.delivered_priority":"normal","google.sent_time":"1646839078397","google.ttl":"2419200","google.original_priority":"normal","from":"645040165901","collapse_key":"aaaaaaaaaaaaa","redirectUrl":"bbbbbbbbb"}}]}
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.getcapacitor.plugin.PushNotifications.removeDeliveredNotifications(PushNotifications.java:159)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: aaaaaaaaaaaaa, PID: 18851
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge$1.run(Bridge.java:551)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.getcapacitor.plugin.PushNotifications.removeDeliveredNotifications(PushNotifications.java:159)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Hope this helps (you can even see the notification object passed)

**Comment by sneko** [comment] 2022-03-09 15:26
It may come from: https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/JSObject.java#L60-L71

Since:
```
{
  "notifications": [
    {
      "id": "0:1646839078401306%0257ad8b0257ad8b",
      "data": {
        "google.delivered_priority": "normal",
        "google.sent_time": "1646839078397",
        "google.ttl": "2419200",
        "google.original_priority": "normal",
        "from": "645040165901",
        "collapse_key": "aaaaaaaaaaaaa",
        "redirectUrl": "bbbbbbbbb"
      }
    }
  ]
}
```

has no "integer" named `id`.

**Comment by jcesarmobile** [comment] 2022-03-22 15:32
can you provide a sample app we can run to verify the issue?

**Comment by Ionitron** [comment] 2022-04-07 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-07 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
