### ISSUE TITLE
Support for weekly notifications on Local Notifications plugin

### ISSUE THREAD

**Issue by talkonadmin** [ionic-team/capacitor-plugins#634] opened 2021-09-26 21:13 UTC
### Plugin
Local Notifications

### Description
I am trying to schedule a weekly repeating notification on specific weekday, hour and minute.
As far as I can see in the code,  in order for this to work using the current implementation, the scheduling must be done exactly 
at the time of the first notification since:
1. If using repeating at: the interval is the diff between the scheduled time and the current time.
2. If using every: The start time is relative to the current time, which will cause the first notification to skip.
3. If using at: The day is the day of the month so there is no option for weekly notifications.

To support that there is a need to add:
1. add an option to set the interval for repeating at scheduling
2. add an option to set the start time for every scheduling
3. add an option to set the weekday for at scheduling
4. or maybe add support for rfc5545 recurrence rule which will provide a very flexible way of scheduling

### Platform(s)
Android, iOS

**Comment by jcesarmobile** [comment] 2021-09-27 08:02
Duplicate of https://github.com/ionic-team/capacitor-plugins/issues/129

**Closed by jcesarmobile** 2021-09-27 08:02 UTC
Labels: triage, platform: android, platform: ios
