### ISSUE TITLE
setCamera() crashes the app on native iOS devices

### ISSUE THREAD

**Issue by pct-tploeger** [ionic-team/capacitor-plugins#1760] opened 2023-08-25 08:46 UTC
### Plugin(s)
capacitor/google-maps ver. 5.2.2

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.2.1
  @capacitor/ios: 5.0.5
  @capacitor/android: 5.0.5

### Platform(s)
iOS

### Current Behavior
Calling the setCamera() function crashes the whole app on native iOS devices, even when making sure the map has been created fully. This beavior occurs sometimes right on map startup and sometimes after the map gets reopened. I "fixed" this temporarily by applying a timeout before the map gets created and before the setCamera() gets called (similar to this #980 ). This leaves me with the guess that some kind of race condition is happening here. I added the debug output from xcode below wich gives an nil error.

### Expected Behavior
The app should not crash when there is a nil error in setCamera().

### Additional Context
![MicrosoftTeams-image (6)](https://github.com/ionic-team/capacitor-plugins/assets/111739950/f381b758-a3c4-4cc7-8187-2240f931ab34)

**Comment by Ionitron** [comment] 2023-08-25 09:11
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-09-10 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-10 00:02 UTC
Labels: platform: ios, needs reproduction
