### ISSUE TITLE
"Unable to resolve camera activity" has made a comeback

### ISSUE THREAD

**Issue by VandrerenErik** [ionic-team/capacitor-plugins#1764] opened 2023-08-26 12:09 UTC
### Plugin(s)
Camera v5.0.7

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/ios: 5.2.2
  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0
```

### Current Behavior
When targeting SDK 33 or 34 the camera won't open on  Android with SDK 32 (Android 12), the same seems to happen on SDKs 30 but I haven't tested personally. Note that on Android 13 with SDK 33 or 34 it works just fine.

### Expected Behavior
The plugin to work the same in all SDK versions

### Additional Context
I've already checked similar bug reports from other past issues and I've tried all possible solutions. Before SDK 33 and 34 the plugin was working just fine.

**Comment by Ionitron** [comment] 2023-08-28 11:18
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-09-13 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-13 00:02 UTC
Labels: needs reproduction, needs reply
