### ISSUE TITLE
Localnotifications.requestPermission shows "{"display":"denied"}"

### ISSUE THREAD

**Issue by jayfortune03** [ionic-team/capacitor-plugins#1627] opened 2023-05-31 08:21 UTC
### Plugin(s)

- Local Notifications

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/ios: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4

[success] Android looking great! 👌
[error] Xcode is not installed
```

### Current Behavior

AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="id.happyhomes.chat">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.ACCESS_DOWNLOAD_MANAGER" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="id.happyhomes.chat.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
    </application>

    <!-- Permissions -->
</manifest>
```

I have registered the required permission on the docs to prompt notifications permission for android 13. But it didn't prompt and showed `{"display":"denied"}` when I checkPermissions.

### Expected Behavior

Prompts to user to show notifications

### Code Reproduction

    async requestNotificationPermission() {
      try {
        const permissionResult = await LocalNotifications.checkPermissions()
        console.log(
          `🥶🥶🥶🥶 ~ フ ク ロ ウ file: LayoutContentVerticalNav.vue:1662 ~ フ ク ロ ウ requestNotificationPermission ~ フ ク ロ ウ permissionResult:`,
          JSON.stringify(permissionResult),
        )
        if (permissionResult.display !== 'granted') {
          const requestResult = await LocalNotifications.requestPermissions()
          if (requestResult.display !== 'granted') {
            // Handle permission not granted
            return
          }
        }

        // Permission granted, you can now schedule and display notifications
      } catch (error) {
        // Handle error
      }
    },

this is the code when I call the functions

### Other Technical Details

Android studio flamingo
Android compile SDK 33

**Comment by Ionitron** [comment] 2023-05-31 13:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-16 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-16 00:02 UTC
Labels: needs reproduction, needs reply
