### ISSUE TITLE
Google Map - Polygon and Polyline

### ISSUE THREAD

**Issue by rateltechcom** [ionic-team/capacitor-plugins#1396] opened 2023-01-29 21:48 UTC
Feature Request

Plugin
google-map

Description
I cannot continue to my project without draw a polygon on map.  Please help me :)

Platform(s)
IOS - Android - Web

**Comment by jcesarmobile** [comment] 2023-01-30 09:39
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1036

**Closed by jcesarmobile** 2023-01-30 09:39 UTC
Labels: triage
