### ISSUE TITLE
[Google Maps] App crashing on startup when plugin is installed

### ISSUE THREAD

**Issue by airton-canale** [ionic-team/capacitor-plugins#1976] opened 2023-12-22 20:22 UTC
### Plugin(s)
List the plugins and versions that this bug affects.
@capacitor/google-maps@5.4.0

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.8.1
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
```

### Platform(s)
List the platforms that this bug affects.
I only tested on Android

### Current Behavior

When @capacitor/google-maps is installed, the app crashes on startup, before the splash screen, if I uninstall the plugin the problem goes away and the app opens as usual

**Comment by ngmiduc** [comment] 2023-12-23 18:07
Did you added your GOOGLE_API_KEY inside the manifest.xml ? 
This was my issue when I encountered something like you have.

**Comment by Ionitron** [comment] 2024-01-02 22:17
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by yong-asial** [comment] 2024-01-14 14:15
Hi, i experience the same. ummm, where i should add the API key?

```
<?xml version="1.0" encoding="utf-8" ?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application ...
      ...
    </application>
    ...
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <meta-data android:name="com.google.android.geo.API_KEY" android:value="API_KEY_HERE" />
</manifest>
```

is it correct? Thank you.

**Comment by Ionitron** [comment] 2024-01-18 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-18 00:02 UTC
Labels: platform: android, needs reproduction
