### ISSUE TITLE
E/FirebaseMessaging: Error while delivering the message: ServiceIntent not found.

### ISSUE THREAD

**Issue by dchedufa** [ionic-team/capacitor-plugins#1140] opened 2022-08-20 20:28 UTC
Hi, i recently updated my app from capacitor 3 to 4 and also the related plugins. I have done also the installation steps again from push-notification oplugins.

I tried to find a resolution bad i still get " E/FirebaseMessaging: Error while delivering the message: ServiceIntent not found." everytime the app is running on the background. 

In foreground i receive the push but is untappable.
Any suggestions on this issue?

**Comment by Ionitron** [comment] 2022-08-22 10:03
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-07 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-07 00:03 UTC
Labels: needs reproduction, needs reply
