### ISSUE TITLE
unable to read downloaded file using downloadFile func on ios 

### ISSUE THREAD

**Issue by JawherHamza** [ionic-team/capacitor-plugins#1861] opened 2023-10-27 00:38 UTC
i'm having a problem reading the downloaded file to use it in the video player  

 let read = await readFile({ path: 'FILE_PATH' })
 var blobURL = URL.createObjectURL(read.data);
 
`blobURL` is used as video `src` 

but i get this error {"errorMessage":"The file “cyeimC7i3QGBt3Q5_41701.mp4” couldn’t be opened using text encoding Unicode (UTF-8).",}

i tried using different encoders, but same error msg and issue

**Comment by Ionitron** [comment] 2023-10-27 11:04
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-11-12 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-12 00:03 UTC
Labels: needs reproduction
