### ISSUE TITLE
[google-maps] Getting Fatal error while using "Map View" on iOS

### ISSUE THREAD

**Issue by mukul-kmr-jha** [ionic-team/capacitor-plugins#1392] opened 2023-01-27 11:55 UTC
## Bug Report

Google maps is not loading and instead getting the following error on iOS device, on the web its working fine.

```
CapacitorGoogleMaps/Map.swift:121: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2023-01-27 17:10:56.144713+0530 App[9806:2924737] CapacitorGoogleMaps/Map.swift:121: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
(lldb) 
```

### Capacitor Version
```

Ionic:

   Ionic CLI                     : 5.4.16 (/Users/mukul/.nvm/versions/node/v14.20.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.9.4
   @angular-devkit/build-angular : 0.1102.19
   @angular-devkit/schematics    : 11.2.19
   @angular/cli                  : 11.2.19
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 4.4.0
   @capacitor/core : 4.4.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res (update available: 0.15.4) : 0.14.1

```

```
PASTE OUTPUT HERE
```

### Platform(s)
Issue is on iOS

### Current Behavior
Template changes

container.component.html
```html
   <ion-header>HEADER DESIGN</ion-header>
   <ion-content>
        <app-map-view class="map-container"></app-map-view>
        <other-ui></other-ui> --> some other UI item to be shown on top of the map
  </ion-content>
```

map-view.component.html
```html
<capacitor-google-map #mapRef></capacitor-google-map>
```

CSS changes
```css

.map-container {
    display: block;
    position: absolute;
    top: 0; 
    left: 0;
    width: 100vw;
    height: 100vh;
}

capacitor-google-map {
    display: block;
    width: 100%;
    height: 100%;
}

```

### Expected Behavior
Map should be rendered.

**Comment by Ionitron** [comment] 2023-01-27 17:49
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mukul-myhq** [comment] 2023-01-27 17:53
Hi @jcesarmobile and team, any suggestions/pointers here in this issue?

**Comment by Ionitron** [comment] 2023-01-27 17:59
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-12 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-12 00:03 UTC
Labels: platform: ios, needs reproduction, needs reply

**Comment by mukul-myhq** [comment] 2023-02-23 18:20
Hey @jcesarmobile , any resolutions / pointers for this one? Thanks!

**Comment by mukul-myhq** [comment] 2023-03-10 05:56
Hi @Ionitron  its still unresolved, requesting to reopen this. @jcesarmobile would appreciate if i can get some suggestions/pointer for this. Thank you!
