### ISSUE TITLE
Google Maps not working in IOS

### ISSUE THREAD

**Issue by jvargas91** [ionic-team/capacitor-plugins#1007] opened 2022-05-26 21:26 UTC
### Plugin(s)
google-maps

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

[success] iOS looking great! 👌
```

### Platform(s)
IOS

### Current Behavior

⚡️  To Native ->  CapacitorGoogleMaps create 134192264
⚡️  To Native ->  CapacitorGoogleMaps create 134192265
⚡️  TO JS undefined
⚡️  TO JS undefined
⚡️  To Native ->  CapacitorGoogleMaps enableCurrentLocation 134192266
⚡️  To Native ->  CapacitorGoogleMaps setCamera 134192267
⚡️  To Native ->  CapacitorGoogleMaps enableCurrentLocation 134192268
⚡️  To Native ->  CapacitorGoogleMaps setCamera 134192269
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file CapacitorGoogleMaps/Map.swift, line 322
2022-05-26 17:03:03.456091-0400 App[43661:2526979] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file CapacitorGoogleMaps/Map.swift, line 322

    func enableCurrentLocation(enabled: Bool) throws {
        DispatchQueue.main.sync {
            self.mapViewController.**GMapView**.isMyLocationEnabled = enabled
        }
    }

### Code Reproduction

      const apiKey = 'KEY';
      this.map = await GoogleMap.create({
        id: 'my-map',
        element: this.mapRef.nativeElement,
        apiKey: apiKey,
        config: {
          center: {
            lat: parseFloat(this.positionDefault.lat),
            lng: parseFloat(this.positionDefault.lng)
          },
          zoom: 15
        },
      });

### Additional Context

"@capacitor/google-maps": "^1.0.0"
MacBook Pro (13-inch, M1, 2020)
Chip Apple M1
xcode Version 13.3.1 (13E500a)

**Comment by Ionitron** [comment] 2022-05-26 21:50
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-11 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-11 00:02 UTC
Labels: platform: ios, needs reproduction, needs reply

**Comment by phrammon** [comment] 2022-06-12 20:16
Hi. I've encountered the exact same issue, can you please let me know what info is missing from the OP so I can provide it?

**Comment by phrammon** [comment] 2022-06-12 21:49
Leaving a workaround here for other people encountering this issue.
I get the crash when creating the map during the `ionViewDidEnter` hook.
Putting the GoogleMap.create code inside a setTimeout without a duration seems to fix it.

`  ionViewDidEnter(): void {
    setTimeout(() => {
      this.renderMap();
    });
  }`
  `renderMap(){
    Geolocation.getCurrentPosition().then(position => {

      this.createMap(position.coords.longitude, position.coords.latitude).then(map => {
        this.googleMap = map;
        this.mapIsLoading=false;
        map.addMarker({
          coordinate: { lat: position.coords.latitude, lng: position.coords.longitude },
          title: 'You are here'
        })
      });
    });
  }`
