### ISSUE TITLE
Google Map is not working in React18/Nextjs After installation

### ISSUE THREAD

**Issue by swapnilnandgave** [ionic-team/capacitor-plugins#1374] opened 2023-01-13 09:52 UTC
### Plugin(s)
```Google Maps```

### Capacitor Version
```
"@capacitor/cli": "^4.6.1"
"@capacitor/android": "^4.6.1",
"@capacitor/core": "^4.6.1",
"@capacitor/google-maps": "^4.3.2",
"@capacitor/ios": "^4.6.1"
```

### Platform(s)
```web``` ```Android``` ```iOS```

### Current Behavior
I have installed google map plugin and did npm run dev and getting below error. It is nextjs typescript static application.
```
error - unhandledRejection: TypeError: Cannot read properties of undefined (reading 'CapacitorGoogleMapsWeb')
    at /Users/swapnilnandgave/swapnil/web/projects/trials/nextjs/next-google-map/node_modules/@capacitor/google-maps/dist/plugin.cjs.js:51:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadPluginImplementation (/Users/swapnilnandgave/swapnil/web/projects/trials/nextjs/next-google-map/node_modules/@capacitor/core/dist/index.cjs.js:159:47)
error - ReferenceError: HTMLElement is not defined
    at Object.<anonymous> (/Users/swapnilnandgave/swapnil/web/projects/trials/nextjs/next-google-map/node_modules/@capacitor/google-maps/dist/plugin.cjs.js:63:32)
```

### Expected Behavior
It should display google map

### Code Reproduction
1. Install Latest Nextjs application
2. Initiliaze capacitor
3. Install Google Map Capacitor Plugin
4. Run ```npm run dev```

### Other Technical Details
It is nextjs 13 typescript application

### Additional Context
![Screenshot 2023-01-13 at 3 07 02 PM](https://user-images.githubusercontent.com/1922846/212290695-bb90b71d-b810-41d4-a7d1-f82e58971665.png)

**Comment by Ionitron** [comment] 2023-01-17 17:10
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-02 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-02 00:02 UTC
Labels: platform: web, needs reproduction, needs reply
