### ISSUE TITLE
When using the @capacitor/camera plugin, the system image picker menu displays incorrectly on Android devices in landscape mode.

### ISSUE THREAD

**Issue by AleksandrMatuka** [ionic-team/capacitor-plugins#2172] opened 2024-08-14 09:22 UTC
## Bug Report
When trying to use the `Camera.getPhoto `method, the plugin invokes the system menu with options for adding a photo, which is not displayed as expected in landscape mode ( Android ).

### Plugin(s)
"@capacitor/camera": "^6.0.0",

### Capacitor Version
Capacitor 6

### Platform(s)
Android API 30 - 35.
Tested with Pixel 8 Pro API 30.

### Current Behavior
The system menu is not fully displayed, misleading the user into thinking there are no options available, and it's unclear whether it's possible to scroll down or not.
<img width="902" alt="" src="https://github.com/user-attachments/assets/1c1c56ca-6013-435f-9ad2-6db926339720">

### Expected Behavior
<img width="912" alt="" src="https://github.com/user-attachments/assets/f67dbc93-603d-42c0-85d7-efbdd0eec48c">

### Related issue:
https://github.com/ionic-team/capacitor-plugins/issues/1643

**Comment by Ionitron** [comment] 2024-08-19 16:23
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-09-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-09-04 00:03 UTC
Labels: platform: android, needs reproduction
