### ISSUE TITLE
Wrong Intent.EXTRA_REFERRER is set when launching CustomTab

### ISSUE THREAD

**Issue by jindorx** [ionic-team/capacitor-plugins#1728] opened 2023-08-10 16:40 UTC
### Plugin(s)
capacitor/browser

### Capacitor Version
```
$ npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/core: 5.2.2

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)

Android

### Current Behavior

A wrong Intent.EXTRA_REFERRER is set when the browser plugin is launching CustomTab.  This is supposed to be of form 'scheme://package.name' but a bug in the code https://github.com/ionic-team/capacitor-plugins/blob/66c7217cf3a61aef90346efbd0daa17479fd3769/browser/android/src/main/java/com/capacitorjs/plugins/browser/Browser.java#L108 generates a wrong string, such as '2//com.devhd.feedly", likely set by Feedly which uses the plugin.

The line with a bug is as follows: 
```
tabsIntent.intent.putExtra(Intent.EXTRA_REFERRER, Uri.parse(Intent.URI_ANDROID_APP_SCHEME + "//" + context.getPackageName()));
```

It clearly intends to construct a Uri of the form android-app://com.example.app, but it messes up. [URI_ANDROID_APP_SCHEME](https://developer.android.com/reference/android/content/Intent#URI_ANDROID_APP_SCHEME) is an int flag (1 << 1), not a string constant for the android-app scheme.  It is also missing the colon.

### Expected Behavior

The line should generate a Uri of valid form, starting with a scheme (android-app in this case), followed by a colon, and then the app's package name.  

### Code Reproduction

Repro can be done with any Android app built with capacitor, using the browser plugin to launch CustomTab for viewing urls. The step below uses Feedly:

1. Install Feedly and launch, start with "Get started for free" option, and login (Sign up with Google, for instance)
2. Add content (any content will do). Choose, for instance, TECH -> Engadget 
3. Select any feed article, and tap any links in the article to launch a CustomTab to view it

You see a toast message "Running in Chrome" at the bottom of the screen every time you launch CustomTab. This is supposed to show up only for the first time CustomTab is launched, and then stops on subsequent launches.

A demo clip showing the issue caused by the bug: https://drive.google.com/file/d/1534yvHbAo2n9Uo3BxiI893DgYqMiRGgr/view?usp=drive_link

### Other Technical Details

It doesn't even need to set the referrer extra explicitly if the plugin wants it to reflect the calling package name - since this is the default behavior.

### Additional Context

CustomTab shows the branding label saying "Running in Chrome" to let users know that the feature is served by Chrome (or any default Web browsers). It is designed to show up just once at the first launch of CustomTab. The bug described here i.e. invalid referrer is getting the browser confused about the identity of the app launching it, resulting in the repeated occurrences of the label. This is not the best user experience.

**Comment by jindorx** [comment] 2023-08-10 17:13
This is where the default referrer for CustomTab is set to android-app://package.name:

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/Activity.java;l=6519;drc=82470eb398a82833220d5b462ab8154e4c79a182

**Comment by jindorx** [comment] 2023-08-10 17:27
Create a PR https://github.com/ionic-team/capacitor-plugins/pull/1729

**Comment by Ionitron** [comment] 2023-08-15 12:19
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-08-31 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-08-31 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
