### ISSUE TITLE
Critical & Time Sensitive Push Permissions

### ISSUE THREAD

**Issue by jeremywj** [ionic-team/capacitor-plugins#1565] opened 2023-05-01 03:10 UTC
### Plugin
push-notifications

### Description
Expand to allow checking and requesting of critical and time sensitive alerts.

### Platform(s)
iOS

**Comment by jcesarmobile** [comment] 2023-08-25 11:11
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/659

**Closed by jcesarmobile** 2023-08-25 11:11 UTC
Labels: platform: ios
