### ISSUE TITLE
Black screen before splash is loaded

### ISSUE THREAD

**Issue by asiermusa** [ionic-team/capacitor-plugins#1003] opened 2022-05-24 12:34 UTC
### Plugin(s)
@capacitor/splash-screen

### Capacitor Version
@capacitor/core: "^3.5.0"

I don't know why but when app is launched it loads a black screen and some miliseconds later start the splash screen image. I generate the icons and splash images with the cordova-res plugin.

https://user-images.githubusercontent.com/32843723/170035663-3451c06d-af35-499a-a7b7-4f3626f09ff6.mp4

**Comment by Ionitron** [comment] 2022-05-24 12:45
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-06-09 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-06-09 00:02 UTC
Labels: needs reproduction

**Comment by asiermusa** [comment] 2022-07-09 14:29
I'm sure that the problem is not only mine because I tried with different projects and in fresh instslations the behaivour is the same too.

When I launch the app it always shows black screen. If a set some miliseconds for the splash screen (capacitor config file) it respects the miliseconds but shows the splash image after the black screen as I mentioned in previous post.
