### ISSUE TITLE
Capacitor Splash-screen Jasmine unit test bug

### ISSUE THREAD

**Issue by Kevinlok** [ionic-team/capacitor-plugins#463] opened 2021-06-07 15:42 UTC
### Plugin(s)

@capacitor/splash-screen

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
```

### Current Behavior

A correct unit test for Splashscreen.hide in jasmine won't result in a passed test. 
Error: Expected spy hide to have been called.

### Expected Behavior

The test should pass, the spy for splashscreen.hide should have been called.

### Code Reproduction

// app.component.spec.ts

import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { CoreService } from './core/core.service';
import { SplashScreen } from '@capacitor/splash-screen';
import { Platform } from '@ionic/angular';

describe('AppComponent', () => {
  let component: AppComponent;
  let fixture: ComponentFixture<AppComponent>;
  let coreService: CoreService;
  let platform: Platform;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
      providers: [Platform]
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    coreService = TestBed.inject(CoreService);
    platform = TestBed.inject(Platform);
  });

it('should hide the splashscreen', () => {
    spyOn(platform , 'ready').and.callFake(() => Promise.resolve(''));
    const spy = spyOn(SplashScreen, 'hide');
    fixture.detectChanges();
    expect(spy).toHaveBeenCalled();
  });

//App.component.ts (the code that should be tested)

import { SplashScreen } from '@capacitor/splash-screen';
import { Platform } from '@ionic/angular';

  constructor(public platform: Platform) {}

  private initializeApp(): void {
    this.platform.ready().then(() => {
      SplashScreen.hide();
    });
  }

### Other Technical Details

Versions: 
"@angular/core": "~12.0.3",
"@capacitor/splash-screen": "^1.0.0",
"@capacitor/core": "3.0.0",
"@ionic/angular": "^5.6.4",
"@ionic-native/core": "^5.33.1",
 "jasmine-core": "~3.7.1",
 "jasmine-spec-reporter": "~7.0.0",
 "karma": "~6.3.3",
"typescript": "~4.2.4"

### Additional Context

Chrome 91.0.4472.77 (Mac OS 10.15.7) AppComponent should hide the splashscreen FAILED
        Error: Expected spy hide to have been called.
            at <Jasmine>
            at UserContext.<anonymous> (src/app/app.component.spec.ts:50:17)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
Chrome 91.0.4472.77 (Mac OS 10.15.7): Executed 1 of 55 (1 FAILED) (skipped 54) (0.19 secs / 0.121 secs)
TOTAL: 1 FAILED, 0 SUCCESS

**Comment by Ionitron** [comment] 2021-06-07 16:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-24 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-24 00:01 UTC
Labels: needs reply, needs reproduction
