### ISSUE TITLE
Android build crash 

### ISSUE THREAD

**Issue by yeasin-hossain** [ionic-team/capacitor-plugins#1427] opened 2023-02-23 04:18 UTC
### Plugin(s)
--> @capacitor/network
List the plugins and versions that this bug affects.
--> 4.1.0

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/core: 3.5.1
  @capacitor/ios: 3.6.0
  @capacitor/android: 3.5.1
  @capacitor/cli: 3.5.1

```
PASTE OUTPUT HERE
```

### Current Behavior

<img width="960" alt="image" src="https://user-images.githubusercontent.com/50882838/220820480-703893ef-3009-4495-8bdb-72726f62aa39.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50882838/220820493-e0599a16-7396-4210-aeef-8d6f560949df.png">

**Comment by Ionitron** [comment] 2023-02-23 08:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-11 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-11 00:03 UTC
Labels: needs reproduction, needs reply
