### ISSUE TITLE
Filesystem: special character encoding

### ISSUE THREAD

**Issue by ChristofferAaen** [ionic-team/capacitor-plugins#2200] opened 2024-09-24 18:23 UTC
## Bug Report
When i use the filesystem.writefile, I encounter that im not able to have danish characters like "æ" "ø" and  "å" on either Android or iOS in the filepath. I have tried to decode it before i call the function however no matter what I have tried it return the characters as encoded. On PC however, it works perfectly fine. I have played around with the encoding but to no luck. I suspect this to be a bug.
### Capacitor Version
<
![image](https://github.com/user-attachments/assets/2ba168d7-2ebb-415c-ac70-38cfffb6e79e)

```
PASTE OUTPUT HERE
```

### Platform(s)

Android, iOS

### Current Behavior

create a filepath that contains danish characters on Android and iOS return the encoded string of characters

### Expected Behavior

To show the characters like on PC

**Comment by Ionitron** [comment] 2024-10-16 08:50
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-11-01 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-11-01 00:04 UTC
Labels: platform: android, platform: ios, needs reproduction
