### ISSUE TITLE
Android Geolocation : watchPosition() stops watching after some minutes

### ISSUE THREAD

**Issue by matteobaldini-quix** [ionic-team/capacitor-plugins#382] opened 2021-05-11 07:29 UTC
### Plugin(s)
Geolocation

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/android 2.4.7
  @capacitor/core 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 

### Platform(s)
Android

### Current Behavior
watchPosition() stops emitting values after like 3 minutes.

### Expected Behavior
watchPosition() should keep emitting values even after that time, and ideally keep emitting values even when the app is in background.

### Code Reproduction
Geolocation.watchPosition({
      enableHighAccuracy: true
    }, (pos, error) => {
      console.log(pos);
    })

**Comment by Ionitron** [comment] 2022-09-20 17:19
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-10-06 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-06 00:05 UTC
Labels: platform: android, needs reproduction, needs reply, plugin: geolocation
