### ISSUE TITLE
Java library throwing errors when building for Android

### ISSUE THREAD

**Issue by Wendryl** [ionic-team/capacitor-plugins#1859] opened 2023-10-24 23:54 UTC
### Plugin(s)
- capacitor-geolocation v5.0.6

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

[error] Xcode is not installed
[success] Android looking great! 👌

```

### Platform(s)
- Android

### Current Behavior
I'm getting the following error when trying to run my Ionic App on an Android physical device:

![image](https://github.com/ionic-team/capacitor-plugins/assets/43496662/56466c77-4463-41c3-b65f-bec3869f869d)

![image](https://github.com/ionic-team/capacitor-plugins/assets/43496662/8096a867-9838-49ac-9f20-b106a925eed9)

### Expected Behavior
It should build and run with no errors.

**Comment by Ionitron** [comment] 2023-10-25 08:40
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-11-10 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-10 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
