### ISSUE TITLE
Device Plugin not returning the exact model name of the device

### ISSUE THREAD

**Issue by wadhersmitesh** [ionic-team/capacitor-plugins#888] opened 2022-03-22 10:46 UTC
### Plugin(s)

@capacitor/device

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS & Android

### Current Behavior

The model variable inside object is returning the model name as android for platform Android and iPhone for platform iOS

### Expected Behavior

The model variable should return iPhone 13 / iPhone 13 Pro Max.

**Comment by jcesarmobile** [comment] 2022-03-22 10:50
duplicate of https://github.com/ionic-team/capacitor-plugins/issues/804

**Closed by jcesarmobile** 2022-03-22 10:50 UTC
Labels: platform: android, platform: ios
