### ISSUE TITLE
network change back to WiFi does not trigger network listener/promise

### ISSUE THREAD

**Issue by lazmeister** [ionic-team/capacitor-plugins#1375] opened 2023-01-17 19:56 UTC
### Plugin(s)
@capacitor/network

### Capacitor Version
4.1.0

### Platform(s)
Angular 14.2.8
Ionic/Angular 6.36
Web/PWA

### Current Behavior
When using Network.addListener, the promise is triggered when device is taken off Wi-Fi, though when you enable Wi-Fi afterwards, the listener does not get triggered.

### Expected Behavior
Network.addListener should be triggered when Wi-Fi is enabled or disabled.

### Code Reproduction

```
// Listen to network changes
      Network.addListener('networkStatusChange', status => {
        console.log(status.connected);
        if (status.connectionType === 'wifi') {
          networkConnectionWifi = true;
        } else {
          networkConnectionWifi = false;
        }
        // Check connection status
        currentNetworkStatus = status.connected;
      });
```

**Comment by Ionitron** [comment] 2023-01-18 09:44
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-03 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-03 00:02 UTC
Labels: platform: web, needs reproduction, needs reply

**Comment by lazmeister** [comment] 2023-02-08 01:13
Here is the picture of the testing from the repo showing going from wifi to mobile connection, the network listener is triggered, but when going from mobile back to wifi the network listener does not trigger any event
![image](https://user-images.githubusercontent.com/3281599/217402829-9e0690a7-79c3-403f-913f-976d61ac38c8.png)

public repo for testing: https://github.com/lazmeister/CapacitorWifiIssue

**Comment by lazmeister** [comment] 2023-02-08 01:15
@jcesarmobile Sorry Just wanted to make sure this issue is reopened to investigate or if you need me to submit a new issue. Thanks
