### ISSUE TITLE
Issue when opening URL with @capacitor/browser

### ISSUE THREAD

**Issue by Dante1349** [ionic-team/capacitor-plugins#2253] opened 2024-11-21 13:03 UTC
### Plugin(s)
* @capacitor/browser

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/ios: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
--------------------------------------
```

### Platform(s)
* iOS 18 simulator

### Current Behavior
Viewport stays white, back button has no function. 
No error logs in console. 
Close button in notch safe-area.

### Expected Behavior
Page loads correctly. 
Back button click makes user return to app.
Close button below notch safe-area.

### Code Reproduction
Browser.open({ url: url }).catch((error) => {
    console.error("Cannot open url in browser", error);
});

### Other Technical Details
The issue only occurs in the iOS simulator but not on a real iOS devices that also has iOS 18. No issues, no hint whats going on atm.

#### Screenshot
![image](https://github.com/user-attachments/assets/90d3205f-189c-4c72-ae23-4e139e73da15)

**Comment by Ionitron** [comment] 2024-11-29 11:45
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-12-15 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-12-15 00:04 UTC
Labels: needs reproduction
