### ISSUE TITLE
 "SplashScreen" plugin is not implemented on android

### ISSUE THREAD

**Issue by Isaacn123** [ionic-team/capacitor-plugins#517] opened 2021-07-14 12:41 UTC
how can we be helped on Capacitor 3.1.1
vendor.js:61418 ERROR Error: Uncaught (in promise): Error: "SplashScreen" plugin is not implemented on android

**Comment by Ionitron** [comment] 2021-07-14 14:09
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-07-30 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-07-30 00:01 UTC
Labels: needs reply, needs reproduction
