### ISSUE TITLE
Dismiss Keyboard Prevented on iOS

### ISSUE THREAD

**Issue by howlettga** [ionic-team/capacitor-plugins#2174] opened 2024-08-15 19:47 UTC
### Plugin(s)
"@capacitor/keyboard": "6.0.1"

### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
```

### Platform(s)
iOS

### Current Behavior
Whenever the keyboard is opened on iOS (mainly input events), the keyboard cannot be dismissed by swiping down on it. This should be the default behavior and is how just about every app on my phone works. Now it is stuck and you can't use half the screen real estate. Having a keyboard that can't be dismissed creates a broken and bad user experience.

### Expected Behavior
The keyboard is dismissed when the swipe down gesture is used on the keyboard.

### Code Reproduction
Run the `ionic start` command and create a new project using Capacitor. Add an input element and add an iOS project. Open the application on an iOS device and select the input. The keyboard that comes up cannot be dismissed.

### Additional Context
[Apple API](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode)
This is a baseline iOS behavior that needs to be available on any modern iOS app.

**Comment by Ionitron** [comment] 2024-08-19 16:24
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-09-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-09-04 00:03 UTC
Labels: platform: ios, needs reproduction
