### ISSUE TITLE
Geolocation package is not working

### ISSUE THREAD

**Issue by TalhaWorking** [ionic-team/capacitor-plugins#2001] opened 2024-01-20 12:25 UTC
### Plugin(s)
@capacitor/geolocation ^5.0.6

### Capacitor Version
Paste the output from the `npx cap doctor` command into the code block below. This will provide the versions of Capacitor packages and related dependencies.

```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[error] gradlew file is missing in android
        AndroidManifest.xml is missing in app/src/main
```

### Platform(s)
Web

### Current Behavior
When I am trying to get a current position using Geolocation.getCurrentPosition() it gives an error 
Error -> Network error. Check DevTools console for more information.
or sometime -> Timeout expired

### Expected Behavior
It should return the coordinates

### Code Reproduction
[](https://github.com/TalhaWorking/demo-repo-capacitor-geolocation)

### Other Technical Details
I am using the Brave browser

**Comment by Ionitron** [comment] 2024-02-26 17:18
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-03-13 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-03-13 00:03 UTC
Labels: platform: web, needs reproduction, needs reply
