### ISSUE TITLE
Google Maps: Support for MapOptions.styles (Styled Map Selection)

### ISSUE THREAD

**Issue by mandrasch** [ionic-team/capacitor-plugins#1169] opened 2022-09-06 13:31 UTC
### Plugin
Google Maps

### Description

Would be awesome if the plugin supports `.styles` to customize the color scheme, especially important for work for clients.

Docs & demo: https://developers.google.com/maps/documentation/javascript/examples/style-selector

### Platform(s)
All

### Preferred Solution
https://developers.google.com/maps/documentation/javascript/examples/style-selector

### Alternatives
None known, or could we directly access gmaps object and call `map.setOptions({ styles: ... })`? Don't know if Javascript SDK is working in the background?

### Additional Context

Thanks very much in advance for replying!

**Comment by jcesarmobile** [comment] 2022-09-06 13:39
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/946

**Closed as not planned by jcesarmobile** 2022-09-06 13:39 UTC
