### ISSUE TITLE
Status bar reappears when interacting with input boxes

### ISSUE THREAD

**Issue by apbarratt** [ionic-team/capacitor-plugins#515] opened 2021-07-13 09:36 UTC
## Bug Report
Very much related to https://github.com/ionic-team/capacitor-plugins/issues/79

After hiding the status bar using `StatusBar.hide()`, interacting with an input box such as an ion-input will cause the status bar to reappear.

The current recommended solution to this behaviour (which is the same as described in issue 79 but not due to deliberate user interaction) is to poll and hide the bar if it should reappear.

I would far rather the status bar simply not appear at all.

Note, this does not seem to happen on all devices and we have found that it in fact does not happen on a new Samsung phone with all the latest updates, but it does on an identical one which hasn't been updated for some time.

I'm sorry to say we haven't taken many notes to keep track of versions.  But on older devices that simply can't be updated further, this is proving quite a problem.

Unfortunately, we use these devices in TV production, so having the bar flash up even for a split second isn't an option for us.

Additionally, if we poll and hide the status bar again whilst the keyboard remains open, the bar does indeed disappear but the ion-header behind it does not resize to collapse back into the space cleared.  Meaning we end up with what looks like an ion-header with a chunk of `padding-top` added in.  This disappears once the keyboard is closed.

I'd very much like a fix for this, or a work around that doesn't result in visible artifacts if anyone has any suggestions :)

### Plugin(s)
Status Bar

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/ios: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/core: 3.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Load an app that calls `StatusBar.hide()` on startup (in my case, inside an `ngOnInit` function).
On the home screen, have an ion-input component.

Tap the input on an android device running an older version of android (sorry I couldn't be more specific, our latest experiment tells us it's a problem at least on Android 10 but not 11)
Observe that the StatusBar has returned when the keyboard did.

### Expected Behavior

Status Bar should remain hidden, regardless of the keyboard behaviour.

**Comment by jcesarmobile** [comment] 2021-07-13 11:10
it's a duplicate of the issue you linked, interacting with input boxes qualify as user interaction

**Closed by jcesarmobile** 2021-07-13 11:10 UTC
Labels: platform: android, triage

**Comment by apbarratt** [comment] 2021-07-13 11:16
Fair enough, I'd wondered if this would considered different as tapping the top to see the clock could be seen as a deliberate user interaction, one that would actually be quite frustrating to block happening.  Whereas user interaction with an input box inside an app that has nothing to do with the status bar would be more likely seen as undesirable :)
