### ISSUE TITLE
@capacitor/camera is there a way to obtain the EXIF data or file name after taking a photo

### ISSUE THREAD

**Issue by st474ddr** [ionic-team/capacitor-plugins#1910] opened 2023-11-17 17:20 UTC
### Plugin
@capacitor/camera

### Description
Is there a way to obtain the EXIF data or file name after taking a photo.
When I take a photo, I only can get dataUrl or webPath...

### Platform(s)
web

### Preferred Solution
The getPhoto function provides the return of the file name or EXIF data.

### Alternatives
Or other function I can take photo and get photo name.

**Comment by jcesarmobile** [comment] 2023-11-20 08:53
No, it's not possible to get the exif on web, and when you take a picture there is no file name, neither.

Closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/327

**Closed by jcesarmobile** 2023-11-20 08:53 UTC
Labels: platform: web
