### ISSUE TITLE
bug: AppPlugin.minimizeApp() throws No Activity found to handle Intent

### ISSUE THREAD

**Issue by qliqdev** [ionic-team/capacitor-plugins#1572] opened 2023-05-03 15:41 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

Installed Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- [x] android

### Current Behavior

```
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
       at android.app.Activity.startActivityForResult(Activity.java:5516)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java)
       at android.app.Activity.startActivityForResult(Activity.java:5474)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java)
       at android.app.Activity.startActivity(Activity.java:5860)
       at android.app.Activity.startActivity(Activity.java:5813)
       at com.capacitorjs.plugins.app.AppPlugin.minimizeApp(AppPlugin.java:21)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:29)
       at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Expected Behavior

Should check for active Activity intent and minimize app if available

### Additional Context

Got this crash log from firebase crashlytics

**Comment by Ionitron** [comment] 2023-05-03 19:04
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-05-19 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-05-19 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
