### ISSUE TITLE
GoogleMap 'Missing or invalid map id' 

### ISSUE THREAD

**Issue by djabif** [ionic-team/capacitor-plugins#1969] opened 2023-12-19 12:30 UTC
### Plugin
Google Maps

### Description
I found that in iOS there's [this code](https://github.com/ionic-team/capacitor-plugins/blob/fb12c049e3bd619dbbab00c21888e3c31021bf88/google-maps/src/map.ts#L229C5-L241C8) that wants to display the map without asking if the map is ready so every time I enter the page I have a 'Missing or invalid map id' error because the plugin calls `OnDisplay` and the map is not ready yet.
 

### Platform(s)
iOS

### Preferred Solution
 Add an `if` to check if the map is ready before calling `OnDisplay`. 

### Alternatives
I did a quick workaround by removing the `ion-page` class in the `ngOnInit` so the `OnDisplay` is not triggered. This fixes my error but it would be good if you could add an `if` to check if the map is ready before calling `OnDisplay`. 

### Additional Context
My map is inside a modal

**Comment by Ionitron** [comment] 2024-01-02 22:18
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-01-18 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-18 00:02 UTC
Labels: platform: ios, needs reproduction
