### ISSUE TITLE
Footer doesn't snap to keyboard with 2 inputs on page

### ISSUE THREAD

**Issue by joshuah459** [ionic-team/capacitor-plugins#1407] opened 2023-02-06 21:22 UTC
### Plugin(s)

@capacitor/keyboard
Original (working version) 4.0.0
Updated Version (not working) 4.1.1

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

### Current Behavior

Currently if 2 inputs are on screen tapping on one will push the ion-footer up up above they keyboard (as expected), however after tapping on the second input (while the keyboard is up) the footer will disappear (returning to the bottom). Tapping on the first input will bring it back, dismissing the keyboard and then tapping the 2nd input inverts the behavior.

### Expected Behavior

The footer should stay in place above the keyboard regardless of which input is tapped or if the next tap is another input. 

### Code Reproduction

Will provide shortly

**Comment by Ionitron** [comment] 2023-05-23 13:38
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-08 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-08 00:03 UTC
Labels: platform: ios, needs reproduction, needs reply
