### ISSUE TITLE
Splash Screen plugin overrides status bar styles

### ISSUE THREAD

**Issue by marcjulian** [ionic-team/capacitor-plugins#1249] opened 2022-10-26 13:43 UTC
### Plugin(s)

- @capacitor/status-bar@4.0.1
- @capacitor/splash-screen@4.1.1
- @hugotomazi/capacitor-navigation-bar@2.0.0 (also effected)

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.4.0
  @capacitor/cli: 4.4.0
  @capacitor/android: 4.4.0

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Changing the styles of StatusBar and NavigationBar is overridden when the `@capacitor/splash-screen` plugin is installed in the project.

```ts
ngOnInit(): void {
    if (Capacitor.getPlatform() === "android") {
      StatusBar.setStyle({ style: Style.Dark });
      StatusBar.setBackgroundColor({ color: "#ef4444" });
      NavigationBar.setColor({ color: "#ef4444" });
    }
  }
```

![Status and Navigation bar color w/ Splash Screen plugin](https://user-images.githubusercontent.com/8985933/198041266-4e51c9f6-d491-40f1-b06b-a45cbf3195ba.png)

### Expected Behavior

The StatusBar and NavigationBar styles should be applied as in the case without the `@capacitor/splash-screen` plugin.

![Screenshot 2022-10-26 at 15 28 35](https://user-images.githubusercontent.com/8985933/198041348-b499068c-3f93-4678-a2dd-f11487fff670.png)

### Code Reproduction

https://github.com/marcjulian/ng-cap-status-bar

**Comment by jcesarmobile** [comment] 2022-10-26 18:02
This is a bug on the Android 12 Splash Screen API, when using `setOnExitAnimationListener` (which Splash Screen uses), it won't allow to make modifications to the device UI while the splash screen is present if it has an exit animation listener.

Android 12 Splash Screen API is bundled into the OS now, so there is nothing we can do about it, only google can fix those kind of issues.
We are considering adding a configuration option for not adding the exit animation listener, which would cause the splash to not have a fade out animation, but would not present the issue neither.

A workaround for your app would be to set the status bar and navigation bar color from the styles
Add this to the `AppTheme.NoActionBar` style in `styles.xml` file.
```
<item name="android:navigationBarColor">#ef4444</item>
<item name="android:statusBarColor">#ef4444</item>
```

closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1160 as the problem is the same

**Closed by jcesarmobile** 2022-10-26 18:02 UTC
Labels: platform: android

**Comment by marcjulian** [comment] 2022-10-27 08:30
Thanks for the clarification of the bug in Android 12 Splash Screen. Your propose workaround works perfect for me, thanks.

**Comment by tobiloeb** [comment] 2022-11-15 15:52
@jcesarmobile I have the same issue but for the statusbar text color. Its always white now and I can't get it black/dark again. Do you have any suggestions to change this in the styles.xml as well?

**Comment by tobiloeb** [comment] 2022-11-16 07:36
I checked the code for the StatusBar Plugin and found this line:
`windowInsetsControllerCompat.setAppearanceLightStatusBars(!style.equals("DARK"));`

So I can fix the text color issue when set the following to my styles:
` <item name="android:windowLightStatusBar">true</item>`

May this helps someone else.
