### ISSUE TITLE
Unable to get data when sending Android push notifications

### ISSUE THREAD

**Issue by Sam-Davis** [ionic-team/capacitor-plugins#1336] opened 2022-12-16 15:03 UTC
## Bug Report
   Expected to be able to send data with a push notification. Push notification received has data overwritten to android defaults and only shows Title and Body. An example of the data received by the android app is here: 
   https://stackoverflow.com/questions/64167615/ionic-capacitor-pushnotiifcations-android-notification-data-messag
   
   
### Plugin(s)
    "@capacitor/android": "^4.0.0",
    "@capacitor/app": "^4.0.1",
    "@capacitor/push-notifications": "^4.1.0",

### Capacitor Version
4

### Platform(s)
Android

### Current Behavior
Plugin shows generic data with id set to 0 and no custom data fields that were sent in the payload. 
{
  body: "My Body",
  data: {
    android.appInfo: "ApplicationInfo{809371c app}",
    android.bigText: "My Body",
    android.progress: 0,
    android.progressIndeterminate: false,
    android.progressMax: 0,
    android.reduced.images: true,
    android.showChronometer: false,
    android.showWhen: true,
    android.template: "android.app.Notification$BigTextStyle",
    android.text: "My Body",
    android.title: "My Title",
    gameDndOn: false,
    specialType: "",
    topFullscreen: false,
    groupSummary: false,
    id: 0,
    title: "My Title"
  }
}

### Expected Behavior
Should be able to use C# FirebaseAdmin.Messaging.MulticastMessage.Data or FirebaseAdmin.Messaging.MulticastMessage.Android.Data to send information about the notification to the app. Currently this is only received by iOS and not android. 

### Code Reproduction
C# send example above and response logged from: 
```
 await PushNotifications.addListener('pushNotificationReceived', (notification: any) => {
      console.log('Push notification received: ', "data:", JSON.stringify(notification));
));
```

### Other Technical Details
Sending data as follows: 
         ```
  var message = new MulticastMessage()
                {
                    Tokens = sendPushNotificationForMessageCommand.push_registration_tokens,
                    
                    Notification = new Notification()
                    {
                        Title = sendPushNotificationForMessageCommand.title,
                        Body = sendPushNotificationForMessageCommand.body,
                        

                    },
                    Data = new Dictionary<string, string>(){
                    {"type", sendPushNotificationForMessageCommand.type },
                    {"id", sendPushNotificationForMessageCommand.id },
                    {"title", sendPushNotificationForMessageCommand.title },
                    {"sent_by_initials", sendPushNotificationForMessageCommand.sent_by_initials },
                    {"sent_by_last_name", sendPushNotificationForMessageCommand.sent_by_last_name },
                    {"timeSent", sendPushNotificationForMessageCommand.timeSent },
                    {"thread_id", sendPushNotificationForMessageCommand.thread_id },
                    {"body", sendPushNotificationForMessageCommand.body },
                    {"studentNames", sendPushNotificationForMessageCommand.studentNames },
                }
```

### Additional Context
See upvotes on this ticket, seems a fairly common issue: [https://stackoverflow.com/questions/64167615/ionic-capacitor-pushnotiifcations-android-notification-data-messag]

**Comment by Ionitron** [comment] 2022-12-16 15:11
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Sam-Davis** [comment] 2022-12-16 15:27
Added more details

**Comment by Ionitron** [comment] 2022-12-16 16:49
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-01 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-01 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
