### ISSUE TITLE
@capacitor/keyboard: Keyboard's height doesn't update

### ISSUE THREAD

**Issue by TheotimeColin** [ionic-team/capacitor-plugins#2193] opened 2024-09-10 16:44 UTC
### Plugin(s)
@capacitor/keyboard: 6.0.0

### Capacitor Version
```
Latest Dependencies:
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.1.2
  @capacitor/android: 6.1.2
```

### Platform(s)
Android

### Current Behavior
- When the keyboard height changes (example: opening emojis), it's not reflected on the app

https://github.com/user-attachments/assets/c3b6429c-2f78-4a45-b9c1-7efdd923fbb6

### Expected Behavior
- The keyboard height should update when the size of the keyboard changes
- It works well on iOS, where 'keyboardDidShow' is fired when the keyboard resizes

**Comment by Ionitron** [comment] 2024-09-16 10:16
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-10-02 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-10-02 00:03 UTC
Labels: platform: android, needs reproduction
