### ISSUE TITLE
Notification does not get triggered if no minute is set

### ISSUE THREAD

**Issue by mahen23** [ionic-team/capacitor-plugins#1073] opened 2022-06-30 05:05 UTC
### Plugin(s)
local notification

### Capacitor Version
3.6.0

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.4.1
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.5.1

[success] Android looking great! 👌
[error] Xcode is not installed

```

### Platform(s)
Linux



### Current Behavior
If i set a notification to be triggered at 9am, if i left the minute blank, its never triggered:

on: {weekday: 4, hour: 9 } => this will never be triggered, be it 9:00 or 09:10 or 09:59
on: {weekday: 4, hour: 9, minute: 4 } => this will be triggered at only 09:04.



### Expected Behavior
Notification should be triggered at least once.

**Comment by Ionitron** [comment] 2022-06-30 20:21
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-07-16 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-16 00:02 UTC
Labels: needs reproduction, needs reply
