### ISSUE TITLE
Allow multiple photo selection from library

### ISSUE THREAD

**Issue by tcihak-fqa** [ionic-team/capacitor-plugins#118] opened 2020-12-02 15:36 UTC
### Plugin
Camera

### Description
Allow multiple pictures to be selected from the photo library.

### Platform(s)
Android
iOS
PWA (if possible)

**Comment by jcesarmobile** [comment] 2021-06-17 13:53
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/227

**Closed by jcesarmobile** 2021-06-17 13:53 UTC
Labels: enhancement, platform: android, platform: ios, platform: web, plugin: camera
