### ISSUE TITLE
Please provide marker rotation in google maps plugin

### ISSUE THREAD

**Issue by rcherukuri-sta** [ionic-team/capacitor-plugins#2053] opened 2024-03-10 12:31 UTC
### Plugin

@capacitor/google-maps

### Description

I use this plugin in an app where vehicle tracking is required and unable to rotate the marker(vehicle) using this plugin. Please provide the capability to set the marker rotation. 

### Platform(s)

Both Android and iOS

**Comment by IT-MikeS** [comment] 2024-03-11 15:44
This is a duplicate of #1428

**Closed** 2024-03-11 15:44 UTC
