### ISSUE TITLE
Motion plugin on iOS not working (permission dialog *never* shows up)

### ISSUE THREAD

**Issue by lucascassiano** [ionic-team/capacitor-plugins#1791] opened 2023-09-11 22:49 UTC
### Plugin(s)
`@capacitor/motion`

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

### Platform(s)
ios (iPhone 12)

### Current Behavior
```ts
const permission = await (DeviceMotionEvent as any).requestPermission();
```
Always returns "denied" and don't even show up the Dialog

### Expected Behavior
Displays the Permission Dialog or even output the "granted" automatically. 

### Other Technical Details
I included on the `Info.plist` file a Usage description, as following:
```xml
	<key>NSMotionUsageDescription</key>
	<string>Use accelerometer data?</string>
```

If anyone knows how to fix this issue, or use another plugin to do so, please let me know. 
iPhones have a rich range of motion sensors, and our project would benefit a *lot* from accessing them within Capacitor.js. 

Thanks!

**Comment by Ionitron** [comment] 2023-09-12 08:33
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-09-28 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-28 00:02 UTC
Labels: platform: ios, needs reproduction, needs reply
