### ISSUE TITLE
Could not find androidx.exifinterface:exifinterface:1.3.3 Required by: project :capacitor-camera

### ISSUE THREAD

**Issue by hooh88** [ionic-team/capacitor-plugins#1304] opened 2022-11-28 14:05 UTC
### Plugin(s)
```
"dependencies": {
    "@angular/cdk": "^15.0.0",
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/fire": "^7.5.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@angular/service-worker": "^15.0.1",
    "@awesome-cordova-plugins/file": "^6.2.0",
    "@awesome-cordova-plugins/file-transfer": "^6.2.0",
    "@capacitor/android": "4.5.0",
    "@capacitor/app": "4.1.1",
    "@capacitor/camera": "^4.1.4",
    "@capacitor/core": "4.5.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/ios": "^4.5.0",
    "@capacitor/keyboard": "4.1.0",
    "@capacitor/status-bar": "4.1.0",
    "@ionic/angular": "^6.1.9",
    "@ionic/pwa-elements": "^3.1.1",
    "@ionic/storage-angular": "^3.0.6",
    "capacitor-voice-recorder": "^4.0.0",
    "howler": "^2.2.3",
    "ionicons": "^6.0.3",
    "jalali-moment": "^3.3.11",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
```

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/ios: 4.5.0
  @capacitor/android: 4.5.0

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
Android

### Current Behavior
I have some problem in my ionic application (Angular). I use capacitor-camera to take photo, when I need to build in Android Studio get this error:

```
Could not find androidx.exifinterface:exifinterface:1.3.3.
Required by:
    project :capacitor-camera
Search in build.gradle files
```

**Comment by Ionitron** [comment] 2022-11-28 14:51
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by hooh88** [comment] 2022-11-28 15:59
Thank you for your response.

I created a reliable Code Reproduction :
[https://github.com/hooh88/CapacitorCameraCodeReproduction](https://github.com/hooh88/CapacitorCameraCodeReproduction)

When I uninstall @capacitor/camera , I can build android project.

Thanks

**Comment by jcesarmobile** [comment] 2022-11-28 17:30
Thanks for the sample app, but you haven't committed the android folder, so how can you be sure it doesn't build?

**Comment by hooh88** [comment] 2022-11-28 19:39
Sorry, I forgot to commit the Android folder.
Please check again

**Comment by jcesarmobile** [comment] 2022-11-29 10:48
Sorry, I still can't reproduce.

I think it's a connectivity problem on your end.
I saw your question on SO and your profile says you are from Iran. 
Looks like the maven repositories where the dependencies such as `androidx.exifinterface:exifinterface` are hosted (google and mavenCentral), are both blocked from Iran according to this thread
https://www.reddit.com/r/androiddev/comments/xxva4t/alternativemirror_for_google_and_mavencentral/

Can you access this url? https://mvnrepository.com/artifact/androidx.exifinterface/exifinterface
and this one? https://maven.google.com/androidx/exifinterface/exifinterface/1.3.3/exifinterface-1.3.3.aar

**Comment by hooh88** [comment] 2022-11-29 13:35
In Iran, some pages are blocked, but I use a VPN to access the internet.
I can access to this url : [https://maven.google.com/androidx/exifinterface/exifinterface/1.3.3/exifinterface-1.3.3.aar](https://maven.google.com/androidx/exifinterface/exifinterface/1.3.3/exifinterface-1.3.3.aar).
However, I have a problem with the first url, when I open this url: [https://mvnrepository.com/artifact/androidx.exifinterface/exifinterface](https://mvnrepository.com/artifact/androidx.exifinterface/exifinterface) in my browser I can open and see them but when I 'check connection' in HTTP Proxy (in android studio settings) and use this url, I got the error 403.

What can I do to solve this problem?
Would it be a good idea to download and use it offline?

**Comment by jcesarmobile** [comment] 2022-11-29 13:49
I have no experience with that, but I don't think it's as simple as downloading the file as the plugin would still expect it from a maven repository.
So you will probably need to create your own local or remote maven repository with the aar files you need.
Here is some info about how to create a local maven repository
https://alessiobianchi.eu/blog/obfuscated-aar-local-maven/

Then you'll have to modify your app to check in that repository first and forcing all the modules to also look there first since the dependency is in the camera plugin, which is a module in your app.

I'm closing since it's not a Capacitor issue.

**Closed by jcesarmobile** 2022-11-29 13:49 UTC
Labels: platform: android, needs reproduction
