### ISSUE TITLE
[Push Notifications] - App on foreground firing a notification without Intent

### ISSUE THREAD

**Issue by dnietodev** [ionic-team/capacitor-plugins#1373] opened 2023-01-11 09:26 UTC
### Plugin
Push Notifications

### Description
When the app is on foreground and receives a push notification "pushNotificationReceived" is fired but also a notification is fired with only title and body and nothing else. This is the code that fires a notification when the app is on foreground (which was included on v4)

[See lines from 217 to 247](https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java)

[Compare it with v3 version, lines 219 to 243](https://github.com/ionic-team/capacitor-plugins/blob/3.x/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java)

If you are sending a deep link within the data and you can't/want to annoy the user at that point by showing a modal or similar when the "pushNotificationReceived" listener fires, you end up with a notification that does nothing. The user can tap on the notification but it won't do anything, not even open the application as it has no associated intent, they can only delete it which is not very useful.

### Platform(s)
Android

### Preferred Solution
Add an Intent setting an extra data from "data". key. https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages.

### Alternatives
Previously on v3, the fireNotification method was only triggering the "pushNotificationReceived" listener, and the we could fire a notification with "Local Notifications Plugin" after getting the data from the listener and have full control of it.

### Additional Context
I think we should have control over the notifications fired when the app is open if not for me does not make any sense as we lose control over it and how the user interacts with our app.

**Comment by Ionitron** [comment] 2023-01-11 09:28
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dnietodev** [comment] 2023-01-12 07:42
Hello, the problem is in these lines [from the source code of the plugin](https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java), 

`NotificationCompat.Builder builder = new NotificationCompat.Builder(
                        getContext(),
                        NotificationChannelManager.FOREGROUND_NOTIFICATION_CHANNEL_ID
                    )
                        .setSmallIcon(pushIcon)
                        .setContentTitle(title)
                        .setContentText(body)
                        .setPriority(NotificationCompat.PRIORITY_DEFAULT);
                    notificationManager.notify(0, builder.build());`
                    
In here for me, it should have a setter with the intent, something like:  https://developer.android.com/develop/ui/views/notifications/navigation#java


I've been working on adding the intent and so far it works, the "handleOnNewIntent" and "fireNotification" methods have been modified. The only thing that doesn't convince me is that the data we receive from the "pushNotificationActionPerformed" listener is in JSON. I have attached a zip with PushNotificationsPlugin.java file modified with the changes. My android knowledge is limited, maybe isn't the best solution  😅

[PushNotificationsPlugin.java.zip](https://github.com/ionic-team/capacitor-plugins/files/10399190/PushNotificationsPlugin.java.zip)

**Comment by Ionitron** [comment] 2023-01-12 16:55
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by junekpavel** [comment] 2023-01-17 15:28
Hello. I'm having the exact same issue.

When notification is received when application is in background, everything works fine. The notification arrives, looks like desired and when user taps the notification the application is opened and the `pushNotificationActionPerformed` is triggered.

But when application is in the foreground and notification is received, the arrived notification missing some of UI settings. But most importantly, the notification isn't clickable. When user clicks the notification, nothing happens.

This is because the Intent isn't set, as described earlier. You can see the official Android docs for detailed information about setting the notification click/tap action - https://developer.android.com/develop/ui/views/notifications/build-notification#click.

Also attaching screenshots of the two notifications. First one arrived when application was in the backgroud, so it's clickable. The second one arrived when application was in the foreground and is not clickable.

![background](https://user-images.githubusercontent.com/39130083/212939373-520fce3e-bb61-4592-8802-b130db477b55.png)  ![foreground](https://user-images.githubusercontent.com/39130083/212939589-2b92001b-e982-4104-b70b-2bf4707dce4d.png)

**Comment by junekpavel** [comment] 2023-01-17 15:39
#1324 Probably related?

**Comment by Ionitron** [comment] 2023-01-18 17:42
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-03 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-03 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
