### ISSUE TITLE
Preferences plugin not available after upgrade to Capacitor v5

### ISSUE THREAD

**Issue by giloliveira-nmi** [ionic-team/capacitor-plugins#1730] opened 2023-08-10 17:58 UTC
### Plugin(s)
- [Preferences plugin](https://capacitorjs.com/docs/apis/preferences)

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
Android

### Current Behavior
When trying to retrieve data from device localStorage in apps that are released through Google Play (on any track), an error pops up: `Preferences plugin is not implemented`. This issue does not appear during development, can be fixed when `minifyEnabled` is set to `false` in de **build.gradle** file and does not appear for other plugins. As such, it seems like ProGuard possibly removes references to the Preferences plugin.

### Expected Behavior
Preferences plugin can be used while `minifyEnabled` can be set to `true` to reduce filesize.

### Code Reproduction
Since the issue only appears on apps published through the Play Store, I am unable to reproduce this issue!

**Comment by Ionitron** [comment] 2023-08-15 12:20
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by muuvmuuv** [comment] 2023-08-21 09:18
You can try to reproduce with the Android Simulator by building a SDK instead of a AAB in "Build" → "Generate signed...". Then locate the file and drag-and-drop it into the simulator. Debugging can be done with logcat. Maybe this helps finding the right proguard flag for minify. 

We have the same issues with other Capacitor plugins and still debugging to find the correct flags ^^ try-and-error I guess.

**Comment by Ionitron** [comment] 2023-09-06 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-06 00:02 UTC
Labels: platform: android, needs reproduction
