### ISSUE TITLE
[Keyboard] Android doesn't account for height of auto suggestions

### ISSUE THREAD

**Issue by IljaDaderko** [ionic-team/capacitor-plugins#275] opened 2021-02-26 10:44 UTC
### Plugin(s)

@capacitor/keyboard: 0.5.3

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/android: 3.0.0-beta.3
  @capacitor/core: 3.0.0-beta.3
  @capacitor/cli: 3.0.0-beta.3
  @capacitor/ios: 3.0.0-beta.3
```

### Platform(s)

android

### Current Behavior

Keyboard height works, but it doesn't account for "autosuggestion" / "spellcheck" area of the keyboard (see attached image, there is button below username input that is covered by keyboard)

### Expected Behavior

Should account for this section

### Code Reproduction

N/A

### Other Technical Details

N/A

### Additional Context

<img width="438" alt="Screenshot 2021-02-26 at 12 44 12" src="https://user-images.githubusercontent.com/3154053/109290504-597c1700-7830-11eb-9d89-848c3f6e6442.png">

**Comment by lincolnthree** [comment] 2021-03-16 14:08
I can confirm this as well.

**Comment by IljaDaderko** [comment] 2021-03-22 09:54
For additional context, my keyboard config is set to

```js
    Keyboard: {
      resize: KeyboardResize.None,
      style: 'dark'
    }
```

**Comment by lincolnthree** [comment] 2021-03-29 13:18
This is also happening on iOS. Screenshot incoming.

**Comment by lincolnthree** [comment] 2021-03-29 13:44
![image](https://user-images.githubusercontent.com/362329/112845870-59f80f80-9073-11eb-8eb1-10d370556252.png)

**Comment by lincolnthree** [comment] 2021-03-29 13:59
iPhone SE: 
![image](https://user-images.githubusercontent.com/362329/112847757-65e4d100-9075-11eb-9be7-96f0ec9cde0c.png)

**Comment by lincolnthree** [comment] 2021-03-29 15:01
Actually, this may be an incorrect behavior of the ion-safe-area as applied to padding on toolbars in the footer. Still investigating.

**Comment by IljaDaderko** [comment] 2021-03-29 15:02
In my case it's related to values returned by capacitor keyboard, as I am not using ionic.

**Comment by lincolnthree** [comment] 2021-03-29 15:02
Ok, thanks. I'll create a separate issue and will comment here if I find more details about this!

**Comment by lincolnthree** [comment] 2021-03-31 13:57
Confirmed this is still happening to us as well. It's not an Ionic issue. This screen doesn't use Ionic for us either:

![image](https://user-images.githubusercontent.com/362329/113155882-7e84f080-9207-11eb-9b7d-31e945279f71.png)

**Comment by lincolnthree** [comment] 2021-03-31 14:07
Here's another screenshot showing that the height of the keyboard does get reported, but as you can see, the additional accessory bar just pushes it up by that much more:

![image](https://user-images.githubusercontent.com/362329/113157454-e4be4300-9208-11eb-8820-bf20c85fa84d.png)

**Comment by jcesarmobile** [comment] 2022-09-20 16:49
There were some changes in the keyboard plugin that might have fixed the issue.
Can you provide a sample app where the issue can be reproduced?

**Comment by Ionitron** [comment] 2022-10-06 00:05
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-10-06 00:05 UTC
Labels: platform: android, needs reply, plugin: keyboard
