### ISSUE TITLE
Problem when click an element above the map

### ISSUE THREAD

**Issue by xdelvalle** [ionic-team/capacitor-plugins#1332] opened 2022-12-15 10:43 UTC
### Plugin(s)

@capacitor/google-maps 

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Only occurs in my physical device (Samsung Galaxy S21 Ultra - Android 13 - One UI 5.0)

When a map marker is clicked, an ActionSheet appears with several options, if you click an option, this click is done two or three elements below instead on the option clicked. This behavior only occurs when the ActionSheet is deployed above the map, otherwise it works fine.

This problem also appears when we have a sidebar menu and click in options above the map.

I have tested this code in Android 10, 11 and with Android Studio emulator (API 33) and **works fine**. I could only see the problem on my physycal smartphone.

### Expected Behavior

The clicks in elements above the map must be done correctly.

### Code Reproduction

This code reproduces the problem.

https://github.com/xdelvalle/test-maps.git

### Other Technical Details

├── @capacitor/android@4.6.1
├── @capacitor/app@4.1.1
├─┬ @capacitor/cli@4.6.1
├─┬ @capacitor/core@4.6.1
├── @capacitor/geolocation@4.1.0
├─┬ @capacitor/google-maps@4.3.2
├── @capacitor/haptics@4.1.0
├── @capacitor/keyboard@4.1.0
├── @capacitor/status-bar@4.1.1

**Comment by xdelvalle** [comment] 2023-01-13 08:31
I've tested with Android 13 in a Google Pixel 7 and works fine.. In my case only appears in the Samsung S21 Ultra

**Comment by kavdev** [comment] 2023-01-26 07:52
See also https://github.com/ionic-team/capacitor-plugins/issues/1357

**Comment by jcesarmobile** [comment] 2023-05-24 15:07
I can't reproduce on 4.5.1 or newer, so I guess it was a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1357

**Closed by jcesarmobile** 2023-05-24 15:07 UTC
Labels: platform: android

**Comment by kavdev** [comment] 2023-05-24 16:20
@jcesarmobile yep, correct.
