### ISSUE TITLE
Maybe: support for picking videos?

### ISSUE THREAD

**Issue by qliqdev** [ionic-team/capacitor-plugins#1432] opened 2023-02-27 18:24 UTC
https://github.com/ionic-team/capacitor-plugins/blob/89d09cb1af52fc7263394e5365a57d475011eabe/camera/ios/Plugin/CameraPlugin.swift#L506

Why cant you make something like that?

```
        configuration.filter = .any(of: [.images, .videos]) 
```

and after return base64String of video?

**Comment by jcesarmobile** [comment] 2023-02-27 18:26
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/229

**Closed by jcesarmobile** 2023-02-27 18:26 UTC
Labels: triage
