### ISSUE TITLE
Use @capacitor/share to share img from capacitor-screenshot

### ISSUE THREAD

**Issue by nijakobius** [ionic-team/capacitor-plugins#1989] opened 2024-01-11 19:29 UTC
### Plugin
[@capacitor/share](https://github.com/ionic-team/capacitor-plugins/blob/main/share/README.md)
[capacitor-screenshot](https://github.com/ludufre/capacitor-screenshot)

### Description
`capacitor-screenshot` returns a base64 string and it doesn't seem possible to share that using `@capacitor/share`.

It MUST be possible to integrate this, because this very old plugin [cordova-plugin-x-socialsharing](https://github.com/codeborne/cordova-plugin-x-socialsharing) can do exactly that.

### Platform(s)
iOS
Android

### Preferred Solution
In the old plugin I successfully use the following code:
`window.plugins.socialsharing.shareWithOptions({files: ['data:image/png;base64,' + res.base64]});`

**Comment by jcesarmobile** [comment] 2024-01-12 14:28
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1748

**Closed by jcesarmobile** 2024-01-12 14:28 UTC
Labels: platform: android, platform: ios
