### ISSUE TITLE
issue when navigating between ion-inputs with keyboard open

### ISSUE THREAD

**Issue by sahil-infocusp** [ionic-team/capacitor-plugins#1598] opened 2023-05-18 09:55 UTC
### Plugin(s)
@capacitor/keyboard

### Capacitor Version
```
Installed Dependencies:

  @capacitor/cli: 5.0.1
  @capacitor/core: 5.0.1
  @capacitor/android: 5.0.1
  @capacitor/ios: 5.0.1
```

### Platform(s)
iOS 16.4

### Current Behavior
When we navigate from one ion-input field to other, the viewport resizes to the actual size and moves all the elements as if keyboard is not open.

### Expected Behavior
It should not resize the viewport in cases where keyboard is open

### Code Reproduction
```
<ion-app>
  <ion-split-pane contentId="main-content">
    <ion-menu contentId="main-content" type="overlay">
      <ion-content>
        <ion-list id="inbox-list">
          <ion-list-header>Inbox</ion-list-header>
          <ion-note>hi@ionicframework.com</ion-note>
          <ion-item>
            <ion-input fill="outline" label="input 1" label-placement="floating"></ion-input>
          </ion-item>
          <ion-item>
            <ion-input fill="outline" label="input 2" label-placement="floating"></ion-input>
          </ion-item>
          <ion-menu-toggle *ngFor="let p of appPages; let i = index" auto-hide="false">
            <ion-item [routerLink]="[p.url]" detail="false" lines="none" routerDirection="root" routerLinkActive="selected">
              <ion-icon [ios]="p.icon + '-outline'" [md]="p.icon + '-sharp'" aria-hidden="true" slot="start"></ion-icon>
              <ion-label>{{ p.title }}</ion-label>
            </ion-item>
          </ion-menu-toggle>
        </ion-list>
      </ion-content>

      <ion-footer>
        <ion-button>
          Footer button
        </ion-button>
      </ion-footer>
    </ion-menu>
    <ion-router-outlet id="main-content"></ion-router-outlet>
  </ion-split-pane>
</ion-app>
```

### Other Technical Details
The issue happens only if we use the capacitor/keyboard version 5.0.1 with above mentioned capacitor versions, if we use capacitor/keyboard version 4.0.1, then everything works fine.

### Additional Context
https://github.com/ionic-team/capacitor-plugins/assets/73810410/9f1a24c6-f918-4126-90cb-d64cfe41645d

**Comment by calvinwoo** [comment] 2023-05-19 21:35
Am struggling with this as well. I believe it's a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1413, which is still open unfortunately.

**Comment by jcesarmobile** [comment] 2023-05-22 09:05
yeah, it's a duplicate of #1413

**Closed by jcesarmobile** 2023-05-22 09:05 UTC
Labels: platform: ios
