### ISSUE TITLE
FileSystem Copy Directory does not work.

### ISSUE THREAD

**Issue by distante** [ionic-team/capacitor-plugins#1430] opened 2023-02-27 08:28 UTC
### Plugin(s)
FileSystem

### Capacitor Version

```

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/cli: 4.6.3
```

### Platform(s)
web (haven't test it in device yet)

### Current Behavior
Fails with `'Cannot overwrite a directory with a file'`

### Expected Behavior
Should copy the folder

### Code Reproduction
```typescript
  public toNewVersion$(: Observable<void> {
    return defer(() => {

      return this.capacitorService.fileSystem
        .mkdir({
          path: `v1/Development`,
          directory: Directory.External,
          recursive: true,
        })
        .catch((e) => {
          console.error(
            `v0v1 migration mkdir v1/Development failed`,
            e
          );
          throw e;
        });
    }).pipe(
      switchMap(() => {

        return this.capacitorService.fileSystem
          .copy({ // THIS WILL FAIL!
            from: 'v0',
            to: `v1/Development`,
            directory: Directory.External,
          })
          .catch((e) => {
            console.error(
              `v0v1 migration copy v0 to v1/Development failed`,
              e
            );
            throw e;
          });
      }),
      switchMap(() => {
        /**
         * Delete old v0 folder
         */
        return this.capacitorService.fileSystem
          .rmdir({
            path: 'v0',
            directory: Directory.External,
            recursive: true,
          })
          .catch((e) => {
            console.error('v0v1 migration rmdir v0 failed', e);
            throw e;
          });
      }),
      map(() => void 0),
    );
  }
```

### Additional Context
Unless I am missing something, this check does not make any sense:
https://github.com/ionic-team/capacitor-plugins/blob/89d09cb1af52fc7263394e5365a57d475011eabe/filesystem/src/web.ts#L528-L531

At that moment in the code, there is no check of the `from` input, so we can not be sure the `from` is a file.

If I try to copy it without creating the folder `Development` first (just `v1`), then it fails with `'Entry does not exist.'` because `stat` throws that error.

I have no idea of React but looks like in the Test App there are no Copy directory tests. https://github.com/ionic-team/capacitor-testapp/blob/main/src/pages/Filesystem.tsx

**Comment by Ionitron** [comment] 2023-02-27 09:05
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by tachibana-shin** [comment] 2023-03-12 16:11
> This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> 
> Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> 
> Thanks! Ionitron 💙

I believe this is the problem please see this pull request: https://github.com/ionic-team/capacitor-plugins/issues/1430

**Comment by distante** [comment] 2023-03-12 16:39
> > This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> > Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> > Thanks! Ionitron 💙
> 
> I believe this is the problem please see this pull request: #1430

Do you mean this https://github.com/ionic-team/capacitor-plugins/pull/1479 ?

**Comment by tachibana-shin** [comment] 2023-03-12 23:57
> > > This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.
> > > Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
> > > Thanks! Ionitron 💙
> > 
> > 
> > I believe this is the problem please see this pull request: #1430
> 
> Do you mean this #1479 ?

yes

**Comment by tachibana-shin** [comment] 2023-03-13 12:36
it's been a day and the developers aren't going to do something about the pull request and this problem

**Comment by tachibana-shin** [comment] 2023-03-14 08:29
There is no indication that this bug will be of concern as the capacitor pool is gathering for `capacitor@5.x` so those who have problems can use this patch to temporarily fix the problem:

```ts
import type { CopyOptions, CopyResult } from "@capacitor/filesystem"
import { Filesystem } from "@capacitor/filesystem"

function resolve(path: string): string {
  const posix = path.split("/").filter((item) => item !== ".")
  const newPosix: string[] = []

  posix.forEach((item) => {
    if (
      item === ".." &&
      newPosix.length > 0 &&
      newPosix[newPosix.length - 1] !== ".."
    ) {
      newPosix.pop()
    } else {
      newPosix.push(item)
    }
  })

  return newPosix.join("/")
}
function isPathParent(parent: string, children: string): boolean {
  parent = resolve(parent)
  children = resolve(children)
  const pathsA = parent.split("/")
  const pathsB = children.split("/")

  return (
    parent !== children &&
    pathsA.every((value, index) => value === pathsB[index])
  )
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
;(Filesystem as unknown as any)._copy = async function copy(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  this: any,
  options: CopyOptions,
  doRename = false
): Promise<CopyResult> {
  // eslint-disable-next-line functional/no-let
  let { toDirectory } = options
  const { to, from, directory: fromDirectory } = options

  if (!to || !from) {
    throw Error("Both to and from must be provided")
  }

  // If no "to" directory is provided, use the "from" directory
  if (!toDirectory) {
    toDirectory = fromDirectory
  }

  const fromPath = this.getPath(fromDirectory, from)
  const toPath = this.getPath(toDirectory, to)

  // Test that the "to" and "from" locations are different
  if (fromPath === toPath) {
    return {
      uri: toPath,
    }
  }

  if (isPathParent(fromPath, toPath)) {
    throw Error("To path cannot contain the from path")
  }

  // Check the state of the "to" location
  // eslint-disable-next-line functional/no-let
  let toObj
  try {
    toObj = await this.stat({
      path: to,
      directory: toDirectory,
    })
  } catch (e) {
    // To location does not exist, ensure the directory containing "to" location exists and is a directory
    const toPathComponents = to.split("/")
    toPathComponents.pop()
    const toPath = toPathComponents.join("/")

    // Check the containing directory of the "to" location exists
    if (toPathComponents.length > 0) {
      const toParentDirectory = await this.stat({
        path: toPath,
        directory: toDirectory,
      })

      if (toParentDirectory.type !== "directory") {
        throw new Error("Parent directory of the to path is a file")
      }
    }
  }

  // Cannot overwrite a directory
  if (toObj && toObj.type === "directory") {
    throw new Error("Cannot overwrite a directory with a file")
  }

  // Ensure the "from" object exists
  const fromObj = await this.stat({
    path: from,
    directory: fromDirectory,
  })

  // Set the mtime/ctime of the supplied path
  const updateTime = async (path: string, ctime: number, mtime: number) => {
    const fullPath: string = this.getPath(toDirectory, path)
    const entry = await this.dbRequest("get", [fullPath])
    entry.ctime = ctime
    entry.mtime = mtime
    await this.dbRequest("put", [entry])
  }

  const ctime = fromObj.ctime ? fromObj.ctime : Date.now()

  switch (fromObj.type) {
    // The "from" object is a file
    case "file": {
      // Read the file
      const file = await this.readFile({
        path: from,
        directory: fromDirectory,
      })

      // Optionally remove the file
      if (doRename) {
        await this.deleteFile({
          path: from,
          directory: fromDirectory,
        })
      }

      // Write the file to the new location
      const writeResult = await this.writeFile({
        path: to,
        directory: toDirectory,
        data: file.data,
      })

      // Copy the mtime/ctime of a renamed file
      if (doRename) {
        await updateTime(to, ctime, fromObj.mtime)
      }

      // Resolve promise
      return writeResult
    }
    case "directory": {
      if (toObj) {
        throw Error("Cannot move a directory over an existing object")
      }

      try {
        // Create the to directory
        await this.mkdir({
          path: to,
          directory: toDirectory,
          recursive: false,
        })

        // Copy the mtime/ctime of a renamed directory
        if (doRename) {
          await updateTime(to, ctime, fromObj.mtime)
        }
      } catch (e) {
        // ignore
      }

      // Iterate over the contents of the from location
      const contents = (
        await this.readdir({
          path: from,
          directory: fromDirectory,
        })
      ).files

      // eslint-disable-next-line functional/no-loop-statements
      for (const filename of contents) {
        // Move item from the from directory to the to directory
        await this._copy(
          {
            from: `${from}/${filename.name}`,
            to: `${to}/${filename.name}`,
            directory: fromDirectory,
            toDirectory,
          },
          doRename
        )
      }

      // Optionally remove the original from directory
      if (doRename) {
        await this.rmdir({
          path: from,
          directory: fromDirectory,
        })
      }
    }
  }
  return {
    uri: toPath,
  }
}
```

**Comment by jcesarmobile** [comment] 2023-03-15 18:36
we can't know if it's the same issue since no sample app for reproducing has been provided.
please, provide a sample app

**Comment by Ionitron** [comment] 2023-03-31 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-31 00:03 UTC
Labels: platform: web, needs reproduction, needs reply
