### ISSUE TITLE
Add ability to set dialog theme programatically or at least use app theme (on Android)

### ISSUE THREAD

**Issue by crebuh** [ionic-team/capacitor-plugins#1674] opened 2023-07-05 07:01 UTC
### Plugin

Dialog

### Description

The current implementation of the dialog plugin sets the theme of the dialog based on whether the device is in dark mode or not on iOS, while on Android the dialog always uses the light theme. It would be beneficial to have the option for developers to set the theme of the dialog regardless of the device's dark mode setting, and based on the app theme.

### Platform(s)

iOS, Android

### Additional Context

This feature would be particularly useful for apps that use a dark theme, as the current dialog style does not match well with dark backgrounds. Providing an option to set the style based on the web app's theme would improve the overall user experience and make the action sheet feel more integrated into the app.

This issues is similar to the one related to the action sheet theme: https://github.com/ionic-team/capacitor-plugins/issues/1380

**Comment by jcesarmobile** [comment] 2023-07-06 15:58
On Android I see the dialogs having the same color the device theme has, as long as the app's theme is a `DayNight` theme. If it's not, then it will match the app theme.

The plugin doesn't set any theme programmatically. 

Can you provide a sample app that reproduces the issue? 
In which device/Android version are you testing? Dark mode was officially added in Android 10, so if it's an older version with some custom vendor implementation of their own dark mode, it might not work.

**Comment by Ionitron** [comment] 2023-07-22 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-07-22 00:02 UTC
Labels: platform: android, platform: ios, needs reply
