### ISSUE TITLE
IOS app custom notification is not working

### ISSUE THREAD

**Issue by vinutatibil** [ionic-team/capacitor-plugins#1164] opened 2022-09-01 11:52 UTC
### I'm trying to customise the notification sound in IOS  and I'm using fcm to send notification. And I have placed my audio file in ios->app-->app -->sounds -->sample.wav 
And my  notification payload looks like this:
"apns": {
                "payload": {
                    "aps": {
                        "defaultSound": false ,
                        "sound": "sample.wav",
                        "color": "#202320",
                        "vibrate":true
}
                }

**Comment by Ionitron** [comment] 2022-09-01 11:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-09-17 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-17 00:03 UTC
Labels: needs reproduction, needs reply
