### ISSUE TITLE
@capacitor/dialog: avoid being dismissed after user taps on the backdrop

### ISSUE THREAD

**Issue by ricardo-muina** [ionic-team/capacitor-plugins#1379] opened 2023-01-18 23:13 UTC
## Feature Request
Add a **dismissible** property that can be managed from javascript to make the dialog dismissible or not if the user taps on the backdrop.

### Plugin
Dialog plugin

### Description
Add the ability to make the dialog (alert, confirm, or prompt) dismissible or not

### Platform(s)
Android

### Additional Context
In the DialogPlugin.java, add a dismissible property that can be passed as a parameter to the Dialog.java
 Example in DialogPlugin.java:
```
@PluginMethod
public void alert(final PluginCall call) {

       ...

        **final Boolean dismissible = call.getBoolean("dismissible", false); //Sets to true | false by default**

        ...

        Dialog.alert(activity, message, title, **dismissible**, buttonTitle, (value, didCancel, inputValue) -> call.resolve());
    }
```

Then in Dialog.java:

```
 public static void alert(
            final Context context,
            final String message,
            final String title,
            **final Boolean dismissible,**
            final String okButtonTitle,
            final Dialog.OnResultListener listener
    ) {
        final String alertOkButtonTitle = okButtonTitle == null ? "OK" : okButtonTitle;

        new Handler(Looper.getMainLooper())
                .post(
                        () -> {
                            AlertDialog.Builder builder = new AlertDialog.Builder(context);

                            ...

                            // Checking if the dialog can be dismissed or not
                            **if (!dismissible) {
                                builder.setCancelable(false);
                            }**

                            ...

                            dialog.show();
                        }
                );
    }
```

**Comment by jcesarmobile** [comment] 2023-01-19 10:07
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/630

**Closed by jcesarmobile** 2023-01-19 10:07 UTC
Labels: platform: android
