### ISSUE TITLE
LocalNotification crashes the app when opened on iOS

### ISSUE THREAD

**Issue by rohanpatil-pfizer** [ionic-team/capacitor-plugins#1377] opened 2023-01-18 16:19 UTC
### Plugin(s)

"@capacitor/local-notifications": "4.1.4",

### Capacitor Version

```
@capacitor/cli: 4.4.0
 @capacitor/core: 4.4.0
 @capacitor/android: 4.4.0
 @capacitor/ios: 4.4.0
```

### Platform(s)

iOS

### Expected Behavior

When local notification is clicked, it crashes the app in iOS

### Code Reproduction

 LocalNotifications.addListener('localNotificationActionPerformed', (result) => {
        if (result.notification.extra.goto === 'test' ) {
            console.log('Notification clicked');
        }
      });

**Comment by Ionitron** [comment] 2023-01-18 16:20
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-02-03 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-02-03 00:02 UTC
Labels: platform: ios, needs reproduction, needs reply
