### ISSUE TITLE
iPad half of the screen is black in Stage Manager mode (IOS 16)

### ISSUE THREAD

**Issue by nikage** [ionic-team/capacitor-plugins#1305] opened 2022-11-28 14:05 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@capacitor/keyboard@4.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@capacitor/keyboard/ios/Plugin/Keyboard.m b/node_modules/@capacitor/keyboard/ios/Plugin/Keyboard.m
index 8cb00bc..ef59386 100644
--- a/node_modules/@capacitor/keyboard/ios/Plugin/Keyboard.m
+++ b/node_modules/@capacitor/keyboard/ios/Plugin/Keyboard.m
@@ -127,6 +127,20 @@ NSString* UITraitsClassString;
   CGRect rect = [[notification.userInfo valueForKey:UIKeyboardFrameEndUserInfoKey] CGRectValue];
   double height = rect.size.height;
 
+  // In Stage mananer(IOS 16) on Ipad half of the screen is black with hardware keyboard
+  CGFloat screenHeight = UIScreen.mainScreen.bounds.size.height;
+  CGFloat appFrameHeight = UIApplication.sharedApplication.windows[0].frame.size.height;
+
+  if (@available(iOS 14.0, *)) {
+    BOOL isHardwareKeyboard = GCKeyboard.coalescedKeyboard != nil;
+    height = (appFrameHeight < screenHeight || isHardwareKeyboard) ? 0 : height;
+  }
+
+  // sometimes software keyboard is clipped by application frame
+  NSArray *windows = [[UIApplication sharedApplication] windows];
+  UIWindow *lastWindow = (UIWindow *) [windows lastObject];
+  lastWindow.windowLevel = lastWindow.windowLevel + 1;
+
   double duration = [[notification.userInfo valueForKey:UIKeyboardAnimationDurationUserInfoKey] doubleValue]+0.2;
   [self setKeyboardHeight:height delay:duration];
   [self resetScrollView];
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jcesarmobile** [comment] 2022-11-28 14:54
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1285

**Closed as not planned by jcesarmobile** 2022-11-28 14:54 UTC
Labels: triage
