### ISSUE TITLE
@capacitor/filesystem downloadFile() does not support headers

### ISSUE THREAD

**Issue by beruic** [ionic-team/capacitor-plugins#1778] opened 2023-09-04 10:22 UTC
### Plugin

`@capacitor/filesystem`

### Description

I am working on a project where we need to download a lot of files with authentication data in headers.

### Platform(s)

- Android

### Preferred Solution

An additional option for headers is added.

**Comment by Galileon-venta** [comment] 2023-09-05 05:23
Not true; just not documented; you can pass headers as with the HTTP Plugin:
```
...downloadFile({
                  // HTTP OPTIONS
                  url: env.baseUrl + 'documents/',
                  params: {
                    docId: document.documentID,
                  },
                  headers: {
                    Authorization: token,
                    Language: language,
                      },
                  // FILESYSTEM OPTIONS
                  path: fileName,
                  directory: Directory.Documents,
                  recursive: true,
                });
```

**Comment by Ionitron** [comment] 2023-09-05 08:09
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by beruic** [comment] 2023-09-07 08:49
So basically this issue should be that the documentation is lacking. I'm not sure how to "provide a minimal sample app that demonstrates the issue" for that :sweat_smile:

**Comment by jcesarmobile** [comment] 2023-09-08 11:07
So you have tried and they work?
The problem is the downloadFile types extend other types and the generation tool doesn't show the information of the extended type, just the specific to the downloadFile types.
But if you are using typescript you should be able to see all the possible options.

**Comment by Ionitron** [comment] 2023-09-24 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-24 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
