### ISSUE TITLE
Google maps: marker click listener - snippet attribute always empty

### ISSUE THREAD

**Issue by mandrasch** [ionic-team/capacitor-plugins#1133] opened 2022-08-17 07:44 UTC
## Bug Report

When I try to catch a click on a marker the `snippet` attribute is always empty.

```javascript
      this.map.setOnMarkerClickListener(async (marker) => {
        console.log('Marker clicked', marker);
      });
```

![image](https://user-images.githubusercontent.com/777278/185063097-501cd1bc-19e4-4af4-af34-f97c9fb45842.png)

This seems to be because of [line 319](https://github.com/ionic-team/capacitor-plugins/blob/main/google-maps/src/web.ts#L319):

```javascript
  async setMarkerListeners(
    mapId: string,
    markerId: string,
    marker: google.maps.Marker,
  ): Promise<void> {
    marker.addListener('click', () => {
      this.notifyListeners('onMarkerClick', {
        ...
        title: marker.getTitle(),
        snippet: '',
      });
    });
  }
```

### Plugin(s)
Google Maps

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
All

### Current Behavior
`marker.snippet` is empty

### Expected Behavior
`marker.snippet` provides the value which was set via

```javascript

         const newMarkerData = {
            coordinate:{
              lat: 48.3397,
              lng: 15.6784
              }
            title: 'My marker title',
            snippet: '<p>Test 123</p>',
          };
          const newMarker = await this.map.addMarker(newMarkerData);
```

### Code Reproduction
If needed, I can provide it later.

### Other Technical Details
Used with Ionic v6.

### Additional Context
Thanks for providing this great open source software!

**Comment by Ionitron** [comment] 2022-08-22 11:34
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mandrasch** [comment] 2022-08-26 09:46
> 

It is pretty obvious from the ionic source code provided above that `snippet: '',` is empty. Always. ;-) 

If you really need a reproduction of that, please let me know.

**Comment by jcesarmobile** [comment] 2022-09-01 17:00
yes, we need it

**Comment by Ionitron** [comment] 2022-09-17 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-09-17 00:03 UTC
Labels: needs reproduction, needs reply
