### ISSUE TITLE
TypeError: core.registerPlugin is not a function when running project in jest

### ISSUE THREAD

**Issue by benforsrup** [ionic-team/capacitor-plugins#466] opened 2021-06-09 13:59 UTC
### Plugin(s)

@capacitor/status-bar
@capacitor/device
@capacitor/keyboard

### Capacitor Version

```
  @capacitor/core: 3.0.0
  @capacitor/cli: 3.0.0
  @capacitor/ios: 3.0.0
  @capacitor/android: 3.0.0
```

### Platform(s)

Node

### Current Behavior

Running the project in jest, getting ``` TypeError: core.registerPlugin ``` for ```import { Device } from '@capacitor/device';```

**Comment by Ionitron** [comment] 2021-06-09 14:31
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-25 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-25 00:01 UTC
Labels: needs reply, needs reproduction
