### ISSUE TITLE
Default Capacitor Splash Screen Appears Despite Using hide() Method and Configuration Changes

### ISSUE THREAD

**Issue by Senzo13** [ionic-team/capacitor-plugins#1798] opened 2023-09-18 12:13 UTC
### Capacitor Version

> 💊   Capacitor Doctor  💊 
> 
> Latest Dependencies:
> 
>   @capacitor/cli: 5.4.0
>   @capacitor/core: 5.4.0
>   @capacitor/android: 5.4.0
>   @capacitor/ios: 5.4.0
> 
> Installed Dependencies:
> 
>   @capacitor/ios: not installed
>   @capacitor/cli: 5.3.0
>   @capacitor/core: 5.3.0
>   @capacitor/android: 5.3.0

**Project framework information :**
@ionic/angular: 7.0.0

**Documentation follow :** https://capacitorjs.com/docs/v4/apis/splash-screen
**Simulator used for the run:** PIxel 4 API 33

**What I want :**
I would like the default splash screen to absolutely never appear, because I created a page that simulates a splash screen myself

**My problem :**
The default Splash screen still appears even after touching the configuration in all directions and also using the hide() method in the app module

**this screen illustrates my point**
![image](https://github.com/ionic-team/capacitor-plugins/assets/52446531/5f4e36ef-339e-4cd6-8a62-a115a5def1f9)

**current capacitor.config.ts**
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
    appId: 'io.ionic.starter',
    appName: 'shuree',
    webDir: 'www',
    server: {
        androidScheme: 'https'
    },
    "plugins": {
        "SplashScreen": {
            "launchShowDuration": 0,
            "launchAutoHide": true,
        }
    }

};

export default config;
```

**current app-component.ts**
```

import { Component } from '@angular/core';
import { SplashScreen } from '@capacitor/splash-screen';
import { TranslateService } from '@ngx-translate/core';

@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
    styleUrls: ['app.component.scss'],
})
export class AppComponent {
    constructor(private translate: TranslateService) {
        this.translate.addLangs(['en', 'fr']);
        this.translate.setDefaultLang('fr');
        SplashScreen.hide();
    }

    ngOnInit() {
        SplashScreen.hide();
    }
}

```

**Comment by Ionitron** [comment] 2023-09-18 12:22
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-10-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-10-04 00:03 UTC
Labels: needs reproduction, needs reply
