### ISSUE TITLE
Browser does not open on first try

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/capacitor-plugins#472] opened 2021-06-12 11:01 UTC
### Plugin(s)
capacitor/browser

### Capacitor Version

```
Installed Dependencies:
  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
```

### Platform(s)
iOS (Safari)

### Current Behavior
Clicking on a link in a browser safari does not open the url in a new tab. It seems that it blocks as if it's a popup window. On second selection it shows the new tab.

### Expected Behavior
Show the new tab

### Code Reproduction
this.openBrowser('https://github.com/ionic-team');

async openBrowser(url: string) {
    const options: OpenOptions = {
      url: url,
      //presentationStyle: 'popover' // either way it's the same issue
    };
    await Browser.open(options);
}

**Comment by Ionitron** [comment] 2021-06-14 08:17
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-06-30 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-06-30 00:01 UTC
Labels: needs reply, needs reproduction, platform: ios
