### ISSUE TITLE
Push Notification events not working properly in android

### ISSUE THREAD

**Issue by izeryab** [ionic-team/capacitor-plugins#1026] opened 2022-06-07 05:42 UTC
### Plugin(s)
capacitor-push-notificarion

### Capacitor Version

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

### Platform(s)
android

### Current Behavior
PushNotification actionPerformed event is not working when app is in foreground and pushNotification received event didn't work when app is in background this is only happening in android

### Expected Behavior
Push notification action performed and push notification received should work when app is in foreground or background like in ios

### Code

```
capacitorPushNotifications.PushNotifications.addListener(
      "registration",
      (token: Token) => {
        this.deviceToken = token.value;
        console.log("Push registration success, token: " + token.value);
      }
    );
    capacitorPushNotifications.PushNotifications.addListener(
      "registrationError",
      (error: any) => {
        console.log("Error on registration: " + JSON.stringify(error));
      }
    );
    capacitorPushNotifications.PushNotifications.addListener(
      "pushNotificationReceived",
      (notification: PushNotificationSchema) => {
        console.log("Push received: " + JSON.stringify(notification));
      }
    );
    capacitorPushNotifications.PushNotifications.addListener(
      "pushNotificationActionPerformed",
      (notification: ActionPerformed) => {
        console.log("Push action performed: " + JSON.stringify(notification));
      }
    );

```

**Comment by Ionitron** [comment] 2022-06-07 08:17
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by joe-pritchard** [comment] 2022-06-14 07:18
I had this problem while using the push notifications plugin in conjunction with `@capacitor-community/fcm`. I fixed it by adding the following to my `AndroidManifest.xml`:

```
<intent-filter>
    <action android:name="FCM_PLUGIN_ACTIVITY" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

**Comment by jcesarmobile** [comment] 2022-06-28 11:18
closing since the reporter didn't provide a sample app

**Closed by jcesarmobile** 2022-06-28 11:18 UTC
Labels: platform: android, needs reproduction
