### ISSUE TITLE
Filesystem: writing file to Directory.Data creates it in Directory.Cache 

### ISSUE THREAD

**Issue by Juarrow** [ionic-team/capacitor-plugins#511] opened 2021-07-03 20:39 UTC
### Plugin(s)

- Filesystem

### Capacitor Version

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.0.2
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.0.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.1
  @capacitor/android: 3.0.2
  @capacitor/core: 3.0.1

[success] Android looking great! 👌
```

### Platform(s)

- Android

### Current Behavior

When doing the following
````
const fileName = new Date().getTime() + '.jpeg';
    const savedFile = await Filesystem.writeFile({
      data: base64Data,
      path: fileName,
      directory: Directory.Data
    });
````
... and then trying to read back the file doing
````
const readFile = await Filesystem.readFile({
          path: filename,
          directory: Directory.Data
        });
````
... the file is not found.

When checking the files using _Device File Explorer_ i can see that the files are being placed in the cache directory and i can enumerate them using `readdir()` targeting `Directory.Cache` instead of `Directory.Data`.

### Expected Behavior

Files written to `Directory.Data` should be accessible via `Directory.Data`

### Other Technical Details

Android 10

**Comment by jcesarmobile** [comment] 2021-07-06 14:18
I've tried and I can't reproduce, can you provide a sample app?

**Comment by Ionitron** [comment] 2021-07-22 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-07-22 00:01 UTC
Labels: needs reply, platform: android
