### ISSUE TITLE
pushNotificationActionPerformed Event is not firing on iOS

### ISSUE THREAD

**Issue by kpatfln** [ionic-team/capacitor-plugins#922] opened 2022-04-13 04:47 UTC
Bug Report
----
### Plugin(s)
push-notifications
### Capacitor Version
3.4.1
### Platform(s)
iOS
### Current Behavior
When tapping a push notification on iOS from Notification Centre, `pushNotificationActionPerformed` event is not being fired.

Push notifications are still arriving as expected, however.
### Expected Behavior
When tapping a notification on iOS from Notification Centre, `pushNotificationActionPerformed` event should be fired.
### Code Reproduction
Follow [this](https://capacitorjs.com/docs/apis/push-notifications) to set up on webapp side.
Follow [this](https://medium.com/nerd-for-tech/how-to-solve-capacitor-error-no-such-module-firebaseinstanceid-9c142933b589) to set up on iOS Swift side.

**Comment by Ionitron** [comment] 2022-04-18 09:38
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-04 00:03 UTC
Labels: platform: ios, needs reproduction, needs reply
