### ISSUE TITLE
@capacitor/text-zoom: Decimal formatting from TextZoom.getPreferred()

### ISSUE THREAD

**Issue by Toxiapo** [ionic-team/capacitor-plugins#1826] opened 2023-10-03 22:47 UTC
## Feature Request

Consistent number formatting for `TextZoom.get()` and `TextZoom.getPreferred()` function

### Plugin
"@capacitor/text-zoom": "^5.0.6"

### Description

While using the plugin, I noticed that the returned value of the `TextZoom.get()` function is rounded to two decimal places while `TextZoom.getPreferred()` doesn't have this constraint. I am curious if there's a reason why we don't do that and if it's desirable to add the format logic to the getPreferred function.

This is very subtle as one could just create a helper function for it so it's just nice to have.

![Screenshot 2023-10-03 at 5 43 48 PM](https://github.com/ionic-team/capacitor-plugins/assets/14434233/8648f66f-6723-4770-a131-1be983af2664)

### Platform(s)
 iOS

**Comment by Ionitron** [comment] 2023-10-09 16:13
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-10-25 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-10-25 00:02 UTC
Labels: platform: ios, needs reproduction
