### ISSUE TITLE
Keyboard plugin resizes webview on build for Apple Silicon Macs (Mac - Designed for iPad)

### ISSUE THREAD

**Issue by torgnywalin** [ionic-team/capacitor-plugins#1410] opened 2023-02-07 16:51 UTC
### Plugin(s)
 - Keyboard 

### Capacitor Version

```
I did not build the project myself, so I dont have access to this right now.
If this is not easy to reproduce I can find out what it the output on the mac this was built on.
```

### Platform(s)
 - Mac OS

### Current Behavior
When selecting to build an app with `Mac (Designed for iPad)` av an option in **Supported Destinations** in xCode. 
The app when installed on Mac OS will try to resize webview when keyboard should be visible, but there is no keyboard. So Window looks broken. It disapears again when clicking outside of input controller (when keyboard should hide).

I have tried all the resizeModes, and all except `none` will make a large block of the window usless.
`none` will still hide the tabstrip, but does not take up as much space as the other options.

Screenshot
![Skjermbilde 2023-02-07 kl  17 42 18](https://user-images.githubusercontent.com/5191303/217307984-e6149db6-607d-4cb5-bfbb-1c3eb02e1d14.png)

If i use resizeMode `none` only the lighter grey area at the bottom will pop up.

### Expected Behavior
I would expect the Keyboard to not do anything with the webview if keyboard is not available.

### Code Reproduction
Im sorry, but I dont have a reproduction repository.
It should be pretty easy to test by taking an existing app and building it for Mac (Designed for iPad) selected in Xcode.
Select an input component where keyboard would normally pop up.

**Comment by Ionitron** [comment] 2023-02-22 18:47
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-03-10 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-03-10 00:03 UTC
Labels: needs reproduction, needs reply
