### ISSUE TITLE
Time Sensitive Local Notifications on iOS

### ISSUE THREAD

**Issue by nkalupahana** [ionic-team/capacitor-plugins#1367] opened 2023-01-06 20:48 UTC
### Plugin
Local Notifications

### Description
iOS Local Notifications can be marked as Time Sensitive, which is useful for many apps. It would be nice to be able to have this functionality in the Local Notifications plugin.

### Platform(s)
- iOS

**Comment by jcesarmobile** [comment] 2023-01-09 11:21
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/659

**Closed by jcesarmobile** 2023-01-09 11:21 UTC
Labels: platform: ios
