### ISSUE TITLE
Bug - Called two listener when I called one.

### ISSUE THREAD

**Issue by francolondra** [ionic-team/capacitor-plugins#1262] opened 2022-11-07 00:05 UTC
### Plugin(s)
@capacitor/google-map

### Capacitor Version
4.2.1

### Platform(s)
Android

### Current Behavior
I called this listener setOnMarkerClickListener when I push in a marker in the map and in this moment also it called setOnBoundsChangedListener automatic

### Expected Behavior
only it should called setOnMarkerClickListener and only this.

**Comment by Ionitron** [comment] 2022-11-07 08:39
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-11-23 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-23 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
