### ISSUE TITLE
Map disappears with dark mode on android

### ISSUE THREAD

**Issue by Anokino** [ionic-team/capacitor-plugins#1788] opened 2023-09-08 22:01 UTC
## Bug Report

Hello, 
My code that used to work on both web and android doesn't work anymore on android. Possibly caused by an event but i'm not sure of this.

### Plugin(s) concerned
`@capacitor/google-maps` latest

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/cli: 5.3.0

[success] Android looking great! 👌
```

### Platform(s)
`Ionic v7 on android` and web but it's not relevant here

### Error :
So my map is not loading on android, or at least not displaying, although it was working a little while ago and I don't think I've changed anything specific.
In the android debug console, I have a resize event that produces an error. I don't know if this is related, or if it's precisely because the map doesn't work that it's displayed here.: 

```ts
native CapacitorGoogleMaps.onResize (#6561217)
{callbackId: '6561217', pluginId: 'CapacitorGoogleMaps', methodName: 'onResize', options: {…}}
tab2꞉5:32:306
callbackId:
'6561217'
methodName:
'onResize'
options:
{id: 'my-cool-map', mapBounds: {…}}
pluginId:
'CapacitorGoogleMaps'
[[Prototype]]:
Object
```

and the error : 

```ts
result CapacitorGoogleMaps.onResize (#6561217)
{message: 'Map not found for provided id.', code: '2'}
tab2꞉5:32:281
Unhandled Promise rejection: Map not found for provided id. ; Zone: <root> ; Task: Promise.then ; Value: Error: Map not found for provided id.
    at returnResult (:857:32)
    at win.androidBridge.onmessage (http://192.168.10.20:8100/tabs/tab2:832:21) {code: '2', data: undefined, stack: 'Error: Map not found for provided id.
    at … (http://192.168.10.20:8100/tabs/tab2:832:21)', message: 'Map not found for provided id.'} Error: Map not found for provided id.
    at returnResult (:857:32)
    at win.androidBridge.onmessage (:832:21)
```

### Expected Behavior
Anyway, the page is displayed, with the map location but not the map displayed. 
**On web :** 
![image](https://github.com/capacitor-community/google-maps/assets/45012641/3e9d7e39-9654-4bf9-bef9-d29af17bf5d4)

### Current Behavior 
**On Android :** 
![image](https://github.com/capacitor-community/google-maps/assets/45012641/fc564d05-b50c-4178-b0dd-842a8be778e9)

I'm using Ionic 7 and the latest version of the plugin, my APIKey is also in the AndroidManifest, and i have restriction on my ApiKey. Here is the fragment of code of the map page : 
```ts
async createMap() {
    const apiKey = "_...removed for evident reason..._";
    const mapRef = document.getElementById('map')!

    this.newMap = await GoogleMap.create({
      id: 'my-cool-map',
      element: mapRef,
      apiKey: apiKey,
      config: {
        center: {
          lat: 46.513605,
          lng: -1.7696065,
        },
        zoom: 12.30,
      }
    });
```

**Comment by Anokino** [comment] 2023-09-09 02:06
Well, I was looking everywhere but where I should since the map is created as it should be, it's only a matter of dark mode, where the map disappears (but still reacts since I have events when I slide my finger on it). 

Nothing to do with the id, which obviously doesn't prevent the map from working, not to mention the issue https://github.com/ionic-team/capacitor-plugins/issues/1708

Do I need to open another issue for this? Because I can't figure out what would possibly cause this.

**Comment by Ionitron** [comment] 2023-09-11 13:31
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Marceldts** [comment] 2023-09-13 07:42
I had the same problem some days ago when changing the page's style. It disappeared with any style change. I had to destroy and re-create the map every time

**Comment by jcesarmobile** [comment] 2023-09-25 13:11
closing since no sample app was provided

**Closed by jcesarmobile** 2023-09-25 13:11 UTC
Labels: platform: android, needs reproduction
