### ISSUE TITLE
Application is crashed when take picture from Camera 

### ISSUE THREAD

**Issue by mobiliseapplabllp** [ionic-team/capacitor-plugins#1343] opened 2022-12-26 11:03 UTC
Sometimes Android App will crash when take picture from camera

### Plugin(s)
"@capacitor/camera": "^4.1.4",

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/core: 4.5.0

[success] Android looking great! 👌

### Platform(s)
Android

### Current Behavior
when take picture from camera application will crash sometimes. sometimes plugin work fine

### Expected Behavior
photo take successfully and upload to server

### Code Reproduction
 async openCamera(imageno: any) {
    const takePicture = async () => {
      const image = await Camera.getPhoto({
        quality: 50,
        allowEditing: false,
        resultType: CameraResultType.Uri,
      });
      this.readImg(image, imageno)
    };
    takePicture();
  }

  async readImg(photo: any, imageno: any) {
    let random = Date.now() + Math.floor(Math.random() * 90000) + 10000 + '.jpg'
    const response = await fetch(photo.webPath);
    const blob = await response.blob();
    console.log(blob);
    const formData = new FormData();
    formData.append('photo', blob, random);
    formData.append('barcodeno', this.addAsset.value.barcodeno);
    this.uploadImg(formData, imageno)
  }

### Other Technical Details
Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.8
   @angular-devkit/build-angular : 15.0.1
   @angular-devkit/schematics    : 15.0.1
   @angular/cli                  : 15.0.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.5.0
   @capacitor/android : 4.5.0
   @capacitor/core    : 4.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.16.0 (/Users/apple/.nvm/versions/node/v16.16.0/bin/node)
   npm    : 8.11.0
   OS     : macOS Monterey

### Issue with this system
"Redmi Note 9 Pro" issue with this Mobile

**Comment by Ionitron** [comment] 2023-01-03 20:58
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-19 00:35
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-19 00:35 UTC
Labels: platform: android, needs reproduction, needs reply
