### ISSUE TITLE
Share plugin incompatible with Android 14

### ISSUE THREAD

**Issue by shanselm-ergon** [ionic-team/capacitor-plugins#1823] opened 2023-10-03 06:16 UTC
## Bug Report
Our app crashes because of the usage of the Share plugin on an Android 14 device. The Share plugin (and may be also others) use a Receiver, which requires flags to be passed to be compliant with Android 14. 
https://github.com/ionic-team/capacitor-plugins/blob/main/share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java#L44
Newly, we have to specify, if the receiver is visible for other apps or not (see the link in technical details). If you don't specify the flags, the app crashes with the following error. 

```
FATAL EXCEPTION: main
  Process: a.b.c, PID: 1234
  java.lang.RuntimeException: Unable to start activity ComponentInfo{a.b.c/a.b.c.MainActivity}: java.lang.SecurityException: a.b.c: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
```

Furthermore in the Share plugin, there is a pending intent flag, that can not be used anymore with Android 14:
https://github.com/ionic-team/capacitor-plugins/blob/main/share/android/src/main/java/com/capacitorjs/plugins/share/SharePlugin.java#L117
A mutable pending intent is not allowed, instead we can use an immutable one.

Please take a look at the two problems I mentioned above and qualify them, it may also concern other plugins. I my case it was a show stopper.

Thank you

### Plugin(s)
Share (5.0.6)

### Capacitor Version
5.0.6

### Platform(s)
Android 14

### Current Behavior
App crashes, because code is not conform with Android 14.

### Expected Behavior
No crash.

### Code Reproduction
Use the Share plugin in an app and launch it on an Android 14 device. The Plugin encounters an error, because the code is not compliant with Android 14. 

### Other Technical Details
https://developer.android.com/about/versions/14/behavior-changes-14

### Additional Context
https://developer.android.com/about/versions/13/features#runtime-receivers

**Comment by Ionitron** [comment] 2023-10-03 07:40
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by shanselm-ergon** [comment] 2023-10-10 06:24
Hi there
If you use Android 14 as target platform, you will directly see the problem in Android Studio (it will even tell you that there is a problem). The code lines I pointed to should be enough information to fix this problem, I won't create a sample app for it.

**Comment by jcesarmobile** [comment] 2023-10-19 11:21
Targeting SDK 34 is not supported in Capacitor 5 and won't be supported in Capacitor 5 because is a breaking change.

We are already working in Capacitor 6 with SDK 34 support and we will address all SDK 34 related issues like this one.
Share plugin works fine on Android 14 if you keep targeting SDK 33.

**Closed by jcesarmobile** 2023-10-19 11:21 UTC
Labels: platform: android, needs reproduction
