### ISSUE TITLE
[@capacitor/share] It is impossible to share a file

### ISSUE THREAD

**Issue by Brozzor** [ionic-team/capacitor-plugins#1653] opened 2023-06-09 12:13 UTC
### Plugin(s)
@capacitor/share 5.0.2

### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Output from console after push my export button
```
Error: Uncaught (in promise): TypeError: Type error
share@[native code]
@capacitor://dev.oleko.local/node_modules_capacitor_share_dist_esm_web_js.js:41:28
asyncGeneratorStep@capacitor://dev.oleko.local/vendor.js:263320:24
_next@capacitor://dev.oleko.local/vendor.js:263342:27
@capacitor://dev.oleko.local/vendor.js:263349:12
ZoneAwarePromise@capacitor://dev.oleko.local/polyfills.js:1770:29
@capacitor://dev.oleko.local/vendor.js:263338:23
share@[native code]
@capacitor://dev.oleko.local/vendor.js:292:25
onInvoke@capacitor://dev.oleko.local/vendor.js:146601:31
run@capacitor://dev.oleko.local/polyfills.js:239:41
@capacitor://dev.oleko.local/polyfills.js:1583:31
onInvokeTask@capacitor://dev.oleko.local/vendor.js:146589:35
runTask@capacitor://dev.oleko.local/polyfills.js:292:47
drainMicroTaskQueue@capacitor://dev.oleko.local/polyfills.js:740:30
```

### Platform(s)
IOS only

### Current Behavior

After clicking on my button to share my csv, nothing happens and an error appears in the console.

### Code Reproduction
```
async export() {

     const csvData = 'salade,tomate,oignons';
     const fileName = 'export_' + new Date().getTime() + '.csv';
    
    const filewrite = await Filesystem.writeFile({
      path: fileName,
      data: csvData,
      directory: Directory.Cache,
      encoding: Encoding.UTF8
    });

    Share.share({
      title: 'Save or Share File',
      url: filewrite.uri
    });
}
```

**Comment by Ionitron** [comment] 2023-06-12 09:50
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-06-28 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-28 00:03 UTC
Labels: platform: ios, needs reproduction
