### ISSUE TITLE
browserFinished listener invocation is behaving differently in iOS and Android

### ISSUE THREAD

**Issue by AUK4GIT** [ionic-team/capacitor-plugins#1816] opened 2023-09-27 12:38 UTC
### Plugin(s)

Browser

### Capacitor Version

4.1.1

```
Browser.addListener("browserFinished", () => {});
```

### Platform(s)

Android, iOS

### Current Behavior

In Android - The browserFinished  listener is fired when the browser close function is called and when the user explicitly closes using the close button.

In iOS - The browserFinished  listener is fired only when the user explicitly closes using the Done button.

### Expected Behavior

Should behave the same in both platforms

### Code Reproduction

` 
Browser.addListener("browserFinished", () => {});
`

**Comment by Ionitron** [comment] 2023-09-27 13:18
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-10-13 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-10-13 00:02 UTC
Labels: platform: android, platform: ios, needs reproduction
