### ISSUE TITLE
Android 31 Geolocation.getCurrentPosition missing permissions

### ISSUE THREAD

**Issue by tigohenryschultz** [ionic-team/capacitor-plugins#1363] opened 2023-01-05 19:51 UTC
### Plugin(s)
@capacitor/geolocation

### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/android: 4.6.1
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1

[success] Android looking great! �
[error] Xcode is not installed
```

### Platform(s)
Android 12/31

### Current Behavior
Throws console log

### Expected Behavior
Prompt location permissions on device

### Other Technical Details
```
 async getCurrentPosition() {
      const options = {
        enableHighAccuracy: false,
        timeout: 5000,
        maximumAge: 0
      };

      const coordinates = Geolocation.getCurrentPosition(options);
      console.log('Current position:', coordinates);
    },

```

### Additional Context
```
VM3:747 Uncaught (in promise) Error: Missing the following permissions in AndroidManifest.xml:
android.permission.ACCESS_COARSE_LOCATION

    at returnResult (VM3:747:32)
    at win.androidBridge.onmessage (VM3:722:21)
returnResult @ VM3:747
win.androidBridge.onmessage @ VM3:722
```

We've tried multiple combinations  of Manifests, nothing works.

Manifest:
```

<?xml version='1.0' encoding='utf-8'?>
<manifest package="com.tigoenergy.smart" xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:networkSecurityConfig="@xml/network_security_config" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme" android:usesCleartextTraffic="true">
        <meta-data android:name="asset_statements" android:resource="@string/asset_statements" />
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:exported="true" android:label="@string/title_activity_main" android:launchMode="singleTask" android:name="com.tigoenergy.smart.MainActivity" android:theme="@style/AppTheme.NoActionBarLaunch">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
                <data android:host="ei.tigoenergy.com" android:scheme="http" />
                <data android:host="ei.tigoenergy.com" android:scheme="https" />
                <data android:scheme="https" />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="androidx.core.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
    </application>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH" />
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
</manifest>

```

We've tried other calls and they have similar problems, they throw DENIED_ALWAYS:

```
async requestGeoPermissions() {
      await Geolocation.requestPermissions()
        .then((result) => {
          this.$log.debug('TgPermissionsTest:requestGeoPermissions:success:', result);
        })
        .catch((error) => {
          this.$log.debug('TgPermissionsTest:requestGeoPermissions:success:', error);
        })
    },
```

**Comment by tigohenryschultz** [comment] 2023-01-05 20:15
What is odd is I see in Android Studio logs:
```

2023-01-05 12:13:13.365 9838-9838/com.tigoenergy.smart V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 56640974, pluginId: Geolocation, methodName: getCurrentPosition
2023-01-05 12:13:13.365 9838-9838/com.tigoenergy.smart V/Capacitor: callback: 56640974, pluginId: Geolocation, methodName: getCurrentPosition, methodData: {"enableHighAccuracy":true,"timeout":5000,"maximumAge":0}
2023-01-05 12:13:13.377 9838-9838/com.tigoenergy.smart V/Capacitor/AppPlugin: Notifying listeners for event pause
2023-01-05 12:13:13.377 9838-9838/com.tigoenergy.smart D/Capacitor/AppPlugin: No listeners found for event pause
2023-01-05 12:13:13.378 9838-9838/com.tigoenergy.smart D/Capacitor: App paused
2023-01-05 12:13:13.422 9838-9838/com.tigoenergy.smart D/Capacitor: Unable to find a Capacitor plugin to handle permission requestCode, trying Cordova plugins 450497393
2023-01-05 12:13:13.426 9838-9838/com.tigoenergy.smart D/Capacitor: Sending plugin error: {"save":false,"callbackId":"56640974","pluginId":"Geolocation","methodName":"getCurrentPosition","success":false,"error":{"message":"Missing the following permissions in AndroidManifest.xml:\nandroid.permission.ACCESS_FINE_LOCATION\nandroid.permission.ACCESS_COARSE_LOCATION\n"}}

```

**Comment by tigohenryschultz** [comment] 2023-01-06 19:29
I reproduced the issue in the Ionic Start Vue project by installing all these other capacitoir/cordova plugins:

 ```
"dependencies": {
    "@capacitor/android": "^4.6.1",
    "@capacitor/app": "4.1.1",
    "@capacitor/core": "4.6.1",
    "@capacitor/geolocation": "^4.1.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/camera": "^4.1.4",
    "@capacitor/network": "^4.1.0",
    "@capacitor/keyboard": "4.1.0",
    "@capacitor/status-bar": "4.1.1",
    "@ionic/vue": "^6.0.0",
    "@ionic/vue-router": "^6.0.0",
    "core-js": "^3.6.5",
    "ionicons": "^6.0.3",
    "vue": "^3.2.21",
    "vue-router": "^4.0.12",
    "es6-promise-plugin": "^4.2.2",
    "@ionic-native/android-permissions": "^5.36.0",
    "@ionic-native/barcode-scanner": "^5.36.0",
    "@ionic-native/bluetooth-le": "^5.36.0",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/file": "^5.36.0",
    "@ionic-native/globalization": "^5.36.0",
    "@ionic-native/http": "^5.36.0",
    "@ionic-native/network": "^5.36.0",
    "@ionic-native/screen-orientation": "^5.36.0",
    "@ionic-native/wifi-wizard-2": "^5.36.0",
    "cordova-plugin-advanced-http": "^3.2.2",
    "cordova-plugin-android-permissions": "^1.1.3",
    "cordova-plugin-ble-central": "^1.6.1",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-wifiwizard2": "^3.1.1"
  },
```

Using a combination of these breaks @capacitor/geolocation

**Comment by Ionitron** [comment] 2023-01-09 10:06
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-25 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-25 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
