### ISSUE TITLE
@capacitor/camera Webcam stays on when pressing escape key

### ISSUE THREAD

**Issue by 108174** [ionic-team/capacitor-plugins#915] opened 2022-04-04 21:45 UTC
### Plugin(s)
```"@capacitor/camera": "^1.3.1"```

### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 3.4.3    
  @capacitor/core: 3.4.3   
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3    

Installed Dependencies:    

  @capacitor/cli: 3.2.2    
  @capacitor/core: 3.2.2   
  @capacitor/ios: 3.2.2    
  @capacitor/android: 3.2.0
```

### Platform(s)
Desktop / Web

### Current Behavior

When using the Camera modal, if you press the escape key to close the modal, thus not taking a picture, the webcam/camera remains active until the page is refreshed

### Code Reproduction

```
Camera.getPhoto({
      quality: quality,
      resultType: CameraResultType.Base64,
      source: CameraSource.Prompt
})

// Use picture, And press escape when the modal pops up.
```

### Other Technical Details

Used inside an angular project in combination with ionic.

### Additional Context

This error is logged when closing the modal the regular way.

```Error: User cancelled photos app
    at HostElement.<anonymous> (web.js:54:32)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1387:1)
    at HostElement.<anonymous> (asyncToGenerator.js:21:1)
    at HostElement.<anonymous> (web.js:51:17)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25505:1)```

**Comment by jcesarmobile** [comment] 2022-04-05 17:18
I can't reproduce in our [test app ](https://github.com/ionic-team/capacitor-testapp)

Can you provide a sample app where it can be reproduced?

**Comment by Ionitron** [comment] 2022-04-05 17:18
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-04-21 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-21 00:03 UTC
Labels: platform: web, needs reproduction, needs reply
