### ISSUE TITLE
Filesystem downloadFile only downloads a part of the file.

### ISSUE THREAD

**Issue by TheRealPingWin** [ionic-team/capacitor-plugins#1714] opened 2023-08-03 07:34 UTC
### Plugin(s)

capacitor/filesystem : 5.0.4

### Capacitor Version
5.2.2

### Platform(s)

IOS

### Current Behavior

Using the Filesystems downloadFile function runs successfully, however the downloaded file is just a part of the whole file.
In my case a 477Mb video and the downloaded file is only 175 bytes

### Expected Behavior

It should download the whole file.

### Code Reproduction

create a new angular app with 15.2.0 version
install and add latest capacitor
add the needed code into the info.plist file
try downloading file with Filesystem
Filesystem.downloadFile({url: 'paste a url here', path: 'give a location where to save  the file'})
Go into the device's file system and check the downloaded file.

**Comment by TheRealPingWin** [comment] 2023-08-03 08:17
I found another issue, that explains my problem, if the url doesn't exist, it still runs without error and downloads a garbage file.
[](https://github.com/ionic-team/capacitor-plugins/issues/1698)

**Comment by jcesarmobile** [comment] 2023-08-03 09:33
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1698

**Closed by jcesarmobile** 2023-08-03 09:33 UTC
Labels: platform: ios
