### ISSUE TITLE
capacitor/push-notifications: removes old push notification with new one in notification center on Android devices.

### ISSUE THREAD

**Issue by P-Owotade** [ionic-team/capacitor-plugins#2111] opened 2024-05-23 17:36 UTC
### Plugin(s)

capacitor/push-notifications (6.0.0)

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 5.2.3
  @capacitor/core: 4.6.2

```

### Platform(s)

Android

### Current Behavior

When new pushes are received, old pushes in the notification center gets removed instead of stacking occurring.

### Expected Behavior

Push notifications stack on top of each other.

**Comment by Ionitron** [comment] 2024-06-07 15:25
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-06-23 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-06-23 00:03 UTC
Labels: platform: android, needs reproduction
