### ISSUE TITLE
Local Notifications error tests

### ISSUE THREAD

**Issue by Naerian** [ionic-team/capacitor-plugins#1075] opened 2022-07-01 23:13 UTC
## Bug Report
Hi everyone, 

I have installed **@capacitor/local-notifications** with **Capacitor v3.6.0** and I have imported that plugin: 
`import { LocalNotifications } from '@capacitor/local-notifications';`. 

I can use this plugin without problems in my project, but when i try to run the test, I get this error: 

```
Error: node_modules/@capacitor/local-notifications/dist/esm/definitions.d.ts:1:15 - error TS2305: Module '"@capacitor/core"' has no exported member 'PermissionState'.

1 import type { PermissionState, PluginListenerHandle } from '@capacitor/core';
```

I don't know what can I do...

### Plugin(s)
@capacitor/local-notifications **v1.1.0**

### Expected Behavior
Test will be passed

### Code Reproduction
`ng test`
```
Error: node_modules/@capacitor/local-notifications/dist/esm/definitions.d.ts:1:15 - error TS2305: Module '"@capacitor/core"' has no exported member 'PermissionState'.

1 import type { PermissionState, PluginListenerHandle } from '@capacitor/core';
```

### Capacitor Version
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

### Platform(s)
Windows

**Comment by Ionitron** [comment] 2022-07-03 10:17
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Naerian** [comment] 2022-07-03 20:38
I changed in: `...\node_modules\@capacitor\local-notifications\dist\esm\definitions.d.ts`

`import type { PermissionState, PluginListenerHandle } from "@capacitor/core/types/definitions";`

Instead of: 

`import type { PermissionState, PluginListenerHandle } from '@capacitor/core';`

And the tests run without problem... What is the problem?

**Comment by Ionitron** [comment] 2022-07-05 07:18
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-07-21 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-21 00:03 UTC
Labels: needs reproduction, needs reply
