### ISSUE TITLE
Android Local-Notifications Schedule Timestamp to created time fixed

### ISSUE THREAD

**Issue by moonlitangel** [ionic-team/capacitor-plugins#1091] opened 2022-07-25 02:39 UTC
### Plugin(s)
@capacitor/local-notifications: 1.1.0

### Capacitor Version

```
Latest Dependencies:       

  @capacitor/cli: 3.6.0    
  @capacitor/core: 3.6.0   
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
```

### Platform(s)
Android

### Current Behavior
The notification timestamp display on the Android is fixed to the notification generation time.
![photo_2022-07-25_11-17-12](https://user-images.githubusercontent.com/20410385/180680667-12a5a72d-d0bb-419b-ae3c-3ef6720ab543.jpg)

When generating a repetitive notification, the first generated notification is used repeatedly.

### Expected Behavior

1. `setShowWhen()` Add Schedule Option(On, Every, etc..).
2. Generate a new notification from `TimedNotificationPublisher.java > rescheduleNotificationIfNeeded` .

### Code Reproduction

[https://github.com/moonlitangel/bug-notification](https://github.com/moonlitangel/bug-notification)

**Comment by jcesarmobile** [comment] 2022-07-25 14:50
Thanks for the issue, but it's a duplicate of https://github.com/ionic-team/capacitor-plugins/issues/433

**Closed by jcesarmobile** 2022-07-25 14:50 UTC
Labels: platform: android
