### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: "Storage" plugin is not implemented on android

### ISSUE THREAD

**Issue by krunalsk007** [ionic-team/capacitor-plugins#633] opened 2021-09-25 06:12 UTC
### Plugin(s)
npm install @capacitor/storage
npx cap sync

### Capacitor Version
3.2.3

```
PASTE OUTPUT HERE
vendor.js:45839 ERROR Error: Uncaught (in promise): Error: "Storage" plugin is not implemented on android
Error: "Storage" plugin is not implemented on android
    at createPluginMethod (default-node_modules_codetrix-studio_capacitor-google-auth_dist_esm_index_js.js:210)
    at default-node_modules_codetrix-studio_capacitor-google-auth_dist_esm_index_js.js:217
    at ZoneDelegate.invoke (polyfills.js:436)
    at Object.onInvoke (vendor.js:68065)
    at ZoneDelegate.invoke (polyfills.js:435)
    at Zone.run (polyfills.js:196)
    at polyfills.js:1354
    at ZoneDelegate.invokeTask (polyfills.js:470)
    at Object.onInvokeTask (vendor.js:68052)
    at ZoneDelegate.invokeTask (polyfills.js:469)
    at resolvePromise (polyfills.js:1291)
    at polyfills.js:1198
    at rejected (vendor.js:104299)
    at ZoneDelegate.invoke (polyfills.js:436)
    at Object.onInvoke (vendor.js:68065)
    at ZoneDelegate.invoke (polyfills.js:435)
    at Zone.run (polyfills.js:196)
    at polyfills.js:1354
    at ZoneDelegate.invokeTask (polyfills.js:470)
    at Object.onInvokeTask (vendor.js:68052)
```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/cli: 3.2.3
  @capacitor/ios: 3.2.3

[success] Android looking great! 👌
### Platform(s)

Android

### Current Behavior
**I am getting run time error of storage  plugin.**

### Additional Context
i follow all this step which is written in [**this** ](https://capacitorjs.com/docs/apis/storage#configure) official doc.

**Comment by Ionitron** [comment] 2021-09-27 07:57
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-13 00:01
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-10-13 00:01 UTC
Labels: platform: android, needs reproduction, needs reply
