### ISSUE TITLE
Custom splash screen turns to default android splash and stays on indefinitely

### ISSUE THREAD

**Issue by Aliaksandr-Kukhlevsky** [ionic-team/capacitor-plugins#1349] opened 2022-12-29 14:22 UTC
### Plugin(s)

@capacitor/splash-screen@4.1.2

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.3.0
  @capacitor/cli: 4.3.0
  @capacitor/android: 4.3.0
```

### Platform(s)

Android 8.0.0 (Samsung-SM-G935V)

### Current Behavior

When trying to get into the app by clicking on push notification from turned off state, after our custom splash screen is shown, instead of fading out, splash screen switches to the default android one and stays on indefinitely.

### Expected Behavior

Splash screen should fade out after either timer set in config or on splashScreen.hide() command sent from webview.

### Other Technical Details

So far we`ve only been able to reproduce this issue on this specific device. Android 8 emulator works weird but this issue is not present

### Additional Context

It seems like setOnExitAnimationListener method from showWithAndroid12API never gets called in this specific instance. When it does, everything seems to work as expected.

**Comment by Ionitron** [comment] 2023-01-09 09:50
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-25 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-25 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
