### ISSUE TITLE
IONIC with CapacitorHttp send empty data with Android

### ISSUE THREAD

**Issue by devartstudio** [ionic-team/capacitor-plugins#1857] opened 2023-10-24 18:00 UTC
I have a problem in Android with CapacitorHttp.

The data sent to the server is empty, in the console log I can see the data, but the server don't receive any data. With other platforms (browser and ios) it works fine, but not in Android (emulator and device).

Please, any suggestions? This is my ionic info:

```
Ionic:
   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 10.0.0
Capacitor:
   Capacitor CLI      : 5.4.1
   @capacitor/android : 5.4.1
   @capacitor/core    : 5.4.1
   @capacitor/ios     : 5.4.1
Utility:
   cordova-res : not installed globally
   native-run  : 1.7.3
System:
   NodeJS : v18.17.1 (/usr/local/bin/node)
   npm    : 9.6.7
   OS     : macOS Unknown
```

Thanks for your help.

Ionic api calls.

```
const options : HttpOptions= {
    url: "https://fakeapi.com/url",
    headers: {'Content-Type': 'multipart/form-data'},
    data: {nickname:"fakenickname",password:"fakepassword"}
};
const response: HttpResponse = await CapacitorHttp.post(options);
```

server calls log with iOs and browser (correct):

```
{"post":{"nickname":"fakenickname","password":"fakepassword"},"get":{"_":"2023-09-22T09:20:25.556Z"},"req":{"\/url":"","nickname":"fakenickname","password":"fakepassword"}}
```

server calls log with Android (NOT correct):

```
{"post":[],"get":{"_":"2023-09-21T17:53:24.196Z"},"req":{"\/url":""}}
```

**Comment by Ionitron** [comment] 2024-01-02 22:10
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-01-18 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-18 00:03 UTC
Labels: needs reproduction
