### ISSUE TITLE
Filesystem document saving doesn't work after reinstall 

### ISSUE THREAD

**Issue by TonyGiorgio** [ionic-team/capacitor-plugins#1851] opened 2023-10-20 22:09 UTC
## Bug Report

Uninstalling and then installing my capacitor app results in not being able to store files to `Documents` anymore. 

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
`Document` saves correctly whenever it is a fresh install. However, when the app is uninstalled and installed again, it gets permission errors. 

```
2023-10-20 15:01:33.471  6530-6623  Capacitor/...stemPlugin    E  Creating file '/storage/emulated/0/Documents/state.json' with charset 'UTF-8' failed. Error: /storage/emulated/0/Documents/state.json: open failed: EACCES (Permission denied)
                                                                                                    java.io.FileNotFoundException: /storage/emulated/0/Documents/state.json: open failed: EACCES (Permission denied)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    	at com.capacitorjs.plugins.filesystem.Filesystem.saveFile(Filesystem.java:54)
                                                                                                    	at com.capacitorjs.plugins.filesystem.FilesystemPlugin.saveFile(FilesystemPlugin.java:161)
                                                                                                    	at com.capacitorjs.plugins.filesystem.FilesystemPlugin.writeFile(FilesystemPlugin.java:111)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8063)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:560)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
                                                                                                    	at com.capacitorjs.plugins.filesystem.Filesystem.saveFile(Filesystem.java:54) 
                                                                                                    	at com.capacitorjs.plugins.filesystem.FilesystemPlugin.saveFile(FilesystemPlugin.java:161) 
                                                                                                    	at com.capacitorjs.plugins.filesystem.FilesystemPlugin.writeFile(FilesystemPlugin.java:111) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Expected Behavior
It should save to documents no matter if it is a fresh install or not. 

### Code Reproduction
```
import { Capacitor } from "@capacitor/core";
import { Directory, Encoding, Filesystem } from "@capacitor/filesystem";
import { Toast } from "@capacitor/toast";

export async function downloadTextFile(
    content: string,
    fileName: string,
    type?: string
) {
    const contentType = type ? type : "application/json";

    if (Capacitor.isNativePlatform()) {
        try {
            const writeFileResult = await Filesystem.writeFile({
                path: `${fileName}`,
                data: content,
                directory: Directory.Documents,
                encoding: Encoding.UTF8
            });

            await Toast.show({
                text: `Saved to ${writeFileResult.uri}`,
                duration: "long"
            });
        } catch (err) {
            console.error("Error writing the file:", err);
            await Toast.show({
                text: `Error while saving file`,
                duration: "long"
            });
        }
    }
}
```

**Comment by Ionitron** [comment] 2023-10-27 11:05
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by TonyGiorgio** [comment] 2023-10-27 15:54
I provided the code.

**Comment by Ionitron** [comment] 2023-11-12 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-12 00:03 UTC
Labels: platform: android, needs reproduction

**Comment by TonyGiorgio** [comment] 2023-11-12 18:53
What more information do you want? 

Can I get a real human that isn't a fucking bot hassling me? Unless this project is abandoned.
