### ISSUE TITLE
Geolocation.getCurrentLocation () does not stop querying the current position

### ISSUE THREAD

**Issue by zackbone** [ionic-team/capacitor-plugins#440] opened 2021-05-27 05:25 UTC
### Plugin(s)
@capacitor/geolocation@1.0.0

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/core: 3.0.0
  @capacitor/cli: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0
```

### Platform(s)
Android (Version 11)

### Current Behavior
I call the method Geolocation.getCurrentPosition () in the code to get the current geocoordinates.
When I run the app with livereload on the Android smartphone and debug it with Chrome, I notice that the method in the plugin continues to execute the calls, although getCurrentPosition () should only be executed once.
Even if you make changes to the code and reload the app, the plugin seems to continue to execute getCurrentPosition - even if getCurrentPosition () is not called after the reload in the JS code.

Here is the output from the Console:
```
ngOnInit fired
geolocation.service.ts:128 findLocations() fired!
start:228 native Geolocation.checkPermissions (#105834619)
start:202 result Geolocation.checkPermissions (#105834619)
geolocation.service.ts:45 requestPermission() fired! status: {location: "granted"}
start:228 native Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
geolocation.service.ts:159 findLocations():, locations:  (2) [{…}, {…}]
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
start:202 result Geolocation.getCurrentPosition (#105834620)
```

### Expected Behavior
The getCurrentPosition () method should only be executed once and then terminate the renewed query of the current position.

### Code Reproduction
```
async currentPosition(): Promise<Position> {
    const position: Position = await Geolocation.getCurrentPosition();
    return position;
}
```

**Comment by jcesarmobile** [comment] 2021-05-27 08:15
Duplicate of https://github.com/ionic-team/capacitor-plugins/issues/376

**Closed by jcesarmobile** 2021-05-27 08:15 UTC
Labels: platform: android, triage
