### ISSUE TITLE
Share plugin cannot call Share.share more then one time

### ISSUE THREAD

**Issue by tomer2141** [ionic-team/capacitor-plugins#520] opened 2021-07-16 01:00 UTC
### Plugin(s)
@capacitor/share: 1.0.3

### Capacitor Version
  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

### Platform(s)
android

### Current Behavior
While calling Share.share for the first time it will work properly, but if I will try to run the share function again i will get an error:
(using the chrome://inspect/#devices -> inspect -> console)
Error: Can't share while sharing is in progress Error: Can't share while sharing is in progress

### Expected Behavior
Be able to share more then one time

### Other Technical Details
After digging up in the SharePlugin.java file i noticed that the activityResult callback is never called so the varriable isPresnteing will always be true after calling the share function for the first time

**Comment by jcesarmobile** [comment] 2021-07-16 07:31
What’s your android version?

**Comment by tomer2141** [comment] 2021-07-16 11:55
@jcesarmobile A physical device running android 10

**Comment by jcesarmobile** [comment] 2021-07-16 11:59
which option/app are you choosing for sharing?

**Comment by tomer2141** [comment] 2021-07-16 12:07
It happens when i also press the cancel button and when i try to share with whatsapp, but those are the only two methods i checked...

**Comment by tomer2141** [comment] 2021-07-16 14:59
After upgrading my android version to 11 it started working as expected.

**Comment by jcesarmobile** [comment] 2021-07-16 17:39
I'll try to get an Android 10 device to test, it's the only one I don't have at the moment 😢

**Comment by tomer2141** [comment] 2021-07-19 07:56
Seems like this issue is happening again with android version 11 :(

**Comment by YogiBear52** [comment] 2021-07-26 08:43
It happens to us also. Any progress?

**Comment by grigorig** [comment] 2021-07-26 09:51
I'm also seeing this, but I'm using Android 11.

**Comment by grigorig** [comment] 2021-07-26 10:02
FWIW this mostly needs a documentation update I guess. I also noticed that just `await`ing isn't cutting it, is this possibly optimized away?

**Comment by kevinfavv** [comment] 2021-08-09 13:32
Waiting for promise dont work for me, any news ?

**Comment by mukul-myhq** [comment] 2022-03-07 07:15
any updates on this bug?

**Comment by henry-alakazhang** [comment] 2022-03-16 04:38
I encountered this issue, but I found that it was caused by an outdated version of the Facebook connect plugin (`ionic-native/facebook` + `cordova-plugin-facebook-connect`) somehow blocking/absorbing all the `ActivityResult`s. For me, it was also causing issues with `<input type="file">` and other things that rely on opening other activities.

Upgrading the plugin to latest seems to have fixed it for me.

**Comment by rkundnani** [comment] 2022-08-25 05:48
any updates on how to solve it?

**Comment by shikha2408** [comment] 2022-09-20 09:28
share popup should occur only if a specific button is clicked in capacitor.In my app once I click share button to share file, then again If I leave that screen and again start from home screen , it is showing me share popup even before clicking the share button?Is there any way to close this popup from the background ?

**Comment by jcesarmobile** [comment] 2022-09-20 17:18
Closing since I can't reproduce and some users say it's resolved.
If somebody is still facing the same problem, create a new issue and provide a sample app where the issue can be reproduced.
Make sure you are using await on the share call and don't call it again until the first one resolved.

**Closed by jcesarmobile** 2022-09-20 17:18 UTC
Labels: platform: android
