### ISSUE TITLE
@capacitor/camera: Photo Picker from Gallery not working in VM_Ware(Airwatch) MDM.

### ISSUE THREAD

**Issue by KartikDang** [ionic-team/capacitor-plugins#2176] opened 2024-08-16 11:14 UTC
### Plugin(s)

Capacitor Camera Plugin: V5.0.8

### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/core: 5.6.0

### Platform(s)

Android

### Current Behavior

We are experiencing an issue with our mobile application where users are unable to upload photos from the gallery when the app is deployed via a Mobile Device Management (MDM) system: VM-Ware(Airwatch). The issue does not occur when the app is run outside the MDM environment.

### Expected Behavior

The app should successfully upload images from both the camera and gallery, even when deployed through MDM.

### Code Reproduction

1. Create a test app using the Capacitor library with image upload functionality from both camera and gallery.
2. Deploy the app on a device without MDM and verify that image upload from both camera and gallery works.
3. Deploy the same app through Airwatch.
4. Try to upload an image from the gallery.

### Other Technical Details

1. We are also not able to fetch any error message, the error JSON is empty

### Additional Context

1. The issue does not occur when the app is not deployed through MDM.
2. All relevant permissions for gallery access have been confirmed to be enabled.

**Comment by Ionitron** [comment] 2024-08-19 16:25
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-09-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-09-04 00:03 UTC
Labels: platform: android, needs reproduction
