### ISSUE TITLE
Google Map Draw Polygon, Circles 

### ISSUE THREAD

**Issue by aljabr** [ionic-team/capacitor-plugins#1394] opened 2023-01-28 06:24 UTC
### Plugin

google-map

### Description

make the ability to draw polygons and circles 

### Platform(s)

IOS - Android - Web

**Comment by jcesarmobile** [comment] 2023-01-30 09:39
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/998

**Closed by jcesarmobile** 2023-01-30 09:39 UTC
Labels: platform: android, platform: ios, platform: web
