### ISSUE TITLE
ActionSheet: 

### ISSUE THREAD

**Issue by colenso** [ionic-team/capacitor-plugins#2201] opened 2024-10-03 10:30 UTC
### Plugin(s)

Capacitor Action Sheet Plugin

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0
  @capacitor/core: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Adding duplicate action sheet causes an error(as reported by crashlytics):
```
          Fatal Exception: java.lang.IllegalStateException: Fragment already added: ActionSheet{3e19249} (67f3a023-5049-462d-afb5-597d8d1fc0cb tag=capacitorModalsActionSheet)
       at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:93)
       at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1503)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2009)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1895)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Expected Behavior

Should replace the existing Fragment if it's already added.

**Comment by Ionitron** [comment] 2024-10-16 08:49
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-11-01 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-11-01 00:04 UTC
Labels: platform: android, needs reproduction
