### ISSUE TITLE
Marker Dragging not working on Android

### ISSUE THREAD

**Issue by cwcarlson10** [ionic-team/capacitor-plugins#951] opened 2022-05-03 18:25 UTC
### Plugin(s)

google-maps
```
± npm -v @capacitor/google-maps
8.1.0
```

### Capacitor Version

```
± npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.0
  @capacitor/core: 3.5.0
  @capacitor/android: 3.5.0
  @capacitor/ios: 3.5.0

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4


```

### Platform(s)

Android

### Current Behavior

When dragging is enabled it works on ios but not on Android

### Expected Behavior

Dragging of a marker should work on both IOS and Android

### Other Technical Details

This was ran on a Samsung Galaxy A51 smartphone

**Comment by Ionitron** [comment] 2022-05-04 08:17
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-05-20 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-05-20 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
