### ISSUE TITLE
Capacitor Google map not showing in android.

### ISSUE THREAD

**Issue by RajanMobix** [ionic-team/capacitor-plugins#1055] opened 2022-06-23 10:23 UTC
### Plugin(s)
"@capacitor/google-maps": "1.1.0"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0
```

### Current Behavior
Google map is not showing on the android device however it is working on the browser perfectly fine.

### Expected Behavior
Google map should display on the android device.

### Other Technical Details
I have followed the steps from this: https://capacitorjs.com/docs/apis/google-maps
I have also made the background of ion-content transparent.

### Additional Context
There is no error log on the console.

**Comment by artemboyko43** [comment] 2022-07-02 13:57
The same for me, seems like map behind the webview

**Comment by Ionitron** [comment] 2022-07-26 16:15
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dyegonery** [comment] 2022-07-29 19:21
Also having the same issue. The seems to be loaded, as the listeners are working, and I can see the number of requests growing on Google Developers Console, but the map doesn't show up.

**Comment by mannok** [comment] 2022-08-01 08:16
> Also having the same issue. The seems to be loaded, as the listeners are working, and I can see the number of requests growing on Google Developers Console, but the map doesn't show up.

Same here

**Comment by jcesarmobile** [comment] 2022-08-15 21:09
Closing since no sample app was provided. There has been several similar issues reported and problems are often related to not using a proper android SDK key or not making the parent elements transparent.
All the people who commented on the issue, feel free to create new issues if you still couldn’t see the map, but make sure you provide a sample app so we can reproduce.

**Closed by jcesarmobile** 2022-08-15 21:09 UTC
Labels: needs reproduction
