### ISSUE TITLE
Haptics (5.0.7) vibrate call throws error in Firefox desktop

### ISSUE THREAD

**Issue by wade-dallon** [ionic-team/capacitor-plugins#2169] opened 2024-08-09 19:06 UTC
### Plugin(s)

- Haptics v5.0.7

### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0
  @capacitor/core: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

- Firefox

### Current Behavior

When calling Haptics.vibrate(<duration>) the UI freezes and the Firefox is filled with error messages, "Error: Browser does not support the vibrate API"

### Expected Behavior

The vibrate API will not be called for unsupported platforms.

### Code Reproduction

```
import { Haptics } from "@capacitor/haptics";

await Haptics.vibrate({ duration: 300 });
```

**Comment by Ionitron** [comment] 2024-08-19 16:22
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-09-04 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-09-04 00:03 UTC
Labels: needs reproduction, needs reply
