### ISSUE TITLE
local-notifications - Android - No sound when built with shrinkResources option

### ISSUE THREAD

**Issue by UZ8VLqifK36Z** [ionic-team/capacitor-plugins#2191] opened 2024-09-08 09:18 UTC
### Plugin(s)
local-notifications

### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
Hello,
I'm not sure if this is really a bug or if the documentation needs to be updated, but building with the shrinkResources option prevents sound from being played with notifications.
https://developer.android.com/build/shrink-code

I have carefully checked the Capacitor documentation, but I didn't find anything warning against this build option.

### Other Technical Details
Tested on virtual Android 10.0 (Google Play) and 14.0 (Google Play) → no sound.
Also tested on two physical devices running Android 14. One physical device gives default system sound and the other gives no sound
I think the option shrinkResources delete the sound file placed in the res/raw folder.

**Comment by Ionitron** [comment] 2024-09-16 10:23
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-10-02 00:03
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-10-02 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
