### ISSUE TITLE
[@capacitor/googleMap - Android]We need to have control on MarkerId

### ISSUE THREAD

**Issue by francolondra** [ionic-team/capacitor-plugins#1260] opened 2022-11-05 01:47 UTC
### Plugin
@capacitor/google-maps

### Description
I detected a necessity that I need to mapper the field markerId from marker to MarkerClickCallbackData , for example ,if you fill the marker of your database and then you want open a modal and called a service with this markerId , now it is imposible, because the markerId is generate with m0,m1,m2...

### Platform(s)
Android

### Preferred Solution
I think that you need add a field called "markerId" in interface Marker and then it should mapper with this interface Marker Click Callback Data , how title and snippet

**Comment by francolondra** [comment] 2022-11-06 23:53
I put a image of the problem 
![bug-marker](https://user-images.githubusercontent.com/40376158/200202425-7ebf8177-0935-4982-b753-32e7c8794ed4.png)

**Comment by muuvmuuv** [comment] 2022-11-07 06:24
See also my PR which fixes iOS: #1222

**Comment by Dev-it-a-dev** [comment] 2022-11-07 08:36
We should be able to set our markerId directly when adding markers through `addMarker()` or `addMarkers()` methods.

I think would make sense to add `markerId` attribute to the `Marker` interface and replace MarkerCallbackData's one with something like `autoGeneratedId`

**Comment by jcesarmobile** [comment] 2022-11-07 15:37
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1139

**Closed by jcesarmobile** 2022-11-07 15:37 UTC
Labels: platform: android
