### ISSUE TITLE
Button don't work in browser

### ISSUE THREAD

**Issue by CamilleFrive** [ionic-team/capacitor-plugins#1959] opened 2023-12-10 23:04 UTC
### Plugin(s)
 "@capacitor/browser": "^5.1.0"

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
ios

### Current Behavior
click on a specific button in the browser does nothing

### Expected Behavior
click should redirect to an url which will also redirect to a custom scheme url which will close the browser

### Code Reproduction
this code should be called
```
window.location.replace('frive://close');
```
and how it is handled
```
const tryClose = async () => {
    if (Capacitor.isNativePlatform()) {
      await Browser.close();
    }
  };

  App.addListener('appUrlOpen', (data) => {
    if (data.url == 'frive://close') {
      tryClose();
      window.location.reload();
    } 
  });
```

### Other Technical Details
This don't work on some device (like iphone 15 pro max) and work on other (iphone XS)

The agree button is the one which cause the issue (a javascript issue?)
<img width="362" alt="image" src="https://github.com/ionic-team/capacitor-plugins/assets/128401102/3682ce23-bf8c-493a-8eba-263b87af3d06">

**Comment by CamilleFrive** [comment] 2023-12-11 22:33
Update:
The issue is that i used navigate here the full addListener i used

````
  const tryRequest = async (url: string) => {
    const url2 = new URL(url);
    const apiService = axios.create({
      baseURL: url2.origin,
    });

    await apiService.get(url2.pathname + url2.search);
  };

  const tryClose = async () => {
    if (Capacitor.isNativePlatform()) {
      await Browser.close();
    }
  };

 App.addListener('appUrlOpen', (data) => {
    const navigate = useNavigate();

    if (data.url == 'frive://close') {
      tryClose();
      window.location.reload();
    } else {
      if (data.url.startsWith('https://')) {
        if (data.url.includes('/api/v1')) {
          tryRequest(data.url);
          tryClose();
          window.location.reload();
        } else {

          const url = new URL(data.url);
          if (url) {
            navigate(url.pathname);
          }
        }
      }
    }
  });
````

But now I don't know what to do to redirect users, windows.location seems not to work

**Comment by dallastjames** [comment] 2024-01-02 22:22
You likely need to navigate based on the framework you're using, which would be specific to your application since navigation is handled by the web app and not Capacitor. Where are you getting the `navigate` from? Can you provide a sample reproduction that reproduces this issue in a minimal application?

**Comment by Ionitron** [comment] 2024-01-02 22:22
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2024-01-18 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2024-01-18 00:02 UTC
Labels: platform: ios, needs reproduction
