### ISSUE TITLE
Ionic 6 @capacitor/google-maps not loaded in ion-modal dialogs

### ISSUE THREAD

**Issue by veeravetrivel** [ionic-team/capacitor-plugins#1038] opened 2022-06-14 13:42 UTC
## Bug Report
Hello Team

 I am using Ionic 6 and Angular 13, capacitor also latest version. Using @capacitor/google-maps is not loaded in ion-modal component. Is there way to achieve it? 
### Plugin(s)
   google-maps
    "@capacitor/google-maps": "1.0.0"

### Capacitor Version
3.5.0

### Platform(s)
Android

### Current Behavior
@capacitor/google-maps is not loaded in ion-modal

### Expected Behavior
Need to load maps in ion-modal dialog

@mlynch @elylucas @aparajita @peschee @imhoffd

**Comment by Ionitron** [comment] 2022-07-06 17:39
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-07-22 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-07-22 00:03 UTC
Labels: platform: android, needs reproduction, needs reply
