### ISSUE TITLE
@capacitor/browser Check if there is a browser open before calling close()

### ISSUE THREAD

**Issue by aleksandar-brkic** [ionic-team/capacitor-plugins#1899] opened 2023-11-14 13:52 UTC
### Plugin
@capacitor/browser

### Description
When calling the `close()` method while there is no capacitor browser window open, the console logs an error saying `No active window to close!` . When you open a deeplink from the capacitor browser itself, on some devices (particularly iOS) the browser does not close, as that link is already opened in the background (some url in the app page that actually started the capacitor browser). So we added that method on the deeplink open listener, but this then fires on every deeplink, not just that scenario, which causes the error (which does not affect the user or the code, just annoying in the logs).

### Preferred Solution
It would be good if we had a method to check if the browser is open already. Eg `if(Browser.isOpen()) Browser.close()` which would stop the `close` method being called when not needed.

**Comment by Ionitron** [comment] 2023-11-14 14:01
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-11-30 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-11-30 00:03 UTC
Labels: needs reproduction, needs reply
