### ISSUE TITLE
Map not working in android but working in browser.

### ISSUE THREAD

**Issue by vaibhavG321** [ionic-team/capacitor-plugins#1250] opened 2022-10-27 09:33 UTC
### Plugin(s)

"@capacitor/google-maps": "^4.2.1"

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Just implemented google maps as mentioned in the documentation. It is working perfectly in the browser but when tested in android then it is not showing the map.

### Expected Behavior

The map should be displayed in android the same as it is being displayed in the browser.

### Code Reproduction

HTML file
```
<ion-content>
  <ion-card>
    <capacitor-google-map #map></capacitor-google-map>
  </ion-card>
</ion-content>
```

CONTROLLER file
```
  @ViewChild('map')
  mapRef: ElementRef<HTMLElement>;
  newMap: GoogleMap;

...

  async showMap() {
    try {
      const lat = 33.6;
      const long = -117.9;
      console.log(lat, long)
      this.newMap = await GoogleMap.create({
        id: 'map', // Unique identifier for this map instance
        element: this.mapRef.nativeElement, // reference to the capacitor-google-map element
        apiKey: environment.googleApiKey, // Your Google Maps API Key
        config: {
          center: {
            // The initial position to be rendered by the map
            lat: lat,
            lng: long,
          },
          zoom: 16, // The initial zoom level to be rendered by the map
        },
      });

      // Add a marker to the map
      const markerId = await this.newMap.addMarker({
        coordinate: {
          lat: lat,
          lng: long
        }
      });
    } catch(err) {
      alert("errr --> " + JSON.stringify(err));
    }
  }
```

### Other Technical Details

Node version: 16.14.0

### Additional Context

<img width="1440" alt="Screenshot 2022-10-27 at 2 39 02 PM" src="https://user-images.githubusercontent.com/51531542/198247956-6f711e3c-d23d-471e-8d88-9795a3317948.png">
In my opinion, this might be the issue of the map not being displayed, but I couldn't find any correct solution for this issue.

This is the browser view.
<img width="463" alt="Screenshot 2022-10-27 at 2 53 39 PM" src="https://user-images.githubusercontent.com/51531542/198248698-395c6501-b94c-4dab-b53c-f270401fb6fd.png">

This is the mobile view.
<img width="446" alt="Screenshot 2022-10-27 at 2 41 30 PM" src="https://user-images.githubusercontent.com/51531542/198248752-c0651c4a-887c-46cb-8a91-f84bd6da346f.png">

**Comment by Ionitron** [comment] 2022-10-27 09:43
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by vaibhavG321** [comment] 2022-10-27 10:01
I only added the code mentioned in the plugin document nothing else. Do you still want me to create a separate project for you to reproduce?
Please read this issue once, maybe we won't require the reproduction part.

**Comment by jcesarmobile** [comment] 2022-10-27 12:15
yes, please, provide a sample app where the issue can be reproduced

**Comment by Dev-it-a-dev** [comment] 2022-10-27 12:51
@vaibhavG321 make sure your google API Key is correctly configured from Google Console.

Check:
- [ ] If your "Maps SDK for Android" is enabled;
- [ ] If your Android API key is linked correctly to the "Maps SDK for Android";
- [ ] If your Android API key is restricted correctly to your app (must match package name "`com.example.app`" and it's SHA-1 digital fingerprint)


_I got similar errors and these helped me running the map on android too._

**Comment by GiustiRo** [comment] 2022-10-28 19:54
Hi, I've been facing the same issue on Android (physical and emulated device)

Steps to show up your map:
1) Inspect your device with chrome (chrome://inspect/#devices)
2) set all 'background', '--background', etc css variables and rules of your project to: **none** or **transparent**.

There it is! its behind all the project. I hope capacitor team can fix this correctly, to allow using background styles and show the map.. positions rules and z-index wont fix it.

**Comment by jcesarmobile** [comment] 2022-10-28 21:20
That’s not a bug, it’s the only way of showing a native view inside the webview, it’s documented
https://capacitorjs.com/docs/apis/google-maps#usage

**Comment by Ionitron** [comment] 2022-11-13 00:04
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-11-13 00:04 UTC
Labels: platform: android, needs reproduction, needs reply
