### ISSUE TITLE
bug: Push Notifications for foregrounded app still broken on Android (V3)

### ISSUE THREAD

**Issue by creativiii** [ionic-team/capacitor-plugins#234] opened 2021-02-01 13:40 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli: 3.0.0-beta.1
  @capacitor/android: 3.0.0-beta.1
  @capacitor/ios: 3.0.0-beta.1
  @capacitor/core: 3.0.0-beta.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
Last year I reported that push notifications did not appear on Android if the app was currently foregrounded. I [created a PR with my own workaround](https://github.com/ionic-team/capacitor-site/pull/144) of creating a local notification, this was refused as there was going to be a proper fix for Capacitor 3.

I'm currently testing Capacitor 3 and the behavior seems exactly the same as it was in Capacitor 2.

Since there doesn't seem to be [any issues open for push notifications](https://github.com/ionic-team/capacitor/issues?q=is%3Aopen+is%3Aissue+label%3A%22plugin%3A+push-notifications%22), I thought I'd open this just in case.

### Expected Behavior
Just like in iOS, if a notification is received while the app is open, it should be displayed as usual.

### Code Reproduction
N/A

**Comment by jcesarmobile** [comment] 2021-02-05 13:24
Just a note.
On iOS the push notifications are not shown when the app is in foreground neither unless [you configure them to show](https://capacitorjs.com/docs/v3/apis/push-notifications#push-notifications-appearance-in-foreground).
It was showing on a previous release of the plugin, but it was a mistake on the plugin migration and has been fixed on https://github.com/ionic-team/capacitor-plugins/pull/209


The comment you got on the PR was
> Hey there, an update. The team is unsure at the moment about recommending this workaround. They're investigating how to improve PN's for Capacitor 3 so for now, we appreciate your patience. Thanks for contributing the PR!

It says "the team is unsure at the moment about recommending this workaround", which I agree with. And doesn't say it will have a "proper fix".

So, to be clear, this is not a bug, it is intended to work like this, I can't think of any app that I use that display the notifications when the app is in foreground. But of course, would be nice to let the developer decide if they want to show the push notification even when in foreground same way you can configure it on iOS.

**Comment by creativiii** [comment] 2021-02-05 13:53
> Just a note.
> On iOS the push notifications are not shown when the app is in foreground neither unless [you configure them to show](https://capacitorjs.com/docs/v3/apis/push-notifications#push-notifications-appearance-in-foreground).
> It was showing on a previous release of the plugin, but it was a mistake on the plugin migration and has been fixed on #209
> 
> The comment you got on the PR was
> 
> > Hey there, an update. The team is unsure at the moment about recommending this workaround. They're investigating how to improve PN's for Capacitor 3 so for now, we appreciate your patience. Thanks for contributing the PR!
> 
> It says "the team is unsure at the moment about recommending this workaround", which I agree with. And doesn't say it will have a "proper fix".
> 
> So, to be clear, this is not a bug, it is intended to work like this, I can't think of any app that I use that display the notifications when the app is in foreground. But of course, would be nice to let the developer decide if they want to show the push notification even when in foreground same way you can configure it on iOS.

There's definitely apps that do it, for example Twitter catches all notifications and displays them in app directly with their own API. I'm sure plenty of others will popup a native banner when a notification comes in since they can't afford to have a complex notification system like Facebook or Twitter.

But beyond that, the problem with the current docs is that there's no mention of this being the situation for Android, which has led to discussions like:

- https://github.com/ionic-team/capacitor/issues/2261
- https://github.com/ionic-team/capacitor/discussions/3286
- https://forum.ionicframework.com/t/ionic-5-and-capacitor-fcm-push-notification-issue-on-android/192408

So it's obviously creating at least some level of confusion as the default behavior is not mentioned anywhere in the docs.

I'm not saying the workaround I've got should be in the docs, but at least a mention of the current behavior of notifications on Android ( [to mirror the already existing iOS section which specifically mentions what the default behavior is](https://capacitorjs.com/docs/v3/apis/push-notifications#push-notifications-appearance-in-foreground) ) would probably clarify a lot of confusion and avoid a people asking over and over about it.

**Comment by marwilc** [comment] 2021-02-25 15:59
instagram for example shows notifications in the foreground

**Comment by codercodingthecode** [comment] 2021-07-21 20:59
This is definitely an issue. Getting Push Notifications  (v3) to work with android is an incredible pain. (Ionic/Capacitor/React)
I have it working with IOS, which was a breeze, however, for android, so far it is a no-go.

**Comment by ndabAP** [comment] 2021-12-21 10:38
I'm new to app development and started from scratch a project and I'm trying to get a pop up notification in Android when the app is in background (not closed). The notification displays only in the upper area but doesn't popup like other notifications in other apps.

![Screenshot_20211218-221312](https://user-images.githubusercontent.com/8510570/146916101-dca05011-d9a3-4b24-9aab-bb14900cbfae.jpg)

![Screenshot_20211218-221340](https://user-images.githubusercontent.com/8510570/146916135-5e15c862-09e6-41cd-b77c-cfe405f9b86a.jpg)

**Comment by jcesarmobile** [comment] 2022-06-28 11:01
4.0.0 of the plugin will now show notifications using notification payload if [presentationOptions](https://capacitorjs.com/docs/apis/push-notifications#push-notifications-appearance-in-foreground) is configured to show the alert

**Closed by jcesarmobile** 2022-06-28 11:01 UTC
Labels: platform: android, plugin: push notifications
