### ISSUE TITLE
Using iOS Messages to Share Breaks CSS/Layout of Entire App

### ISSUE THREAD

**Issue by jashalevenson** [ionic-team/capacitor-plugins#1023] opened 2022-06-03 23:27 UTC
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/core: 3.4.1
  @capacitor/cli: 3.1.2
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0


```

### Platform(s)

iOS

### Current Behavior

On iOS devices, after launching the Messages app to share a message and returning to the app, the entire application is shifted approx 75px up making the toolbar overlap the safe area and become unusable. 
### Expected Behavior

The look of the app should not change after the Messages app is launched.

**Comment by nprather** [comment] 2022-07-07 12:58
I'm having the same issue.  
It appears to only happen when sharing a fairly large amount of text via the Messenger app on iPhone.

This is ionic 6 latest, capacitor latest, etc.  I created a github repo here that shows the bug:  **[https://github.com/nprather/toolbar-dissappearing.git](https://github.com/nprather/toolbar-dissappearing.git)**

### **Before sharing everything looks good, Toolbar is visible:**

![IMG_BC8816845224-1 2](https://user-images.githubusercontent.com/3101108/177778367-734d7ccb-6415-4f07-9df7-84da7db5a493.jpeg)


### **BUG After sharing the BIG text the Toolbar shift happens:**

![IMG_1CB89AEDC7A8-1](https://user-images.githubusercontent.com/3101108/177777506-4311a60f-7fdb-4ddb-9e57-ab0abdb626cf.jpeg)

**Comment by jcesarmobile** [comment] 2022-09-21 13:51
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/831

**Closed by jcesarmobile** 2022-09-21 13:51 UTC
Labels: platform: ios
