### ISSUE TITLE
Status bar issues with Android 8

### ISSUE THREAD

**Issue by loicparent** [ionic-team/capacitor-plugins#1623] opened 2023-05-30 09:36 UTC
### Plugin(s)
"@capacitor/status-bar": "^5.0.2"

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3
  @capacitor/core: 5.0.3
```

### Platform(s)
Android

### Current Behavior
The status bar is totally white with the `Style.Dark` when I enable `setOverlaysWebView` or when I use transparency in the `setBackgroundColor` (ex: #25202000).

### Expected Behavior
If the device is not compatible with the `setOverlaysWebView` or with the transparency, there should be a fallback to keep the status bar visible and not visually empty.

OR, there should be a way to test if the `setOverlaysWebView` is compatible or not to avoid this issue (maybe using the `getInfo` or a specific new method).

### Code Reproduction
Just a simple install of ionic with the package `@capacitor/status-bar` and run on device with issue such as the Samsung Galaxy A5 with Android 8.0.

(If needed, I can create a blank project but this is very basic and specific to a device issue).

### Other Technical Details
It works fine on main Android devices but on some of them, the error is present.
If I set a non-transparency color (ex: E3E3E3), it works fine.

_Thanks for your help,
Loïc_

**Comment by loicparent** [comment] 2023-05-30 10:00
To better understand the issue, here you can see the render comparing 2 Android Devices (Left: Galaxy A5 with Android 8.0. - Right: Galaxy A51 with Android 13):


### With transparency (with or without setOverlaysWebView)
```.ts
StatusBar.setStyle({
  style: Style.Dark
});
StatusBar.setOverlaysWebView({
  overlay: true
});
StatusBar.setBackgroundColor({
  color: '#25202000'
});
```
![with_transparency](https://github.com/ionic-team/capacitor-plugins/assets/11327909/913c5464-2eae-45e7-9c2b-8068dfe167a2)


### Without transparency (with or without setOverlaysWebView)
```.ts
StatusBar.setStyle({
  style: Style.Dark
});
StatusBar.setOverlaysWebView({
  overlay: true
});
StatusBar.setBackgroundColor({
  color: '#252020'
});
```
![without-transparency](https://github.com/ionic-team/capacitor-plugins/assets/11327909/5143f9b5-8910-4365-8eb8-0e0d792471b4)

Therefore, with transparency, the render seems to be buggy on the left device and the render is nice on the right device. Without transparency, the render is correct on the left device but has not a very nice look on the right device (even if this is acceptable). So, I prefer keeping the transparent right render if possible and for devices that this is not compatible, use a non-transparency alternative (but only if this is not compatible) ;-)

**Comment by Ionitron** [comment] 2023-05-30 10:38
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by loicparent** [comment] 2023-05-31 13:24
Hello, you can find a code reproduction [here](https://github.com/loicparent/ionic-debug-screen-orientation/tree/main).

After testing, the result is correct with `setOverlaysWebView` without using a `setBackgroundColor` but if I want to add a background with opacity, the result is not as expected.

**Comment by Ionitron** [comment] 2023-06-16 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-06-16 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
