### ISSUE TITLE
Unable to back in history with backButton

### ISSUE THREAD

**Issue by progcode** [ionic-team/capacitor-plugins#1095] opened 2022-07-26 19:48 UTC
### Plugin(s)
@capacitor/app

### Capacitor Version

```
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
```

### Platform(s)
android

### Current Behavior
i would like use hardware back button to navigate in history go back with -1. When I tap the back button, the app exit immediately.

### Expected Behavior

The back button navigate in history with back-1.

### Code Reproduction

`mounted() {
    const router = useRouter();

    CapacitorApp.addListener('backButton', ({ canGoBack }) => {
      if(canGoBack){
        router.go(-1);
      } else {
        CapacitorApp.exitApp();
      }
    });`

### Other Technical Details

```
    "vue": "^3.2.21",
    "vue-router": "^4.0.12"
```

**Comment by Ionitron** [comment] 2022-07-27 07:52
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-08-12 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-08-12 00:02 UTC
Labels: platform: android, needs reproduction, needs reply
