### ISSUE TITLE
[@capacitor/push-notifications] FCM Token received invalid when app deployed via Play Console or Apple Connect

### ISSUE THREAD

**Issue by morsagmon** [ionic-team/capacitor-plugins#1556] opened 2023-04-24 06:14 UTC
### Plugin(s)

@capacitor/push-notifications 4.1.2
@capacitor/core 4.7.3
@angular/fire 7.5.0
@ionic/angular 7.0.2

### Capacitor Version

Capacitor Doctor:
```
Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/android: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/ios: 4.7.3
  @capacitor/cli: 4.7.3
```

### Platform(s)

iOS
Android
Angular

### Current Behavior

When I deploy my app directly from Android Studio locally to Android devices, the token I receive and use for sending notification is OK.

However, when the same App is deployed to the Google Play or to Apple Connect (TestFlight) and installed by the testers from Google Play or TestFlight on their devices - the token received is invalid. It also does not look like a token: it is much shorter and has only all-caps chars. Naturally, notifications fail on these devices (Google log screenshot attached here).

I print the received token immediately to the console, before I take it for DB storage, consider this console.log command in the registration process:

```
PushNotifications.addListener("registration", (token: Token) => {      
      if (token && !this.tokenProcessed) {
        this.tokenProcessed = true;
        console.log('My token: ' + JSON.stringify(token));
        this.onFCMTokenChanged.next(token.value);
      }
    });
```

This is the console.log output with the weird token received:

`My token: {"value":"D8636BCC62A673B4D574736AFCA1F73AF7C34EBBB7D99A38E05CDB6963FEAE8B"}`

On a device with local deployment from Android Studio, the (working) token received looks like this:

`My token: {"value":"c0qi_fp5QxmILTqsPVkYXv:APA91bFVDfv_EX8RjC5uB23p9Sb--1tYj4Piob2tuGgslcib8aKLAfFKKlCr7EFcZp7p05Rjb8WwY4X-aHMr-1DDUTDbR_MABTuAr4snxdAWGTwihx7I8VHuCa1VNHcdYU0DnWj33YvP"}`

Please help me understand and fix this weird behavior - happening only when the app is deployed through Google Play or Apple Connect.

### Expected Behavior

Token received from FCM should be exactly the same and a valid one regardless of the app deployment path - locally from Android Studio / XCode or through the App Store / Google Play.

### Other Technical Details

My Angular service code registering with FCM looks like this:

```
import { Injectable, NgZone } from "@angular/core";
import {
  ActionPerformed,
  PushNotifications,
  PushNotificationSchema,
  Token,
} from "@capacitor/push-notifications";
import { Capacitor } from "@capacitor/core";
import { getLocal, setLocal } from "./storage.service";
import { BehaviorSubject } from "rxjs";
import { App } from "@capacitor/app";
import { Router } from "@angular/router";
import { ToastAlertService } from "./toast-alert.service";

@Injectable({
  providedIn: "root",
})
export class FbNotificationsService {
  onFCMTokenChanged: BehaviorSubject<string> = new BehaviorSubject(""); //Listened to in app.component
  onAppResume: BehaviorSubject<string> = new BehaviorSubject(""); //Listened to in chat.page
  tokenProcessed: boolean = false;

  constructor(private taService: ToastAlertService, private zone: NgZone, private route: Router) { }

  initPush() {
    if (Capacitor.getPlatform() !== "web") {
      this.registerPush();
    } else {
      this.onFCMTokenChanged.next("web-platform");
    }
  }

  private registerPush() {
    PushNotifications.requestPermissions().then((permission) => {
      if (permission.receive === "granted") {
        console.log('FireBase Permission granted');

        PushNotifications.register(); 
      } else {
        console.log('FireBase NO permissions granted');
      }
    });

    PushNotifications.addListener("registration", (token: Token) => {
      if (token && !this.tokenProcessed) {
        this.tokenProcessed = true;
        console.log('My token: ' + JSON.stringify(token));
        this.onFCMTokenChanged.next(token.value);

        setLocal("device-token", token.value); //.then( () => {
      }
    });

    PushNotifications.addListener("registrationError", (error: any) => {
      console.log('Registration Error: ' + JSON.stringify(error));
      this.taService.dialogClose(
        "Network Error",
        "The network signal is not sufficient at this time. Please improve connection and try again"
      );
      App.exitApp();
    });
```

### Additional Context

I tried the Google Firebase support, but as I'm not using their FCM SDK, they are not helpful.

![fcm-error](https://user-images.githubusercontent.com/22539785/233913777-cd3ee3ef-1054-408a-9e21-edcdce692150.png)

**Comment by mghcs87** [comment] 2023-04-26 21:49
@morsagmon Check this, it worked well for me: [Guide](https://capacitorjs.com/docs/guides/push-notifications-firebase?__hstc=57877749.da6ed29f0d438309e258218ffdbf51ff.1673369765891.1678490917872.1682540510118.9&__hssc=57877749.1.1682540510118&__hsfp=3965019258&_gl=1*1o5wase*_ga*NTc3MDY5NjUzLjE2NzMzNjk3NjY.*_ga_REH9TJF6KF*MTY4MjU0NTQ3Mi4yMS4xLjE2ODI1NDU1OTguMC4wLjA.#add-initialization-code)

**Comment by spycedev** [comment] 2023-06-20 02:21
Any solution to this beside using a different plugin? I'm getting the same issue on iOS in development.

The token return is not a valid Firebase token

**Comment by Ionitron** [comment] 2023-08-22 17:34
This issue needs more information before it can be addressed.
In particular, the reporter needs to provide a minimal sample app that demonstrates the issue.
If no sample app is provided within 15 days, the issue will be closed.

Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-09-07 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-09-07 00:02 UTC
Labels: platform: android, platform: ios, needs reproduction, needs reply
