### ISSUE TITLE
Storage UserDefaults not loading in iOS 15 after background idle

### ISSUE THREAD

**Issue by kaimallie** [ionic-team/capacitor-plugins#643] opened 2021-10-02 15:02 UTC
### Plugin(s)
@capacitor/storage (1.2.0)

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/core: 3.2.3
```

### Platform(s)
iOS 15

### Current Behavior
I'm using Storage for a while, but since iOS 15 when you close the app and wait for 20/30 minutes and startup the app again, Storage data is not loading. Even when switching screens or actions, the UserDefaults on iOS 15 are not loading. When you then kill the app again and startup again, it's going back to normal. This process is just repeating all again every time you're not interacting for a long time. Feels like the UserDefaults data is going into idle state when the app is not active for 20/30 minutes. No issues on previous OS versions.

Cannot find anything about it on Google, but found this related issue from April about the iOS15 beta (https://developer.apple.com/forums/thread/685685). In my case it's not wiped, but available again after restart.

Also using a keychain capacitor plugin, but no issues. Feels like the connection needs to be refreshed.

### Expected Behavior
Storage data on iOS15 needs to be loaded at any time.

### Code Reproduction
Just using the default code after my app ands views are loaded:
```
import { Storage } from '@capacitor/storage';

const setName = async () => {
  await Storage.set({
    key: 'name',
    value: 'Max',
  });
};
```

**Comment by Ionitron** [comment] 2021-10-04 09:02
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2021-10-20 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2021-10-20 00:02 UTC
Labels: platform: ios, needs reproduction, needs reply

**Comment by charleslin826** [comment] 2021-11-19 07:55
happens to see this issue, maybe you can try this: https://developer.apple.com/forums/thread/667959?answerId=693810022#693810022.

**Comment by kaimallie** [comment] 2021-11-19 10:16
Thanks! I've indeed protection with 'NSFileProtectionComplete' enabled. Going to try to change that to 'NSFileProtectionCompleteUntilFirstUserAuthentication'.
