### ISSUE TITLE
downloadFile doesn't throw error on 404 urls 

### ISSUE THREAD

**Issue by scr2em** [ionic-team/capacitor-plugins#1732] opened 2023-08-14 14:27 UTC
### Plugin(s)
Filesystem

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/cli: 5.0.0
  @capacitor/core: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/ios: 5.1.0
```

### Platform(s)
iOS

### Current Behavior

when I use Filesystem.downloadFile to download a url that gives 404, the function doesn't throw an error 

### Expected Behavior
I expected the .catch would run, but instead it downloaded the 404 error message as the file which can't be opened

**Comment by jcesarmobile** [comment] 2023-08-15 12:28
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/1698

**Closed by jcesarmobile** 2023-08-15 12:28 UTC
Labels: platform: ios, type: bug
