### ISSUE TITLE
Dialog.alert() doesn't show a dialog in Android Studio's emulator, but does in the browser

### ISSUE THREAD

**Issue by tog22** [ionic-team/capacitor-plugins#1515] opened 2023-03-30 23:18 UTC
### Plugin(s)
@capacitor/dialog 4.1.0

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

[success] Android looking great! 👌
```

### Platform(s)
Android, as tested in the Android Studio emulator

### Current Behavior
This is a Vue app with Capacitor. I've added `Dialog.alert({message: 'msg',});` to run as soon as the app does. This succesfully yields a dialog in my browser when I run the app with `npm run serve`. However when I run the app in Android Studio's emulator with `npx cap run android`, no dialog shows.

### Expected Behavior
A dialog should show in Android Studio's emulator.

### Code Reproduction

[GitHub repo with code snapshot](https://github.com/tog22/Gods-Vue-Capacitor/tree/18ca98ddf138fc3f4f024b8112a57bb9a6658928)

The relevant code is in App.vue:

```
import { defineComponent, provide } from 'vue'
import { Capacitor } from '@capacitor/core';
import { Dialog } from '@capacitor/dialog';

export default defineComponent({
	name: 'App',
	setup() {
        
            Dialog.alert({
                message: 'msg',
            });
	}
})
```

**Comment by jcesarmobile** [comment] 2023-04-10 16:37
I can't reproduce.
Can you provide more information?
Are you running on a real device or emulator?
What's the Android version of the device/emulator?

**Comment by Ionitron** [comment] 2023-04-26 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-04-26 00:02 UTC
Labels: platform: android, needs reply
