### ISSUE TITLE
google maps plugin not being re-rendered when navigated away and back (iOS)

### ISSUE THREAD

**Issue by lil-j** [ionic-team/capacitor-plugins#1351] opened 2023-01-02 23:30 UTC
### Plugin(s)

* @capacitor/google-maps

### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

```

### Current Behavior
The Google Map renders great on web, and it rebuilds it every time i navigate to the page and away from it. **However**, on **iOS**, the map loads well and looks great on the first time viewing it, but if I got to a different page or tab, it is just white, and does not come back.

### Expected Behavior
The map should be re-rendered when I navigate back to the page as it does on web

### Code Reproduction
```
useIonViewDidEnter(() => {
        loadMap();
    }, []);

    async function loadMap() {
        // Fetch data
        const data = await fetchData();

        // Create a new map
        await createMap(data);
    }

    async function createMap(data) {
        newMap = await GoogleMap.create({
            id: 'my-cool-map',
            element: mapRef.current,
            apiKey: "",
            config: {
                center: {
                    lat: 47.655548,
                    lng: -122.303200
                },
                zoom: 15,
                // Style the map so it is dark and has a custom marker
                styles:  map_styles
            }
        })
        const markers = data.map((sighting) => {
            return {
                coordinate: {
                    lat:sighting.location.currentLatitude,
                    lng: sighting.location.currentLongitude
                },
                title:sighting.id
            }
        })
        await newMap.addMarkers(markers)
        await newMap.setOnMarkerClickListener(async function (data) {
            history.push('/sighting/' + data.title)
        })
    }
```

Thank you!! <3

**Comment by DwieDima** [comment] 2023-01-03 14:59
i have the same issue.
For now i have to use `forceCreate: true` for `GoogleMap.create()` as a workaround.

**Comment by Ionitron** [comment] 2023-01-05 15:45
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2023-01-21 00:35
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2023-01-21 00:35 UTC
Labels: platform: ios, needs reproduction, needs reply, plugin: google-maps

**Comment by aljabr** [comment] 2023-02-02 06:14
same here!
