### ISSUE TITLE
getDeliveredNotifications throws event error capacitorDidRegisterForRemoteNotifications not called

### ISSUE THREAD

**Issue by sts-ryan-holton** [ionic-team/capacitor-plugins#613] opened 2021-09-16 14:10 UTC
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/ios: 3.2.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**My `package.json` dependencies is as follows:**

```
"dependencies": {
  "@capacitor/android": "3.2.3",
  "@capacitor/camera": "1.1.0",
  "@capacitor/core": "3.2.3",
  "@capacitor/ios": "3.2.3",
  "@capacitor/network": "1.0.3",
  "@capacitor/push-notifications": "1.0.4",
  "@capacitor/splash-screen": "1.1.2",
  "@capacitor/status-bar": "1.0.3",
  "@capacitor/storage": "1.2.0",
  "@nuxt/components": "2.2.1",
  "@nuxtjs/auth-next": "5.0.0-1624817847.21691f1",
  "@nuxtjs/axios": "5.13.6",
  "@nuxtjs/dayjs": "1.4.0",
  "@nuxtjs/dotenv": "1.4.1",
  "@nuxtjs/sentry": "5.1.3",
  "@robingenz/capacitor-badge": "1.2.0",
  "@sentry/capacitor": "0.4.0",
  "core-js": "3.16.2",
  "nuxt": "2.15.8",
  "vee-validate": "3.4.12",
  "vue-axios": "3.2.5",
  "vue-pull-to": "0.1.8",
  "vue2-touch-events": "3.2.2"
},
"devDependencies": {
  "@capacitor/cli": "3.2.3",
  "@nuxtjs/tailwindcss": "4.2.1",
  "@tailwindcss/forms": "0.3.3",
  "fibers": "5.0.0",
  "postcss": "8.3.6",
  "sass": "1.35.2",
  "sass-loader": "10.2.0"
}
```

### Platform(s)

- iOS
- Android

### Current Behavior

I need  to be able to clear out push notifications that have been delivered to both iOS and Android devices apart from clearing out the latest notification. From a previous Github issue, I'm now aware that I need to first get the delivered notifications and then group them and finally remove them.

In my app, a user grants permissions to push notifications, and a device token is stored in their account, I'm then using Firebase on my server to send notifications to the device as per the format there.

After a notification has been delivered on my iOS device, I can see it in the Notification Centre, but when calling [getDeliveredNotifications](https://capacitorjs.com/docs/apis/push-notifications#getdeliverednotifications) I'm getting the following error thrown:

> Error: event capacitorDidRegisterForRemoteNotifications not called. Visit: https://capacitorjs.com/docs/apis/push-notifications for more information

After checking the docs there's nothing that mentions remote notifications under this method.

### Expected Behavior

When calling `getDeliveredNotifications`, I expect an array of notifications that are on my device that haven't been cleared for both iOS and Android, depending on my platform I'm on.

### Code Reproduction

I'm using Nuxt JS, and have an `async` function like this:

```javascript
async getDeliveredNotifications () {
  try {
    const notifications = await this.$CapacitorPushNotifications.getDeliveredNotifications()
    alert(notifications)
  } catch (err) {
    alert('error with getting delivered notifications')
    alert(err)
  }
}
```

This function runs from another function that calls `checkPermissions`, so that only if the user has granted permissions will this run, which I have.

### Additional Context

I think additional information in the plugin docs is needed, potentially a JS example, much like the example provided by the storage plugin. It's not totally clear how all of these functions are intended to be used

**Comment by Ionitron** [comment] 2021-09-16 15:08
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by sts-ryan-holton** [comment] 2021-09-16 15:09
@Ionitron shouldn't need any reproduction for this, the error received is`capacitorDidRegisterForRemoteNotifications`

**Comment by jcesarmobile** [comment] 2021-09-16 15:35
In the other issue you created I told you to create a new issue with a sample app, you created a new issue without a sample app.
Having a sample app helps us reproduce the issue, but if you don't want to provide sample app I understand, but sadly I can't reproduce, so I'm closing the issue.

**Closed by jcesarmobile** 2021-09-16 15:35 UTC
Labels: platform: android, platform: ios, needs reproduction
