### ISSUE TITLE
Module '"@capacitor/browser"' has no exported member 'OpenOptions'

### ISSUE THREAD

**Issue by WuglyakBolgoink** [ionic-team/capacitor-plugins#898] opened 2022-03-26 13:41 UTC
### Plugin(s)
- Browser@latest

### Capacitor Version

```
latest
```

### Platform(s)
no

### Current Behavior
See error on build:

```
error TS2305: Module '"@capacitor/browser"' has no exported member 'OpenOptions'.
10 import { OpenOptions } from '@capacitor/browser';
            ~~~~~~~~~~~
```

### Expected Behavior
no errors on build

### Code Reproduction
nothing

### Other Technical Details
nothing

### Additional Context
nothing

**Comment by Ionitron** [comment] 2022-03-28 09:07
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment] 2022-04-13 00:02
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Closed by Ionitron** 2022-04-13 00:02 UTC
Labels: needs reproduction, needs reply
